# 共通末尾_ルート分岐.txt 
[info]
122 = "回り始める動輪"

[characters]

[character_subs]

[script]
# lines: 0 
[selections]
103 = "Tham khảo ý kiến của Hachiroku"
107 = "Tham khảo ý kiến của Paulette"
126 = "Tham khảo ý kiến của Hibiki"
