# ハチロクh4_ゼリー・シリンジ・コンドーム.txt

[info]

[characters]
1255 = "Hachiroku"
1320 = "Soutetsu H"

[character_subs]
1539 = "Suzu"
1586 = "Soutetsu"

[script]
670 = "——Mong muốn của tôi, cũng đang trùng khớp với mong muốn của Suzu."
674 = "「——Lúc làm tình,\\nnên tìm kiếm những nơi sung sướng mới mẻ hơn」"
677 = "「Ô——ồ——cái nàyっ——」"
680 = "「…………」"
866 = "「Không được! Vẫn chưa——っ——chịu đựngっ——ưm——\\nPhù!!!」"
867 = "「Đú, đúng——vậy……nhỉっ——ưm——\\nSự sung sướng……mới——mẻっ——phù a」"
869 = "「Không chỉ vậy, nghe nói còn để phòng tránh nhiễm khuẩn nữa ạ.\\nLỗ bài tiết, dù sao cũng là lỗ bài tiết mà」"
871 = "「Gì đây? Thùng các-tông này」"
873 = "「Dù em nói vậy, nhưng không nhìn thì sao mà bôi được chứ」"
875 = "「Nhưng mà, anh không muốn cắm ba cái dụng cụ gì đó,\\nvào cơ thể đáng yêu của Suzu của anh đâu」"
876 = "「Nhưng mà, em hiếm khi dùng đến bộ phận đó cơ mà?」"
878 = "「Đồ của Suzu à?」"
881 = "「Vậy bao cao su, cũng là để bôi trơn tốt hơn sao?」"
882 = "「Chà. Bao cao su cũng được dùng như vậy nữa cơ ạ」"
886 = "「Một chút nữa thôi——anh cũng——Suzu,\\nchịu đựng——thêm một chút nữa——thôiっ——」"
889 = "「A, giao đến rồi nhỉ」"
890 = "「Ra là vậy……ống tiêm là dùng cho việc này sao」"
905 = "「Chắc chắn chúng ta sẽ không chỉ dừng lại ở việc quan hệ qua đường hậu môn đâu.\\nHơn nữa——」"
906 = "「Chỉ cần vượt qua được cửa vào——\\nlà trơn tru ngay ấy mà」"
909 = "「Hả? A……vâng……a」"
912 = "「Hya——á——không được——chịu đựng——a——\\nkhông thể——đượcっ——ưm——vìっ——mông emっ」"
914 = "「Á——xấu hổ——lắm ạっ——ưm——rõ ràng, là,\\nmông, thế mà, em——á a——a——lại thế, này」"
915 = "「Á——mông——của em——mông emっ——\\nđang được ngài Soutetsuっ——ngoáy——vào——rồi」"
918 = "「Á——bên trong âm đạo——có gelっ——lạnh——quáっ\\nƯm……phù a——a」"
919 = "「Á——ngài Soutetsuっ——chậm——như vậyっ,\\nchậm, chạp——như vậyっ——hi a!」"
926 = "「Kya fư!? Cô bé——hột leっ——\\nchạm, vào rồi——ưm ưm～～～～～～～!!」"
927 = "「Hi a——a——ưm——tuột——ra, mất——」"
928 = "「Hya a a a a a n!?」"
929 = "「Hya a a!? A——bị nhấn vào——ngoáy, rồi」"
931 = "「Kyu fư ư ư! A——trơn tuột——\\ncái nàyっ——thích quá!!!」"
932 = "「Hya ư!?」"
933 = "「Hya gư!? A——khoét sâuっ——ưm——\\nhyu a!!!」"
934 = "「Hya fư!? A! Đó——chỗ đó!」"
935 = "「Hya ư!? Ưm——hi——\\ntrơn tuột——mông em——a——cái nàyっ——sâu quá——」"
936 = "「Á ưm!? Mông em!?」"
938 = "「Á!? Ngài, Soutetsuっ——á——\\ncậu bé——rút ra——không chịu, đâu——ưm」"
940 = "「Ufufu, xin ngài đừng cứng đơ ra như vậy chứ, ngài Soutetsu?\\nKhông có gì đáng sợ đâu ạ.」"
942 = "「Ư fufu, ngài xem này」"
944 = "「Phù——」"
945 = "「Phù」"
946 = "「Phù a——a——a——a a——」"
947 = "「Phù a——a」"
949 = "「Á——cậu bé——đừng ra——nhé」"
952 = "「Ehehe……chụt——chụt」"
954 = "「Hả!? Ơ——dạ,\\nbị ngài nhìn chằm chằm như vậy, quả thực là——」"
955 = "「Ư——a——」"
956 = "「Ư!」"
957 = "「Hử!?」"
958 = "「A——đến rồi——hôn đi——cô bé——\\ntận cùng, bên trongっ——tử cung, hãy,——hôn đi」"
959 = "「A——xin lỗi, anh nhìn đến mê mẩn mất rồi」"
962 = "「Ư a――――cái này, là——っ」"
965 = "「A……phù……a……nóng quá……\\ntinh dịch……của……ngài Soutetsu……phù——a——」"
966 = "「A……vâ, vâng. Nếu dùng cái đóっ——ưm——\\nbên trong, hậu mônっ——có thể tiến sâu, hơn nữa——a」"
968 = "「A……giá như ngài để em làm cho thì tốt biết mấy」"
970 = "「A……ngài Soutetsu」"
971 = "「A hyu!!?」"
973 = "「A……ừm.\\nĐó là lời tôi đã nói mà.」"
974 = "「A a!」"
975 = "「A a! Cậu bé! Của ngài Soutetsu,\\ncậu bé của ngài Soutetsu! Ưm ư!!」"
977 = "「A a, cô bé——\\ncô bé tuyệt vời nhất——của Suzu」"
979 = "「Hự!」"
980 = "「À, ra là vậy」"
983 = "「A, v, vângっ——\\ntheo ý, ngài Soutetsuっ!?——ưm hưm!」"
985 = "「A, nóng——quá——mông emっ——bụng, cũngっ——\\nưm——nóng, quá ạっ——Ngài, Soutetsu——」"
987 = "「Chụt——ưm——liếm——chụt——liếm láp,\\nchu mút——trượt——chụt」"
988 = "「Phu ya!?」"
989 = "「Hự——a——」"
991 = "「Ưm……a——ưm chụt——phù a——a!?\\nBên trong, mông em——ngài Soutetsu——càng lúc, càng to ra」"
993 = "「Vâng.\\nEm nghĩ thỉnh thoảng cũng nên dùng đến tiền lương xem sao」"
994 = "「Vâng. Vì vậy……」"
996 = "「Hừm. Dùng cái này à」"
998 = "「Vâng. Chuyện là……\\nem ấy mà?」"
999 = "「Ừm」"
1000 = "「Ư iiii!!?」"
1002 = "「Ưm! Kư fư ư ư」"
1003 = "「Hự!?」"
1004 = "「Hửm? A……ống tiêm à.\\nRốt cuộc lại chẳng dùng đến.」"
1007 = "「Hửm? Không, điều đó là hiển nhiên rồi.\\nThực tế thì ngay lúc này, tôi cũng đã rất sung sướng với hậu môn của Suzu.」"
1009 = "「Ha pư——a——Ngài Soutetsu——liếm——\\nNgài Soutetsu」"
1010 = "「Chính vì vậy, Suzu à.\\nPhải tìm cách khác thôi——à」"
1013 = "「A——a——em không biết——cảm giác nàyっ——a——\\nđang cắm vào——vậy màっ——sâu, quá——vậy màっ——ưm」"
1015 = "「Tuyệt thật……đấy——\\nTrí tuệ và dụng cụ của chuyên gia quả là——」"
1016 = "「Ngoan lắm」"
1018 = "「Thì là……chuyện,\\nchuẩn bị tâm lý cho những lúc thế này ấy ạ」"
1020 = "「E, em sẽ chịu đựng——sẽ chịuっ——hyu——chịu đựngっ——\\nVì——ngài Soutetsuっ——cùng nhau——kư fưn!!」"
1022 = "「Em cũng vậy——em cũng vậy——Ngài Soutetsu」"
1024 = "「Ý em không phải vậy.」"
1026 = "「Suzu——thay đổi tư thế nhé?」"
1028 = "「Em đã từng học qua rồi.\\nĐàn ông cũng có thể cảm thấy sướng ở hậu môn đó ạ.」"
1034 = "「Chỉ cắm ngón tay vào thôi mà đã khó khăn đến thế,\\nnhìn xem……sự trơn tru này là sao chứ」"
1036 = "「Anh hiểu rồi.\\nNhưng bộ đồ ngủ này đáng yêu lắm. Cởi hết ra thì phí quá」"
1037 = "「Anh hiểu rồi」"
1039 = "「Vâng……em hiểu rồi ạ, ngài Soutetsu」"
1041 = "「Vâ, vâng——ngài Soutetsuっ——a——cứ thế——\\nnàyっ——, cùng, nhauっ——ưm」"
1042 = "「Vâ, vâng. Em cũng hiểu điều đó nhưng mà——\\nX, xấu hổ quá, nên……em lỡ dùng sức mất rồi」"
1043 = "「Đúng vậy——hãy tận hưởng——cho thỏa thích đi」"
1045 = "「À, anh có nói vậy」"
1047 = "「Đúng thật. Để em đeo cho cũng tốt,\\nmà bản thân anh, cũng muốn tự tay cởi quần lót của Suzu nữa」"
1049 = "「Gel bôi trơn, ống tiêm, và bao cao su ạ」"
1051 = "「Về chuyện đó thì, ngài Soutetsu.」"
1055 = "「Quả nhiên——thế này——\\nmới có cảm giác hòa làm một, với Suzu」"
1058 = "「Không sao đâu——hãy lên đỉnh thỏa thích đi」"
1061 = "「Nếu dùng gel để đưa vào âm đạo, biết đâu đấy,\\nchúng ta lại có thể tìm ra một sự sung sướng mới mẻ nào đó」"
1062 = "「Áo ngủ này, em có thể nhờ ngài Soutetsu cởi giúp được không ạ?」"
1064 = "「Hậu môn——bên trong hậu môn, vốn dĩ là nơi để bài tiết.\\nKhác với âm đạo, việc tiếp nhận cậu bé nằm ngoài mục đích của nó」"
1065 = "「Vì vậy hậu môn không thể tự bôi trơn được.\\nGel được dùng để bù đắp cho điều đó ạ」"
1069 = "「Sung sướng không em?」"
1070 = "「Á!」"
1072 = "「Anh á? Chuyện gì cơ?」"
1073 = "「Biết đâu vì không dùng nên ngược lại——cũng nên ạ.\\nChuyện này, hoàn toàn là vì cơ thể của ngài Soutetsu thôi ạ」"
1074 = "「Dạ, dạ——ngài Soutetsu?\\nCô bé thì——ưm hưm——không cần——gel đâu ạっ」"
1075 = "「Xin ngài cứ yên tâm. Lỗ hậu môn đáng yêu của ngài Soutetsu,\\nlàm sao em nỡ nhét ống tiêm vào chứ? Tiếc lắm ạ.」"
1081 = "「À thì……là dụng cụ dùng để tránh việc mang thai ngoài ý muốn……\\nanh nghĩ vậy」"
1082 = "「Lần này, thì——em——ưm——\\ncho đến khi, ngài bắn ra——em sẽ——chịu đựngっ」"
1086 = "「Dụng cụ tránh thai, là gì vậy ạ?」"
1087 = "「Dụng cụ tránh thai, là gì ạ?」"
1090 = "「Nhân dịp đó——em cũng đã nghe về quan hệ qua đường hậu môn,\\nnên em đã tự mình tìm hiểu ạ」"
1092 = "「Tốt đấy.\\nVậy, em đã mua gì?」"
1094 = "「Không phải vậy?」"
1096 = "「Thế nàyっ——a——vẫn đang cắm, bên trongっ——ưm hưm!\\nA——sâu quá——kư ha a!」"
1097 = "「Vậy thì, ngài Soutetsu」"
1098 = "「Ống tiêm? À, kim tiêm à.\\nBao cao su……là, dụng cụ tránh thai đúng không?」"
1099 = "「Su——zu」"
1100 = "「Suzu——không, em, lẽ nào.」"
1101 = "「Suzu——ra nào. Cùng nhau, ra nhé」"
1102 = "「Suzu」"
1103 = "「Suzu muốn, ngài Soutetsu cắm cậu bé của ngài\\nvào hậu môn——vào lỗ mông của em ạ」"
1104 = "「Suzu! Suzu!!」"
1105 = "「Suzu,\\nem mua bao cao su để làm gì?」"
1106 = "「Suzu, bám chặt vào nhé?」"
1107 = "「Suzu. Nói cho anh biết đi. Cậu bé đẫm gel này,\\nanh nên cắm vào đâu của Suzu đây」"
1108 = "「Suzu. Thế này thì anh không thể nới lỏng bên trong được đâu」"
1121 = "「N, ngài Soutetsu——phu ya——cái nàyっ——\\ntuyệt quá——kư hi i i ưm!」"
1122 = "「Ngài Soutetsu……」"
1123 = "「Ngài Soutetsu……đã chỉ dạy cho em rồi mà」"
1124 = "「Ngài Soutetsu……hôn em……hôn em……」"
1125 = "「Ngài Soutetsu? Nào, chúng ta cùng tìm thử nhé?\\nNơi sung sướng mới mẻ mà ngài Soutetsu vẫn chưa biết tới.」"
1126 = "「Ngài Soutetsu?」"
1127 = "「À, ra là vì vậy nên em mới trải khăn tắm」"
1128 = "「!」"
1129 = "「!?」"
1131 = "「~~~~~~~~!!!」"
1269 = "Rồi, vẫn mặc nguyên áo——"
1270 = "Vậy thì lần tới, anh sẽ vệ sinh sạch sẽ bên trong hậu môn,\\nđể có thể kết nối với Suzu qua đường hậu môn mà không cần vật cản nào."
1280 = "Nhưng, bây giờ là lần đầu tiên, cả hai chúng ta đều là người mới.\\nTốt nhất là cứ ngoan ngoãn làm theo những gì Suzu đã học."
1283 = "Nhưng điều đó lại phản tác dụng.\\nSuzu siết chặt hậu môn lại, ngoan cố từ chối ngón tay tôi."
1285 = "Nhưng, vẫn chưa xong.\\nTuy đã quan hệ qua đường hậu môn nhưng——"
1286 = "Nhưng, vẫn không lỏng ra.\\nNếu vậy, chỉ còn cách dùng chiêu khác thôi."
1288 = "Nhưng dù vậy, nếu không có gel,\\ncó lẽ giữa chừng em ấy lại siết chặt lại và đau đớn mất thôi."
1291 = "Nhưng, nếu vậy thì……"
1292 = "Nhưng, Suzu hoàn toàn không bận tâm,\\nem lúi húi đưa tay——"
1298 = "Hậu môn vẫn chưa nói với tôi điều gì,\\nnhưng cô bé của Suzu lại đang truyền đạt dục vọng một cách hùng hồn đến thế này."
1301 = "Che giấu những nơi không được phép nhìn thấy. Xét về vai trò của quần lót,\\nthì cảnh tượng này chỉ có thể coi là phản tác dụng."
1305 = "Đôi mắt vừa mới mờ đục đi vì khoái cảm,\\ngiờ lại bỗng chốc sáng long lanh."
1306 = "Suzu vừa mới lên đỉnh ban nãy, nhìn kiểu gì cũng thấy em đã đến giới hạn rồi.\\nNhưng tôi thì ngược lại…… nếu có thêm một chút kích thích mạnh hơn nữa thì——"
1313 = "Di chuyển, có thể di chuyển được.\\nCả cửa vào chật hẹp, lẫn bên trong hậu môn khít rịt."
1316 = "Đôi môi hé mở. Chiếc lưỡi mềm nhũn."
1324 = "Trước sự kích thích mạnh mẽ, đơn thuần và bạo liệt đó,\\nđê điều tinh dịch của tôi cũng vỡ tung!"
1326 = "Do bị kéo căng,\\nnên quần lót cũng hằn sâu vào khe hở của cô bé."
1327 = "Việc ngoáy sâu hết mức vào tận cùng cơ thể Suzu,\\nmang lại cảm giác chinh phục, thành tựu và khoái cảm khi được kết nối. Nhưng."
1329 = "Bằng đầu ngón tay thoa đẫm gel,\\ntôi gõ nhẹ \"cốc cốc\" vào cửa hậu môn."
1332 = "Những nếp gấp nhung lụa rối bời,\\nbám chặt lấy quy đầu, nhào nặn điên cuồng."
1334 = "Dù không nói ra miệng là sung sướng,\\nnhưng em đã ngầm thừa nhận điều đó."
1337 = "Rồi em cuộn ngón tay lại thành hình ống,\\nvà đâm mạnh ống tiêm vào trong đó——!!?"
1339 = "Giọng nói nóng bỏng."
1341 = "Như không muốn để tôi thoát khỏi điểm đó,\\nbên trong âm đạo Suzu bám riết lấy tôi, nũng nịu quấn quýt."
1343 = "Ánh mắt em mờ đi vì nóng,\\ntoàn thân cũng nóng ran và đẫm mồ hôi."
1345 = "Trong bộ đồ ngủ, mái tóc đen còn ướt.\\nNụ cười rạng rỡ đầy vui sướng."
1347 = "Em nằm lăn ra chiếc đệm vừa trải,\\nxấu hổ né tránh ánh nhìn của tôi."
1349 = "Nghe em nói chữ \"cũng\", tôi thở phào nhẹ nhõm.\\nQuả nhiên, em mua không phải với mục đích tránh thai."
1351 = "Suzu hớn hở mở thùng các-tông ra.\\nBên trong là——"
1353 = "Sâu quá, sâu quá. Không có điểm dừng."
1355 = "Nhấc bổng Suzu lên và áp sát hông vào nhau hết sức có thể,\\ntôi nhận ra việc không có điểm tận cùng——không chỉ mang lại cảm giác trống trải."
1361 = "Dù tôi có dừng lại, âm đạo vẫn tự động run rẩy,\\nngoan ngoãn khao khát tinh dịch tươi mới của tôi đến nhường này."
1364 = "Tất nhiên cũng nhờ đã nới lỏng từ trước.\\nDù ít ỏi nhưng cũng có kinh nghiệm, và chắc hẳn cũng có cả sự kỳ vọng nữa."
1365 = "Rồi bằng tay trái, tôi nhanh chóng tháo bao cao su vứt đi——"
1382 = "Vậy thì, tôi lại càng muốn ngoáy sâu hơn nữa để bôi gel cho em.\\nNhưng, bên trong hậu môn quá sâu, ngay cả ngón giữa cũng không thể nào với tới được."
1383 = "Tôi cũng là đàn ông.\\nNói lời phải giữ lấy lời."
1385 = "Tôi cũng kiệt sức.\\nNằm ườn ra bên cạnh Suzu."
1388 = "Tôi cứ tưởng mình biết rõ điều đó,\\nnhưng sự tự tin bỗng chốc tan biến."
1391 = "Một nụ hôn cuồng nhiệt.\\nKhoang miệng được lưỡi em âu yếm, còn bên trong âm đạo thì phần cương cứng của tôi đang được nâng niu."
1392 = "Tôi hôn em say đắm,\\ntrao đổi khoái cảm ướt át và nước bọt như đang chà xát vào nhau."
1394 = "Tôi ép chặt quy đầu vào cửa tử cung đang run rẩy liên hồi,\\nnhốt toàn bộ tinh dịch vào sâu bên trong em."
1397 = "Bàn tay vuốt ve cô bé vẫn không hề ngơi nghỉ——"
1399 = "Cạch, cạch, tôi tháo từng chiếc cúc áo phía trước ra."
1400 = "Tôi mạnh bạo ấn hông xuống như muốn xé toạc nơi đó ra——"
1402 = "Điều đó khiến tôi bất an, nhưng lại vô cùng sung sướng,\\nvì vậy tôi muốn kết nối với em đến tận cùng!"
1404 = "Tôi thầm thán phục sự chu đáo, tỉ mỉ đúng chất Suzu.\\nVà đưa ngón tay về phía lỗ nhỏ khép nép, e lệ cũng rất giống em ấy."
1406 = "Lấy gel từ trong hộp ra và thoa đều lên ngón tay,\\nkhông hề bị rối, cũng không dính nhớp, mà thực sự rất mượt mà và dễ chịu."
1408 = "Lời nói thốt ra theo phản xạ,\\ntôi chợt nhận ra nó đã biến thành một câu chơi chữ ngớ ngẩn (anarunaru hodo)."
1410 = "Tôi muốn chạm vào làn da ấy. Muốn chạm vào lỗ hậu môn ấy.\\nMuốn thấy phản ứng của một Suzu ngoan ngoãn, kiên cường."
1411 = "Nếu vậy, tôi cũng muốn cho Suzu biết niềm vui này.\\nSuy nghĩ đó ngay lập tức biến thành một câu nói rất đơn giản."
1413 = "Tôi nhớ ra thứ mình đang cầm trên tay.\\nThứ thứ hai——công tắc khoái cảm của Suzu."
1415 = "Đeo bao cao su vào, rồi trên đó,\\ntôi thoa một lớp gel bôi trơn hậu môn thật dày."
1418 = "Nhấc bổng cơ thể Suzu lên, dùng phần khấc quy đầu,\\ntôi càng làm mở rộng thêm lỗ hậu môn đang chực siết lại."
1420 = "Tôi rút ngón tay ra."
1421 = "Vuốt ve trơn trượt quanh hậu môn,\\ntôi nghe thấy giọng nói đầy vẻ sung sướng của em."
1423 = "Đẩy ngón tay vào lỗ hậu môn không báo trước,\\nSuzu thốt lên một tiếng xen lẫn giữa sự kinh ngạc và khoái cảm."
1424 = "Dùng tay phải và toàn thân đỡ chặt cơ thể Suzu,\\ntôi từ từ rút toàn bộ phần cương cứng ra."
1426 = "Đâu đó tôi từng nghe câu thành ngữ \"đào lỗ hậu môn\",\\nra là vậy, cái này——quả thực, mang lại cảm giác đang đào xới."
1428 = "Trải qua lịch trình quen thuộc trở về phòng,\\nmột khung cảnh hơi khác lạ so với mọi khi đang chờ đón tôi."
1432 = "Di chuyển, và ma sát.\\nChỉ với khoái cảm đơn thuần đó, tôi có thể tập trung đến tận cùng, tận cùng."
1440 = "Uốn cong ngón tay đang cắm trong âm đạo như chiếc móc rồi cử động,\\nSuzu phản ứng lại thật đáng yêu, mật ngọt tuôn trào nhầy nhụa."
1441 = "Vừa siết chặt, Suzu vừa ngoáy tít hông."
1445 = "Đã nới lỏng và làm ướt đến mức này rồi,\\ntôi có cảm giác chỉ cần thế là đủ, nhưng——"
1449 = "Một lực thít chặt không khoan nhượng!"
1450 = "Từ tư thế cực kỳ chông chênh,\\nlần này tôi đột ngột đổi hướng! Dồn toàn lực vào hông!!"
1458 = "Mồ hôi quyện vào mồ hôi, hai cơ thể cũng đang hôn nhau.\\nDù không thể cắm sâu như hậu môn, nhưng chúng tôi lại đang kết nối sâu sắc hơn bao giờ hết."
1473 = "Chỉ nhìn thôi cũng thấy hạnh phúc vì sự đáng yêu ấy."
1475 = "Có thứ gì đó, chạm nhẹ vào khuỷu tay tôi——"
1480 = "Kết thúc ca trực, ngâm mình trong nước nóng,\\nrồi đón gió đêm trở về nhà."
1485 = "Em khẽ cắn yêu vào dái tai tôi,\\nrồi dùng chiếc lưỡi mềm mại xoa dịu vết cắn ấy."
1488 = "Sâu đến thế này, khít rịt đến tận gốc rễ thế này——\\nKhoái cảm được bao bọc hoàn toàn càng làm tăng thêm tình yêu thương trong tôi."
1495 = "Hậu môn cũng có cái sướng riêng của nó."
1496 = "Hậu môn siết chặt lại một cách khác thường,\\nbáo cho tôi biết Suzu đã đạt đỉnh!"
1499 = "Vùng ngực dần lộ ra,\\nvà rồi, những nụ hoa đáng yêu nhô lên e ấp."
1504 = "Tiếng hông và mông va chạm vào nhau.\\nMột nhịp trễ, phần gốc bị siết chặt mạnh mẽ."
1508 = "Đương nhiên tôi sẽ chịu trách nhiệm với những gì mình đã nói."
1510 = "Không có sự phức tạp. Tuy siết chặt, nhưng lại đơn điệu.\\nNhưng, chính vì thế——"
1520 = "Càng cử động, sự hưng phấn càng tăng lên."
1527 = "Không phải là làm tình với hậu môn của Suzu,\\nmà là cùng với Suzu——làm tình bằng trọn vẹn thể xác và tâm hồn."
1528 = "Điều đó mang lại cảm giác trống trải vô tận,\\ndù đang kết nối, nhưng lại muốn kết nối sâu sắc hơn nữa."
1529 = "Thế này thì gel sẽ nhanh chóng bị cuốn trôi mất thôi.\\nNhưng, thế cũng tốt. Chỉ lúc này thôi——vì mục tiêu chính nằm ở nơi khác mà."
1530 = "Vừa dùng đầu ngón tay tận hưởng cảm giác như cao su, khác hẳn với cô bé,\\ntôi vừa thoa gel lên vách thịt."
1531 = "Dù ướt át và trơn tru đến vậy,\\nnhưng da thịt cọ xát vào nhau vẫn sinh ra nhiệt."
1532 = "Nếu là thứ mượt mà thế này,\\nthì chắc chắn sẽ tràn ra ngoài."
1536 = "Rồi trên đó……rốt cuộc là để làm gì cơ chứ?\\nEm trải gọn gàng những chiếc khăn tắm còn thừa từ đợt phát dịp cuối năm."
1538 = "Rất thon gọn.\\nNhìn kỹ thì cũng không có kim tiêm ở đầu."
1540 = "Suzu không thể mang thai nên chắc chẳng liên quan gì đến việc tránh thai……\\nCó lẽ kiến thức của tôi có chỗ nào đó sai sót chăng."
1541 = "Rồi Suzu ngước nhìn tôi,\\nvà giải thích bằng giọng điệu nóng bỏng."
1542 = "Miệng nói vậy, nhưng Suzu lúi húi cởi hẳn chiếc quần lót ra.\\nGấp lại rồi cất xuống dưới gối——"
1543 = "Bỏ ống tiêm ra, Suzu bôi đẫm\\ngel bôi trơn hậu môn lên ngón tay mình."
1544 = "Không thốt nên lời, khuôn mặt đỏ bừng, toàn thân run rẩy không ngừng,\\nSuzu đang lên đỉnh."
1545 = "Suzu lấy ống tiêm từ tay tôi."
1546 = "Suzu lúi húi,\\ncởi quần ra, gấp gọn gàng rồi đặt sang một bên."
1547 = "Liên tiếp.\\nSuzu rùng mình mạnh mẽ, rồi lả đi."
1548 = "Đón nhận nụ hôn nũng nịu của Suzu,\\ntôi cứ thế nhẹ nhàng đặt em nằm xuống nệm."
1549 = "Suzu dịu dàng ôm lấy tôi,\\nnhẹ nhàng vuốt ve lưng tôi——!!!?"
1550 = "Suzu đỏ bừng mặt.\\nDù đỏ mặt, nhưng bàn tay đang kéo quần lót xuống vẫn không hề nhúc nhích."
1551 = "Chiếc quần lót trong sáng đến chói mắt, đúng phong cách của Suzu.\\nEm nhẹ nhàng dùng ngón tay ấn lõm phần mông——chỗ cái lỗ."
1552 = "Dù ngón tay đang thoa đẫm gel vẫn có thể cảm nhận rõ ràng,\\ncô bé của Suzu đang ướt đẫm."
1553 = "Lỗ hậu môn nhỏ bé của Suzu,\\nnhư thể đang hít thở vậy."
1554 = "Bên trong hậu môn của Suzu——tận sâu bên trong,\\nchật hẹp, đơn giản và thẳng tắp."
1555 = "Ánh mắt của Suzu,\\ndẫn dắt ánh nhìn của tôi hướng lên khuôn ngực quá đỗi bằng phẳng của em."
1556 = "Nghe Suzu nói vậy, tôi thở phào——không nổi."
1557 = "Toàn bộ lỗ âm đạo của Suzu dang rộng vòng tay chào đón, ôm chầm lấy tôi."
1558 = "Suzu vẫn mặc nguyên quần lót,\\ncứ thế kéo căng cho nó nhỏ lại, để lộ ra lỗ hậu môn đáng yêu."
1559 = "Vừa nói, Suzu vừa trải đệm ra."
1560 = "Những ngón tay trắng ngần vạch hai cánh mông ra,\\nmở rộng lỗ hậu môn đang khép chặt."
1561 = "Mái tóc Suzu đung đưa chạm vào người tôi.\\nChỉ một chút vậy thôi cũng đủ khiến khoái cảm râm ran dâng trào."
1587 = "Tôi ép chặt, rồi nhấn sâu thêm chút nữa."
1588 = "Vẫn không có nơi nào chào đón phần đỉnh.\\nTử cung không trao cho tôi nụ hôn \"chụt\" nào cả."
1592 = "Ban đầu tôi chỉ định ấn nhẹ quy đầu vào——\\nnhưng nó lại trơn tuột, tiến vào mà không gặp chút trở ngại nào——"
1649 = "（Ra là vậy——được người khác làm cho, hay được làm cho người khác,\\ncũng là một trong những niềm vui của việc làm tình nhỉ）"
1651 = "（Siết chặt!）"
1653 = "（Siết, siết chặt）"
1655 = "（Phập——trượt——）"
1656 = "（Phập——trượt——phập——chu mút）"
1658 = "（Phập!!!）"
1659 = "（Phập!）"
1661 = "（Phập——phập——trượt——phập——）"
1662 = "（Phập!!!）"
1663 = "（Phập!!!!）"
1664 = "（Phập!）"
1666 = "（Trượt trượt trượt trượt trượt）"
1667 = "（Trượt——phập! Trơn tuột——phập!!）"
1668 = "（Trượt——phập! Phập! Bụp!）"
1669 = "（Trượt!!!）"
1670 = "（Phập! Phập! Phập! Phập!）"
1672 = "（So với âm đạo……quả nhiên là khác biệt nhỉ）"
1673 = "（Bụp!）"
1674 = "（Nhấc bổng!）"
1675 = "（Bụp）"
1676 = "（Nhóp nhép——phập——）"
1677 = "（Cộc）"
1680 = "（Nhấc bổng!!）"
1681 = "（Nhấn mạnh!）"
1682 = "（Kéo）"
1683 = "（Ư ư ư!）"
1684 = "（Trượt——ra——ra——ra——rồi!）"
1685 = "（Trượt ra!!!）"
1687 = "（A, đúng rồi）"
1688 = "（Phập!!）"
1689 = "（Phập!）"
1690 = "（Chụt）"
1691 = "（Siết! Siết chặt!!）"
1692 = "（Siết! Siết chặt!!）"
1693 = "（Kéo）"
1695 = "（Phụt! Phụt——phụt——）"
1697 = "（Phụt! Phụt! Phụt! Phụt!）"
1699 = "（Phụt! Phụt! Phụt! Phụt）"
1700 = "（Phập）"
1702 = "（Đúng vậy nhỉ……dù cắm sâu đến mức này——）"
1703 = "（Phập）"
1705 = "（Trượt——siết chặt——râm ran）"
1708 = "（Trượt——nhét——ngoáy——nhét——）"
1709 = "（Trơn tuột）"
1712 = "（Bụp）"
1713 = "（Siết chặt!）"
1714 = "（Thít chặt!!）"
1715 = "（Vuốt ve——vuốt ve——nhóp nhép——nhóp nhép——）"
1716 = "（Vuốt ve）"
1718 = "（Trơn tuột～）"
1719 = "（Đang giật giật——có vẻ lỏng ra rồi nhỉ）"
1722 = "（Lăn ra）"
1724 = "（Cái này……tuyệt thật）"

[selections]
