# ハチロクh5_おだいどこしごと.txt

[info]

[characters]
1316 = "Hachiroku"
1369 = "Soutetsu"
1370 = "Soutetsu H"

[character_subs]
1594 = "Suzu"
1623 = "Soutetsu"

[script]
743 = "——Trao nhau một nụ hôn thật khẽ."
748 = "……Cơ thể tôi, dần dần nóng lên.\\nSuzu, thật đáng yêu. Đáng yêu đến phát điên."
753 = "「Hà……ưm——chụt——liếm——chụt——\\nchụt——chùttt——ngấu——ực」"
756 = "「……Ưm. Phù.\\nMôi của Suzu, đúng là món khai vị tuyệt hảo nhất.」"
757 = "「Vâng……ạ. Thành phần của nó thì——\\nlà nước thải từ hơi nước chưa dùng hết được làm lạnh và hoàn nguyên.」"
759 = "「Á……em xin lỗi——em xin, lỗi——\\ne-em——đã tè dầm——tè dầm mất rồi——ưm.」"
936 = "「Hảo hạng……nước tiểu——của em, sao.」"
939 = "「Sai rồi. Suzu. Là chị Mayami và Hibiki.」"
941 = "「Không phải, vậy đâu——a——bây giờ, thì——chuyện đó——ưm!\\nXin ngài——hãy rút ngón tay——rút tay ra, đi ạ.」"
943 = "「Tấm gương gì chứ, em bây giờ, chỉ là một người phụ nữ thôi.\\nVà người nhìn thấy dáng vẻ này của em, trên thế giới này, cũng chỉ có một mình tôi.」"
944 = "「Đừng hoảng, Suzu.」"
947 = "「Nhưng mà, chỗ này đang giật liên hồi thế này cơ mà?\\nCứ thế rút ngón tay ra chắc em sẽ hụt hẫng lắm.」"
950 = "「Chuyện bất đắc dĩ thôi——mà phải nói là, trong lúc bận rộn tối tăm mặt mũi thế này,\\nSuzu vẫn học được cả nấu ăn cơ đấy. Tôi vui lắm.」"
952 = "「Đến nước này rồi, em còn ngại ngùng gì nữa.」"
953 = "「Trước khi ăn cơm, Suzu. Tôi muốn ăn em.\\nTrong tình trạng này, tôi chẳng thể nào tập trung vào bữa ăn được đâu.」"
957 = "「Nhưng mà……chỗ này……là nhà bếp đấy ạ?\\nLàm chuyện này, ở trong bếp thì……」"
958 = "「Nhưng em, chỉ đang mặc tạp dề bình thường thôi mà?\\nĐâu phải trang phục dành cho việc làm tình như tạp dề khỏa thân——」"
960 = "「Đáng yêu quá. Suzu của tôi.」"
962 = "「Em thật sự rất đáng yêu đấy.」"
964 = "「Đến đi! Hãy bắn ra đi ạ, ngài Soutetsu.」"
967 = "「Xin ngài đợi thêm một chút nữa thôi.\\nBật bếp lên, ăn xong bữa cơm rồi chúng ta……」"
968 = "「Đừng khóc, Suzu.」"
969 = "「Không có gì phải xấu hổ cả.\\nEm khao khát tôi, nên mới ướt át đến mức này đúng không?」"
974 = "「Vẫn còn đọng lại?」"
975 = "「Ra vậy, đợt cúm lần này\\nđã vô tình tạo ra cơ hội đó à.」"
992 = "「A……mặc dù, cách lớp quần lót——ưm——hà——á——mà ngài lại nhẹ nhàng như vậy——âm, vật——!」」"
995 = "「Á!? Xấu hổ quá, em——thế này——\\nưm hứ!!?」"
996 = "「Á phù ư ư ư ư ư ư ư ư ưm!!!」"
998 = "「Á!? Không——được——em——\\nđang——đang lên đỉnh——mà——hà, ưm hư ư ư ư ư ư」"
999 = "「Á!? A——」"
1000 = "「Á!? A——không phải vậy——ưm hứ!?」"
1004 = "「Ufufu, mọi người đã ăn rất sạch sẽ mà.」"
1006 = "「Phù a——a——a……aa——\\nem——đã tiểu——vào ngài, Soutetsu——mất rồi——ưm!」"
1008 = "「Phù——a, c-cái đó——như thế, là——\\ná!? Ưm, hí——a——không được, mất thôi.」"
1010 = "「Phù a a a a a a a a a a a a a!!!\\nA!?——Không được——á————a, aa……」"
1011 = "「Phù」"
1012 = "「Hí a——a——nóng quá——sướng, quá.」"
1013 = "「Á! A——x-xin ngài đừng hối thúc em mà.」"
1015 = "「Hí!? A——dương, vật——ưm——\\nđã xuất tinh, rồi mà——còn to——hơn——ưm——hà a.」"
1018 = "「Hà——a——xấu hổ quá——dịch nhờn——\\nthấm ra mất——em, lại thế này——」"
1020 = "「Hà——a! Ưm——đâm mạnh——vào,\\ntử cung——ưm——hí——mạnh quá——sướng, quá.」"
1023 = "「A, nhưng mà ngài Soutetsu!」"
1025 = "「Hả!? A——Ngài Soutetsu——liếm——」"
1026 = "「Hả?」"
1027 = "「Ồ.」"
1029 = "「L-Làm gì có chuyện đó——ngài nói quá rồi, với lại ngài vội vàng quá.\\nVẫn chưa biết thành phẩm sẽ ra sao mà.」"
1030 = "「A——」"
1031 = "「A——đến rồi——ưm! Á——a——\\ntinh dịch——nặng, quá——thế này——sướng quá——!!」"
1033 = "「A——aa——ưm! Ngài Soutetsu——\\nphù a——Ngài Soutetsu.」"
1035 = "「A——ngài đã uống……mất rồi——\\nNgài Soutetsu——Ngài Soutetsu, đã uống nước, tiểu——của em.」"
1037 = "「A——miệng ngài——ưm——miệng của ngài Soutetsu\\n——đang áp sát——vào cô bé của em.」"
1039 = "「A——xin ngài, đợi một chút——\\ne-em——bây giờ, chuyện đó——」"
1041 = "「A……」"
1045 = "「A……hà……a……ngài Soutetsu.」"
1047 = "「A……thích, quá——ngài, Soutetsu——bàn tay ngài,\\nthật chậm rãi——thật dịu dàng——phù——a——hả?」"
1049 = "「A……em vui lắm. Ngài Soutetsu.」"
1050 = "「A……Ngài Soutetsu——」"
1051 = "「A……Ngài Soutetsu——một chút, thôi——」"
1052 = "「A.」"
1054 = "「À, không sao đâu.\\nCứ thế này, em lên đỉnh một lần trước cũng tốt.」"
1055 = "「Ừ, tôi cũng vậy.」"
1057 = "「A! A! Không, được đâu——ngài Soutetsu——」"
1059 = "「A! Có ạ, tạp dề khỏa thân. Ra là vậy, quả thực,\\nnhững người mặc bộ dạng đó, đều làm tình trong bếp nhỉ.」"
1061 = "「Hả!? Sao lại, liên tục thế này——」"
1063 = "「A, dạ……ngài Soutetsu? Em, chuyện đó.」"
1064 = "「Phù á!? A! Không được——nếu ấn vào——\\nưm——nữa——a, phù a——ưm ưm~~~」"
1065 = "「Phù á!? Cái này!——Sướng quá——\\n~~~~~~~~~~!!!!」"
1067 = "「Ưm——a——tử cung——bị——\\nđâm mạnh——bị đâm mạnh vào——ưm hư ư ư ư ư」"
1068 = "「Ưm——a——tuột ra——mất rồi.」"
1069 = "「Ực——ưm——phù——」"
1070 = "「Ưm……ưm————phù a!」"
1073 = "「Ưm hứ!? Phù a!? A a a a a a a a a a!」"
1074 = "「Ưm hí——á!? Kh-Không được——ưm hự」"
1075 = "「Ưm a a a a a!」"
1076 = "「Ưm——ừng ực——ực——ực」"
1077 = "「Ưm hứ ư ư ư ư ư!!!」"
1078 = "「Ưm!」"
1079 = "「Vâng. Mãi mãi về sau. Nhé? Ngài Soutetsu.」"
1081 = "「Ừ. Tôi biết.」"
1083 = "「Ừ, đúng vậy nhỉ.」"
1084 = "「Hửm? À——」"
1085 = "「Ưm~~~~!」"
1087 = "「Cả hai người đều khen Suzu đấy nhé?\\n『Hoàn toàn là hương vị cháo của nhà Migita』.」"
1089 = "「A……nóng quá……ạ. Với lại——ưm——\\ncó vẻ——phù——cứng hơn, mọi khi, ạ.」"
1092 = "「Nhà bếp là một trong những sân khấu chính của tình dục mà.\\nSuzu chưa từng học qua sao? Cái gọi là tạp dề khỏa thân ấy.」"
1095 = "「Cái may, sao ạ?」"
1096 = "「Thật có lỗi với ngài Soutetsu và mọi người,\\nvì cứ phải ăn đồ mua ngoài suốt.」"
1099 = "「Em đã học dần dần từ chị Mayami từ trước rồi ạ.\\nChỉ là em chưa đủ tự tin để trổ tài thôi.」"
1102 = "「Thế nào rồi ạ? Chị Mayami và Hibi——」"
1103 = "「Thế nào rồi ạ?\\nTình hình của chị Mayami và Hibiki ấy.」"
1108 = "「Tôi cũng vậy, Suzu.」"
1109 = "「Em cũng yêu ngài. Ngài Soutetsu.\\nYêu ngài bằng tất cả những gì em có——chỉ một lòng một dạ.」"
1113 = "「Chị Mayami——em chỉ làm đúng theo công thức mà chị ấy dạy thôi ạ.\\nEm không tự tin lắm vào vị giác của mình.」"
1114 = "「Không, tôi đâu có nói đến mức đó.」"
1117 = "「Suzu, tôi rất thích em.\\n——Tôi yêu em.」"
1118 = "「Em——đang rất hạnh phúc.」"
1119 = "「Việc được ngài uống nước tiểu, lại là một điều……\\nmãnh liệt……tuyệt vời đến nhường này, từ trước đến nay, em chưa từng mơ tới.」"
1120 = "「Vì em muốn ngài được ăn lúc vừa mới nấu xong,\\nnên mọi thứ đã chuẩn bị xong xuôi, chỉ chờ ninh cho ngấm gia vị nữa thôi ạ.」"
1122 = "「Em, rõ ràng là toa xe dẫn đầu——đáng lẽ phải làm tấm gương cho mọi người——\\nthế mà, chỉ bị ngón tay chà xát cô bé thôi đã.」"
1124 = "「Vì thế——hãy cho tôi nhìn kỹ hơn đi.」"
1127 = "「Vì vậy……chuyện đó……nếu ngài không phiền,\\nxin ngài Soutetsu, hãy……」"
1128 = "「Vì vậy, lần tới——\\nnhất định hãy cho em uống nước tiểu của ngài Soutetsu nhé.」"
1131 = "「Lúc mọi người ngã bệnh tôi đã lo không biết sẽ ra sao,\\nnhưng vượt qua rồi mới thấy, đúng là trong cái rủi có cái may.」"
1133 = "「V-Vâng, đúng vậy ạ——ưm——em——tại vì,\\ndạo này cứ bận rộn suốt——dương, vật của ngài Soutetsu——」"
1134 = "「V-Vâng! Sâu bên trong! Vào tận sâu nhất——ưm!\\nHãy đâm thật mạnh, vào đi ạ!」"
1136 = "「Đúng là vậy đó ạ.」"
1138 = "「Đúng vậy nhỉ. Chẳng lẫn chút tạp chất nào.\\nTôi nghĩ đây là thứ nước hảo hạng đấy.」"
1139 = "「Ừ, ướt sũng rồi. Có vẻ như em đã hoàn toàn sẵn sàng.」"
1142 = "「Đúng vậy. Thế nên, tôi cũng trở nên thế này rồi.」"
1144 = "「Ừ, nhờ thế mà tôi mới được thưởng thức đồ ăn Suzu tự nấu.\\nĐây chính là cái may không thể chối cãi.」"
1145 = "「Đúng, vậy nhỉ. Suzu——」"
1147 = "「Vâng ạ!」"
1149 = "「Vâng, thưa ngài Soutetsu.」"
1154 = "「Không có gì là không được cả.\\nTôi cũng muốn nhìn thấy dáng vẻ lúc Suzu lên đỉnh.」"
1155 = "「Tất nhiên rồi. Hãy để tôi trực tiếp thưởng thức nhé.」"
1166 = "「Tất nhiên là em đã chuẩn bị sẵn rồi ạ.\\nKhông thể để cả ngài Soutetsu cũng đổ bệnh được.」"
1167 = "「Có vẻ đã hạ sốt hẳn rồi.\\nCảm giác thèm ăn cũng đã hoàn toàn hồi phục.」"
1175 = "「Suzu ăn diện cũng rất đáng yêu, nhưng điều tôi thích nhất,\\nlà một Suzu cứ như vậy, hiện diện trong cuộc sống thường ngày của tôi.」"
1177 = "「Em cũng đã được chị Mayami\\ndạy cho những công thức nấu ăn khác ngoài cháo rồi đấy ạ?」"
1178 = "「Bụng em……cô bé——đầy ắp rồi……phù, a,\\ncô bé——sắp chết đuối, trong tinh dịch——phù, a——mất thôi.」"
1181 = "「Hự!」"
1182 = "「Ra đây! Ra đây! Suzu!!!」"
1185 = "「Mãi mãi về sau.」"
1187 = "「Cảm ơn em.」"
1191 = "「Mùi này……ra vậy, là thịt hầm khoai tây à.\\nNói mới nhớ, cũng một thời gian rồi tôi chưa ăn món này.」"
1192 = "「Thì ra là vậy. Làm tình với tạp dề khỏa thân,\\ncũng là nghĩa vụ của người vợ——là công việc bếp núc vô cùng quan trọng nhỉ.」"
1199 = "「Dạ……em——\\ncảm giác, vẫn còn đọng lại……một chút xíu nữa ạ.」"
1200 = "「Hãy cùng thử nhiều thứ nhé.\\nLần tới, lần tới nữa, và cả những lần sau nữa.」"
1202 = "「Vậy thì giá như tôi được nếm thử nhỉ.\\nBữa ăn do chính tay Suzu nấu cơ mà.」"
1204 = "「Suzu——lại——lên đỉnh, nữa đây——\\nưm——toàn bộ——của tôi——sẽ bắn vào trong, Suzu.」"
1205 = "「Suzu——lần này, hãy cùng lên đỉnh với tôi nhé.」"
1206 = "「Suzu……」"
1207 = "「Suzu.」"
1208 = "「Suzu thì, mềm mại hơn mọi khi đấy.」"
1209 = "「Suzu! Suzu! Suzu! Suzu!!」"
1210 = "「Suzu, cho tôi xin chút nước muối để phòng hờ được không?」"
1211 = "「Suzu?」"
1220 = "「Nói là nước tiểu, nhưng cái này là nước tinh khiết mà.」"
1221 = "「Ng-Ngài Soutetsu?」"
1222 = "「Ngài Soutetsu……đã uống hết……không chừa lại, một giọt nào——\\nA……a——phù a a a a a ưm ưm!!?」"
1223 = "「Ngài Soutetsu……a——ưm——chụt——chụm——」"
1224 = "「Ngài Soutetsu……ưm……chụt」"
1225 = "「Ngài Soutetsu.」"
1227 = "「Lên đỉnh——nhiều quá——ưm——á——\\nmạch điện——của em——cháy——cháy mất thôi.」"
1228 = "「!」"
1229 = "「!?」"
1328 = "Đừng nói là một khe hở dù chỉ một milimet,\\ntôi còn đang ấn sâu hết mức có thể——"
1336 = "Cơ mà——\\nỦa? Đây là……"
1347 = "Nhưng ngay lập tức, lưỡi và lưỡi. Nước bọt và nước bọt bắt đầu hòa quyện."
1349 = "Nhưng chúng tôi vẫn đang mặc quần áo,\\nkhông thể áp sát những mảng da thịt trơn tuột vào nhau được."
1351 = "Nhưng, thứ tôi cần uống lúc này, không phải là nó."
1358 = "Tuy là màu trắng tinh khôi rất hợp với Suzu,\\nnhưng lại là kiểu đồ lót buộc dây hai bên khá gợi cảm."
1375 = "Và thế là tôi——không, chúng tôi.\\nTrong suốt khoảng thời gian bận rộn này, vẫn chưa làm tình lần nào."
1376 = "Chỉ cần gõ nhẹ bằng đầu lưỡi,\\ncô bé của Suzu liền giật giật liên hồi."
1384 = "Chỉ đơn thuần là đôi môi chạm nhau,\\ndùng đôi tay của mình, ôm trọn lấy cơ thể đối phương."
1386 = "Bị ôm bất ngờ không báo trước, Suzu thốt lên kinh ngạc——\\nnhưng rồi em thở phào, hạnh phúc ngả người vào vòng tay tôi."
1388 = "Cặp mông tròn trịa, cô bé nóng hổi mềm nhũn,\\nđang chu ra một cách đáng yêu."
1392 = "Nhờ Paulette đã quay trở lại làm việc từ hôm nay,\\nnên tôi và Suzu mới có thêm chút thời gian rảnh rỗi."
1393 = "Những nếp thịt mềm như nhung run rẩy bám chặt lấy,\\ntôi dùng quy đầu lật chúng lên rồi lại khoét sâu vào trong."
1395 = "Là tè dầm.\\nSuzu vừa lên đỉnh vừa tè dầm."
1398 = "Giọng nói như thể đang rất bối rối.\\nRồi Suzu cứ thế cúi nhìn xuống cơ thể mình."
1399 = "Chắc là em đang ngại ngùng.\\nSuzu khẽ đung đưa cơ thể."
1401 = "Gần như sắp khóc nấc lên,\\nSuzu lại một lần nữa run rẩy dữ dội——!"
1404 = "Đôi má ửng hồng hạnh phúc, em hắng giọng một cái nhẹ.\\nRồi Suzu ngoan ngoãn đổi cách gọi."
1405 = "Cặp mông khẽ đung đưa nũng nịu một cách đáng yêu.\\nRa là vậy, tôi hiểu rồi."
1408 = "Hút lấy vệt nước bọt sắp rỉ ra từ khóe miệng,\\nđúng lúc đó, Suzu giật mình, khuôn mặt lộ vẻ nhận ra điều gì đó."
1410 = "Vẫn là câu trả lời như mọi khi,\\nnhưng lại ngập tràn sắc dục nồng đậm, như thể lần đầu tiên tôi được nghe."
1412 = "Chỉ cần bị em nhìn chằm chằm, tình yêu thương trong tôi lại trào dâng.\\nTôi khẽ vuốt ve mái tóc đen của em, để những ngón tay vương vấn rồi lại gỡ ra."
1414 = "Khóe mắt đong đầy nước,\\nem lắc đầu nguầy nguậy như một đứa trẻ."
1415 = "Rõ ràng em bảo là chỉ còn một chút xíu nữa thôi,\\nnhưng một lượng lớn nước tiểu thải lại đang trút thẳng vào miệng tôi."
1416 = "Giọng nói thốt ra những lời đàng hoàng, nhưng lại cao vút lên vì phát tình.\\nĐến mức đó sao, Suzu đang hưng phấn đến thế——!!?"
1420 = "Chỉ với một kích thích vô cùng đơn giản đó,\\nSuzu đã thốt ra giọng nói như tan chảy."
1424 = "Tuy đã xuất tinh, nhưng cậu bé vẫn chưa hề xìu xuống.\\nDù bây giờ vẫn đang tiếp tục xuất tinh, tôi cũng chẳng hề có ý định dừng hông lại."
1430 = "Mặc dù chảy ra từ lỗ niệu đạo,\\nnhưng nó lại có màu trong suốt và không hề có mùi."
1439 = "Tôi và Suzu, Nagi, Reina đã phải mượn sức của những người xung quanh,\\nxoay xở đủ đường mới vượt qua được, nhưng mà——"
1441 = "Tôi muốn làm em bình tĩnh lại, chỉ muốn làm vậy thôi.\\nVùi mũi vào mái tóc đen dài của em, tôi thì thầm."
1444 = "Tôi cố tình không đưa ngón tay vào âm đạo.\\nĐể ngón tay thấm đẫm mật ngọt, rồi chầm chậm, chầm chậm di chuyển."
1448 = "Với sức mạnh và độ sâu chưa từng có từ trước đến nay,\\ntôi đang gõ cửa lối vào tử cung của Suzu."
1451 = "Chúng tôi trao nhau nụ hôn."
1452 = "Một nụ hôn.\\nChỉ đơn thuần là nhấm nháp đôi môi."
1454 = "Toàn bộ da thịt đang tuôn mồ hôi đầm đìa,\\ntuyệt vọng cố gắng làm mát cơ thể dù chỉ một chút."
1455 = "Thế nên, tôi và Suzu, sẽ mãi mãi,\\nlặp lại những chuỗi ngày như thế này."
1457 = "Bắn chất lỏng và hơi nóng của tôi vào nơi sâu nhất của Suzu,\\nvừa để nó ngấm vào, vừa khắc sâu dấu ấn của mình."
1461 = "Vắt kiệt toàn bộ tinh dịch, dốc cạn mọi sức lực,\\ntôi gục xuống tấm lưng nhỏ bé của Suzu, trong khi hai đứa vẫn đang dính liền lấy nhau."
1462 = "Tôi dùng ngón giữa giữ cho cô bé của Suzu mở rộng,\\nrồi bắt đầu tấn công dồn dập từ âm vật xuống đến cửa mình."
1464 = "Tôi tung vạt váy lên thật cao từ tận dưới cùng."
1465 = "Tôi thậm chí còn có cảm giác tinh hoàn đang phồng to lên gấp chục lần."
1468 = "Không phải chạm vào da thịt, mà là từ từ, chầm chậm vuốt ve\\nbộ đồng phục thường ngày của Suzu ngay bên dưới lớp tạp dề."
1470 = "Không để em gục ngã.\\nTôi ôm chặt lấy eo em!"
1472 = "Vừa lôi cậu bé đang cương cứng ra khỏi quần——\\nngay khoảnh khắc đó, tôi đã đút vào rồi!"
1474 = "Đâm chọc, khoét sâu vào âm đạo đang run rẩy liên hồi của Suzu,\\ntôi thỏa sức tận hưởng em theo ý muốn của mình."
1475 = "Hiểu được ý muốn của Suzu, tôi cố gắng chống đỡ cơ thể——\\nSuzu xoay người đổi tư thế, đối mặt với tôi."
1478 = "Chẳng hiểu sao tôi lại cảm thấy bị choáng ngợp,\\nđồng thời——thực sự cảm thấy ghen tị."
1480 = "Tôi dùng ngón tay quệt đầy thứ mật ngọt đó,\\nvuốt dọc qua lỗ niệu đạo, rồi kéo dài lên tận âm vật."
1482 = "Súc miệng bằng nước muối xong và quay lại bếp,\\ntôi thấy Suzu đã nhanh nhẹn rửa xong đống bát đĩa vừa dọn xuống."
1484 = "Tôi ép đũng quần mình vào hạ bộ của em."
1486 = "Tất cả tâm trí tôi, đều hóa thành dòng tinh dịch đậm đặc,\\ntuôn chảy vào trong Suzu, khao khát được hòa làm một với em!"
1487 = "Tôi luồn tay qua khe hở của chiếc tạp dề."
1489 = "Tôi ôm chặt lấy eo em,\\nvà dốc toàn lực đẩy hông về phía trước."
1490 = "Nói mới để ý, từ chiếc nồi trên bếp,\\ncó một mùi hương thơm lừng, giống mùi nước tương đang thoang thoảng bay tới."
1491 = "Tôi khẽ đặt môi lên khóe mắt,\\nhứng lấy và nhấm nháp những giọt nước mắt của Suzu."
1493 = "Vừa cởi dây buộc, chiếc quần lót không rơi xuống ngay——\\nmà dính chặt vào đũng quần một thoáng, rồi mới rơi xuống."
1494 = "Chỗ nhạy cảm của Suzu, tôi vẫn luôn nhớ."
1498 = "Từ bên trên lớp bao quy đầu nhỏ nhắn đáng yêu,\\ntôi nhẹ nhàng chà xát âm vật của em."
1500 = "Thế nên, tôi chỉ tập trung vào một điểm duy nhất,\\nnơi bộ phận sinh dục của cả hai đang kết nối với nhau."
1508 = "Đống bát đĩa dọn xuống,\\ncả hai phần đều trống trơn một cách hoàn hảo khiến tôi cũng phải vui lây."
1510 = "Và rồi, để thề hẹn với nhau, chúng tôi thêm một lần nữa."
1512 = "Nếu đó là mong muốn của Suzu,\\nthì đương nhiên, tôi chẳng có lý do gì để từ chối cả."
1515 = "Đáng lẽ chỉ là nước lọc thôi,\\nnhưng càng uống, tận sâu trong cơ thể tôi càng nóng rực lên như thiêu như đốt."
1522 = "Sau khi dịu dàng mơn trớn âm vật,\\ntôi cử động ngón tay, ấn chiếc quần lót lún sâu vào rãnh dọc."
1523 = "Những giọt chất lỏng âm ấm liên tục tuôn ra từ lỗ niệu đạo của Suzu."
1524 = "Chiếc váy màu đen đỏ lấp ló dưới lớp tạp dề nấu ăn,\\ncàng làm tôn lên đôi chân, làn da trắng nõn và đầu gối tròn trịa của Suzu."
1526 = "Trong công việc, trong cuộc sống, và cả trong chuyện chăn gối. Em luôn nghiêm túc, hết mình,\\nham học hỏi hơn bất cứ ai, là người vợ vô cùng, vô cùng đáng yêu của tôi."
1528 = "Nhưng, tôi không đợi nữa.\\nĐúng hơn là, không thể đợi được nữa."
1538 = "Nếu vậy thì, Suzu cũng——\\nchắc hẳn đã rất mong chờ đêm nay."
1541 = "Hơi nóng bốc lên ngùn ngụt.\\nMật ngọt từ cô bé đã chảy róc rách vào trong khoang miệng tôi."
1545 = "Chị Mayami, Hibiki, Paulette, Fukami, Kisaki,\\nđều lần lượt phát sốt và nằm bẹp giường vì cúm."
1554 = "Một giọng nói đầy vẻ vui sướng.\\nĐể không phụ lòng mong mỏi của Suzu——"
1555 = "Cậu bé cương cứng đang giật nảy lên vì bứt rứt,\\nliên tục thúc giục tôi nhanh lên, nhanh lên nữa."
1565 = "Hông tôi tham lam ra vào."
1585 = "Nói đúng hơn thì, chắc chắn là vậy.\\nDựa trên cấu tạo cơ thể của Suzu——"
1589 = "Có lẽ em đã bị thuyết phục.\\nSuzu im lặng, gật đầu thật sâu."
1590 = "Bị dội trực tiếp vào miệng thế này,\\nthay vì nói là âm ấm, thì đúng hơn là nóng hổi."
1592 = "Mềm mại, trắng trẻo và nhỏ nhắn——\\nnhưng lại vô cùng mạnh mẽ, đôi bàn tay ấy đang nâng đỡ lấy tôi."
1593 = "Bác sĩ cũng đã đảm bảo rằng\\ntrong hai ba ngày tới mọi người sẽ bình phục——"
1595 = "Bàn tay Suzu dịu dàng, nhẹ nhàng vuốt ve vùng bụng dưới của tôi."
1596 = "Suzu lộ vẻ bối rối.\\nCơ thể cũng trở nên cứng đờ."
1597 = "Mông của Suzu cũng nhầy nhụa rồi.\\nBên dưới lớp tạp dề nấu ăn có lẽ cũng đã ướt nhẹp hết cả."
1598 = "Suzu uốn cong lưng như một cây cung,\\nrồi rũ rượi——"
1599 = "Như muốn biến lời nói thành hình hài,\\nđôi mắt Suzu cong lên thành một vòng cung vô cùng dịu dàng."
1600 = "Suzu nảy lên từng hồi, cơ thể lắc lư dữ dội,\\ncô bé siết chặt lấy tôi một cách mãnh liệt!"
1601 = "Hai tay Suzu áp vào má tôi."
1602 = "Nghe tôi nói vậy, Suzu khẽ cười ufufu."
1603 = "Suzu cứ thế để lộ hoàn toàn cặp mông,\\ngập người tựa vào bồn rửa chén."
1604 = "Suzu rùng mình, run rẩy dữ dội."
1618 = "Cửa âm đạo run rẩy như đang nũng nịu,\\nkhông ngừng bôi mật ngọt lên đầu ngón tay tôi."
1619 = "Cửa âm đạo giật giật một cách dâm đãng và đáng yêu,\\nnhững giọt mật đặc sệt đang rỉ ra từ đó."
1621 = "Một tư thế mời gọi tôi lộ liễu đến mức không thể rõ ràng hơn,\\nnhưng thứ em đang đòi hỏi, không phải là đút vào."
1622 = "Khoảng giữa hai mắt, phía trên sống mũi,\\nphía sau chỗ đó cứ nhấp nháy chớp giật liên hồi."
1624 = "Tôi đã lỡ ấn phải công tắc gì, ở đâu vậy chứ."
1625 = "Hậu môn đang run rẩy một cách cô đơn,\\nnhưng giờ tôi chẳng thể chạm nổi một ngón tay vào đó."
1627 = "Và rồi, với những ngón tay đã ướt sũng nhầy nhụa——"
1678 = "（Là chuyện đó sao!）"
1680 = "（Phập!!!!）"
1681 = "（Phập! Phập! Bạch! Bạch!!）"
1682 = "（Phập! Phập! Phập! Bạch!）"
1684 = "（Tuột!）"
1685 = "（Nhẹ nhàng）"
1686 = "（Thịch）"
1687 = "（Nhóp nhép——ấn——miết——cọ xát!）"
1688 = "（Cọ xát）"
1690 = "（Cọ xát, nhóp nhép——ấn, miết）"
1691 = "（Nhóp nhép）"
1693 = "（Thúc）"
1694 = "（Miết mạnh!!）"
1695 = "（Ưm）"
1697 = "（Róc rách——róc——róc rách!）"
1698 = "（Ồ）"
1699 = "（Bạch!!!）"
1701 = "（Phập! Phập! Chụt! Phập!!）"
1702 = "（Róc rách）"
1704 = "（Chụt）"
1706 = "（Chụt——róc rách!）"
1708 = "（Thít! Siết chặt!!）"
1709 = "（Chụt! Chụt! Miết! Cọ xát）"
1710 = "（Chụt）"
1712 = "（Phụt! Phập! Phụt! Phập!）"
1713 = "（Ưm）"
1715 = "（Phịch）"
1717 = "（Phụt——phụt——）"
1720 = "（Phụt, phụt——phụt——）"
1721 = "（Phụt! Phụt! Phụt! Phụt!）"
1723 = "（Phụt! Phụt! Phụt! Phụt!）"
1725 = "（Phụt! Phụt! Phụt! Phụt!）"
1726 = "（Chộp lấy!）"
1729 = "（Ôm）"
1730 = "（Rút ra!）"
1731 = "（Tuột）"
1732 = "（Cọ xát）"
1733 = "（Miết——cọ xát——vuốt——trượt——）"
1734 = "（Xoa——miết——nhấn——chụt）"
1735 = "（Vuốt ve——vuốt ve——cọ xát——miết）"
1736 = "（Vuốt ve——）"
1737 = "（Vuốt ve）"
1738 = "（Mở rộng）"
1740 = "（Vuốt ve——chạm nhẹ——nắn——xoa——）"
1741 = "（Vuốt ve）"
1742 = "（Gõ nhẹ, gõ nhẹ）"
1743 = "（Liếm——mút——mút——ực）"
1745 = "（Liếm nhẹ）"
1747 = "（Chỉ vì bị uống nước tiểu……\\nmà em ấy đã lên đỉnh sao?）"

[selections]
