# 凪h1_ふたりっきりのデート.txt

[info]

[characters]
1349 = "Nagi"
1441 = "Soutetsu H"

[character_subs]
1708 = "Soutetsu"

[script]
844 = "\"——Cái cây mà Nagi đốn ngã trong lúc tu hành,\\ngốc cây cũng đã bị dọn đi rồi.\""
846 = "——Nagi tự mình dùng ngón tay mở rộng\\nâm đạo đang ướt đẫm đến mức kéo sợi ra."
848 = "\"——Em ấy tựa lưng vào thân một cái cây non,\\nnhìn tôi bằng đôi mắt ươn ướt, ánh nhìn đầy nũng nịu.\""
850 = "「——っ」"
855 = "「……Chìm sâu hơn nữa nhé?」"
857 = "\"「...Sự cố đó đã làm thay đổi rất, rất nhiều thứ,\\nrất nhiều chuyện.」\""
1006 = "「Âm đạo cảm nhận được, cái gì cơ?」"
1008 = "「Không đâu. Vừa nãy——\\nNếu làm thêm lần nữa, tôi sẽ lại bị ép xuất tinh mất」"
1014 = "\"「Nhưng mà, có một chuyện em hiểu nè. Học hỏi từ chuyến dã ngoại,\\ncó một chuyện——em cũng đã hiểu ra rồi á.」\""
1018 = "「Nagi cũng vậy, sao」"
1020 = "\"「Em đã hiểu ra chuyện gì?」\""
1021 = "「Một bộ ngực thật dễ thương」"
1023 = "「Dương vật của anh hai, không dễ thương chút nào——\\nTrông rất, mạnh mẽ……hung ác lắm á」"
1025 = "「Nè? Nè? Sao vậy á, anh hai」"
1030 = "「Nagi——Nagi! Nagi!」"
1032 = "「Nagi……được chứ?」"
1033 = "「Nagi——Cởi quần ra nhé」"
1036 = "「Nagi——Em có thể dùng sức kẹp hai chân lại được không?」"
1037 = "「Nagi」"
1040 = "\"「Đi chơi thôi! Đi chơi thôi!\\nĐi hẹn hò riêng với anh hai thôi nè!」\""
1043 = "「Vừa nãy, em đã sướng một mình mất rồi」"
1044 = "「Lên đỉnh đi. Nagi.\\nHãy cho tôi thấy dáng vẻ đáng yêu nhất của em, chỉ mình tôi thôi」"
1046 = "「A——Hể——Kỳ——Kỳ lắm, á——\\nƯm——Xung quanh——lỗ——mông, á——cọ cọ」"
1048 = "「Hya——A——A——A——」"
1050 = "「Hya——A——Cọ xát——rồi——Ưm——\\nA——Dương, vật——của anh hai——thế này」"
1051 = "「Hya——A——Mồ hôi, á——Trơn tuột……rồi, nè」"
1053 = "「Hya——A——Cái này——Cái này——Ưm——\\nMông——Ấm quá——Sướng——quá」"
1054 = "「Hức——Ư——Phù——Ưm」"
1055 = "「Hya!!」"
1056 = "「Hya!!!」"
1057 = "「Hya!」"
1059 = "「Nyau! Ưm——Lưỡi, ngoáy vòng vòng——A,\\nvách——âm đạo——bị, liếm, á」"
1060 = "「Hyauuuuuuuuuuuuuuuuuuuuuu!!?」"
1061 = "「Nhya!?」"
1062 = "「Hya!? Lại, mông nữa á!?」"
1063 = "「Nhi!? Phù——Hà——Bên trong, âm đạo——\\nƯm——Lưỡi, của anh hai, á, trơn tuột」"
1065 = "「Hya!? Hể——Ua——A——Bên trong——\\nBụng——Bụng——của anh hai——nóng, quá」"
1067 = "「Ư——A」"
1068 = "「Ư」"
1069 = "「っ!」"
1071 = "「Phù——Hà——Ahaha!\\nAnh hai, xin lỗi á! ——（Chụt!）」"
1072 = "「Phù——Ưm——Sau, đó——Giật, giật——\\nSự run rẩy——nhịp đập, của anh hai——cũng, cảm nhận được, á」"
1075 = "\"「Mấy chuyện phức tạp em không hiểu đâu á.」\""
1076 = "「Lúc đó em đã nghĩ, mình làm sai rồi, thất bại rồi!\\nCảm giác đó khiến ngực em đau nhói. Nhưng mà」"
1078 = "「Phù——A——A——Hạnh phúc——Ưm——\\nHạnh phúc quá——Hạnh, phúc quá——Sướng, quá」"
1079 = "「Phù——A——Đang bị, hôn, á——\\nƯm——Anh hai, đang hôn chụt chụt, vào âm đạo」"
1080 = "「Aaa」"
1081 = "「Hya!」"
1082 = "「Hya!!」"
1083 = "「っ!?」"
1084 = "「Phù, a! A! ~~——Ưnnn!!!」"
1086 = "「Hể——A——Âm, đạo——Ưm——á——\\nChạm vào——cọ xát——rồi——Nóng——quá——Ưm」"
1087 = "「Hể——A——Phụt——Phụt, á——\\ncủa anh hai——đang đập vào bụng——Phù——Phù a」"
1089 = "「Ối chà!」"
1090 = "「Hể!?」"
1091 = "「Hể? ——A! A, em hiểu rồi á」"
1092 = "「Ưm——」"
1093 = "「Ưm……Phù——A……Sướng……lắm, á」"
1095 = "「Hứ hừm, em và bé Fukami\\nsẽ kéo anh hai chìm nghỉm đến lúc ngạt thở luôn nha」"
1096 = "「Hya!」"
1097 = "「Hừm」"
1099 = "「A……Âm đạo, mát quá」"
1102 = "「A……A——Lúc nãy——á——Ưm——Phù, a,\\nEm, vừa nãy……chỉ vì giọng nói của anh hai……mà lên đỉnh mất rồi, á」"
1103 = "「A——A——Phù——A——」"
1105 = "「Hà——A——A——A! Ưm——Lưỡi,\\nKhông——Móc ngoáy——như thế——Chụt chụt, á!」"
1106 = "「Hà……Ư……Sướng, quá……Ưm——Bàn tay,\\ncủa anh hai……Làm ngực em……Nhũn cả ra……rồi——Phù——A」"
1108 = "「A……Ưm——Hya——Bị, làm——chậm rãi, thì,\\nbụng——âm đạo——cảm nhận được, rõ lắm á——」"
1109 = "「Hà——Vâng——Ưm——Anh hai——Anh hai ơi」"
1110 = "「A……Ư, m」"
1111 = "「A——Anh hai……Anh hai ơi……Ưm——Hà——A,\\nEm——Em——sắp——thế này——thì, sắp」"
1114 = "「A……Đây——là——Ưm——Đây, là——làm tình\\n——Đang……làm tình, với——anh hai——」"
1115 = "「A」"
1116 = "「っ!」"
1117 = "「A, Ưm——Phù——A——Anh hai——Anh, hai ơi」"
1118 = "「Ưm……Chụt——Chụt——Chụt——Chụt——\\nChụt——Ngoáy——Chụt——Chụt——Phù a」"
1120 = "「Rơi vào lưới tình, sao」"
1121 = "「Ưm……Phù——Thích, quá……Ưm——\\nNgón tay……của anh hai……Sướng……quá——」"
1123 = "「Ưm……Hà……A——Nóng, quá……Ưm——\\nNgực——Tê rần——rồi——Nóng quá, á——Ưm」"
1125 = "「Vâng……Được á——Tất cả, cứ làm theo ý anh hai đi」"
1126 = "「Ưm……」"
1127 = "「Hya!」"
1129 = "「Ừ, Nagi. Tôi cũng vậy——」"
1130 = "「Vâng. Được á.\\nĐến đây? Anh hai」"
1132 = "「Ừ, tôi biết」"
1133 = "\"「Hửm.」\""
1135 = "\"「Ehehe, vui quá.\\nAnh hai, vẫn còn nhớ ha~」\""
1136 = "「Uô!?」"
1138 = "\"「Ôn lại kỉ niệm cũng là hẹn hò á.」\""
1143 = "「A, anh hai, đ……đó là……mông——\\nÀ thì——lỗ, mông……á」"
1144 = "「A, anh hai? E, em……không sao, đâu á?\\nAnh hai cứ, làm theo ý mình……chuyển động……đi, á?」"
1146 = "「Anh hai……Anh, hai——Lúc nãy, á——Lại, nữa à?」"
1149 = "「Anh hai cũng vậy, hở?」"
1151 = "\"「Anh hai, vẫn chẳng hiểu\\ntâm lý con gái chút nào á~」\""
1152 = "「Anh hai! Anh hai! Anh hai! Anh hai——!?\\nHả? A——Phù a!?」"
1154 = "「Chắc hẳn, đó là——」"
1156 = "「Tận hưởng đã đời luôn á! Thỏa mãn quá á!\\nHẹn hò chỉ có hai người quả nhiên, hạnh phúc thật á!」"
1158 = "「Vậy thì! Về nhà thôi á!\\nBình an vô sự về đến nhà, tất cả gộp lại mới là hẹn hò trọn vẹn á!」"
1159 = "\"「Là phía trước sao.」\""
1161 = "「Hình dáng——á——Ưm——Chỗ, to——\\ncủa dương, vật——anh hai——chẳng hạn——Ưm」"
1162 = "「Làm tốt lắm」"
1171 = "「Cứ từ từ——chậm rãi——cùng sướng nhé」"
1172 = "「Tôi cũng vậy」"
1174 = "\"「Làm sao mà quên được.\\nQuả thực là một sự kiện vô cùng ấn tượng.」\""
1175 = "「Đúng ý tôi luôn」"
1176 = "「Thế nên nhé? Nagi」"
1178 = "「Xin lỗi nhé. Làm em giật mình à?」"
1180 = "「Ch, chỉ giật mình một chút thôi,\\nkhông có gì——phải xin lỗi đâu á」"
1182 = "「Nè? Nè——Anh, hai」"
1183 = "「Ừ——」"
1184 = "「Ừ」"
1185 = "「Ừ. Đúng vậy.\\nHẹn hò chỉ có hai người quả nhiên, hạnh phúc thật」"
1187 = "「Vậy sao——Thế thì」"
1191 = "「Gì chứ. Sẽ nóng lên ngay thôi」"
1192 = "「Tất cả. Em đã bảo cứ làm theo ý anh hai rồi mà」"
1195 = "「Sụt——Sụt sịt——」"
1198 = "\"「Tại sao lại đi dọc theo đường ray?\\nThiếu gì những nơi thú vị khác để đi chứ.」\""
1200 = "\"「Trong cái rủi có cái may——không,\\nchúng ta đã dốc toàn lực để biến họa thành phúc.」\""
1202 = "\"「Hẹn hò đâu phải chỉ để vui chơi thôi đâu nè?」\""
1205 = "「Cảm ơn, anh hai」"
1211 = "「Th, thế này——được chưa á?」"
1212 = "「Hòa làm một——\\nChính là ý nghĩa của việc làm tình đấy」"
1213 = "「Lần này, phải đàng hoàng. Cùng với anh hai.\\nCả hai cùng nhau sướng á」"
1214 = "\"「Kỷ niệm? Giữa anh và Nagi——!」\""
1215 = "\"「Vậy thì hãy nói cho anh biết đi, Nagi sensei.\\nQuang cảnh này có chỗ nào khiến tâm hồn thiếu nữ vui vẻ——」\""
1218 = "「Nếu vậy, tôi đang chìm dần……như bị nuốt chửng vào đầm lầy không đáy,\\nđến tận bây giờ, vẫn tiếp tục chìm đắm trong lưới tình nhỉ」"
1221 = "\"「Lúc đó——được anh hai cứu,\\ntim em, đã đập thình thịch á.」\""
1222 = "「Lúc đó, em đã——rơi tõm vào lưới tình rồi.\\nLà bé Fukami và anh hai đã giúp em nhận ra điều đó á」"
1223 = "\"「Đúng là hẹn hò, và chỉ có hai đứa thôi nhưng mà...」\""
1297 = "Hôn. Hôn, hôn, hôn."
1299 = "\"Cho đến bây giờ——\\nnghĩ lại thì, những từ ngữ sáo rỗng lại hiện lên trong đầu.\""
1300 = "Khoảnh khắc đó, ánh mắt tôi bị cướp mất."
1303 = "Sự thắt chặt mãnh liệt chẳng kém gì lúc kích thích lỗ mông——\\nnhưng lại mềm mại và tròn trịa hơn rất nhiều."
1307 = "Chẳng mấy chốc, mật ngọt từ bên trong Nagi bắt đầu làm ướt đầu ngón tay tôi.\\nThuận theo lời mời gọi đó, tôi uốn cong ngón tay như chiếc móc rồi thử đưa vào."
1311 = "Không biết là cố ý, hay vô tình,\\nvòng eo đang khẽ đong đưa."
1324 = "Nhưng, từng chút, từng chút một——"
1326 = "Nhưng mà, lớp thịt này——\\nbên trong lớp thịt đã nới lỏng, tan chảy và lầy lội này thì——"
1328 = "Đến rồi! Đến rồi! Đến rồi! Đến rồi!\\nSự thắt chặt âm đạo quá đỗi mãnh liệt như muốn cắn đứt!!"
1345 = "Lời cho phép, cũng chính là lời nài nỉ.\\nChắc hẳn Nagi cũng không thấy đau. Hẳn là khoái cảm quá đỗi mãnh liệt."
1387 = "Nagi cũng hà hà, thở hổn hển,\\nkhuôn mặt trông có vẻ như nhẹ nhõm phần nào."
1388 = "Nagi cũng có cùng cảm xúc với tôi, cũng đang khao khát những nụ hôn.\\nBiết được điều đó khiến tôi vô cùng hạnh phúc, tôi trao cho em hết nụ hôn này đến nụ hôn khác."
1390 = "Nagi, không hề tỏ ra chán ghét chút nào.\\nChỉ là, em đang ngạc nhiên thôi."
1392 = "Giọng nói như bị nghẹn lại ở cổ họng."
1394 = "Tôi mút lấy dòng nước bọt vô tình chảy ra từ khóe miệng em. Rồi nuốt trọn."
1396 = "Nagi dùng lời nói để cho tôi nghe thấy hành động của chính mình."
1398 = "Em hơi nheo mắt lại đầy uể oải như một chú mèo con sắp ngủ.\\nCứ thế, Nagi cọ cọ đầu vào ngực tôi."
1400 = "Giọng nói vút cao, như đang sốt ruột."
1401 = "\"Một nụ cười đầy vẻ trêu chọc và tự tin.\""
1403 = "\"Cắt ngang lời tôi,\\nbiểu cảm của Nagi từ từ thay đổi.\""
1406 = "Nagi nắm lấy tay tôi, rồi dẫn dắt nó đặt lên ngực em."
1407 = "Những ngón tay Nagi vẫn đang nắm chặt lấy tay tôi dần dùng lực.\\nKhi bị ấn vào thêm lần nữa, tôi lập tức nhận ra."
1408 = "Nagi khẽ lắc lư cơ thể gỡ tay tôi ra.\\nRồi, em rướn người về phía trước——"
1411 = "Nagi ngã khuỵu xuống, và tôi cũng ngã theo——\\nKhứu giác là thứ đầu tiên cho tôi biết điều đó."
1414 = "Âm đạo của Nagi tuy ẩm ướt, nhưng không có cảm giác là dịch nhờn.\\nVậy thì, chắc đây chỉ là mồ hôi thôi."
1417 = "Đầu ngón tay Nagi vươn tới phần đang cương cứng của tôi."
1418 = "Giọng nói ngọt ngào."
1420 = "Ở rốn Nagi, mặt trong quần, ranh giới giữa da thịt và quần lót,\\nmồ hôi túa ra, đọng lại thành từng giọt."
1422 = "Âm đạo Nagi——lỗ âm đạo, hệt như một con thú với đôi môi không răng,\\nđang cố gắng hết sức, ngoạm khá mạnh vào đầu ngón tay tôi."
1423 = "Nhiệt độ cơ thể vốn đã cao của Nagi,\\nnay lại càng thêm nóng hổi."
1425 = "Bị nhìn chằm chằm.\\nHai chúng tôi nhìn nhau chằm chằm."
1427 = "\"Cười nhẹ, Nagi xoay người một vòng——\""
1428 = "Không biết có phải hiểu lầm đầu lưỡi nhọn hoắt cứng đơ là dương vật hay không,\\nthịt âm đạo Nagi thắt chặt lại, chực vắt kiệt tinh dịch."
1430 = "Núm vú của Nagi, núm vú nhỏ nhắn đang cứng lại."
1436 = "Khoảnh khắc chạm vào âm đạo, màng nhĩ tôi rung lên\\nbởi giọng nói như tê dại, như đang mỏi mòn chờ đợi."
1444 = "Đáng yêu. Rất, rất đáng yêu.\\nRun rẩy nho nhỏ, tựa như nụ hoa bé xíu xa lạ nào đó."
1447 = "Vừa làm vậy, tôi vừa chậm rãi, chậm rãi đẩy hông tới."
1453 = "Cứ thế bị thu hút, khi tôi ghé mặt sát lại gần,\\nNagi lặng lẽ rụt tay về."
1460 = "Khoái cảm tuyệt vời, như thể não bộ và xương sống bị bôi trắng xóa trong chốc lát."
1463 = "Miệng Nagi run rẩy há ra ngậm vào——\\nRồi toàn thân em run lên bần bật, căng cứng duỗi thẳng người."
1466 = "Không chút ngần ngại, em vuốt ve sự cương cứng đó.\\nRồi Nagi ngước mắt lên nhìn tôi."
1468 = "\"Trông có vẻ thẹn thùng, ngượng ngùng...\\nThực sự là một nụ cười dịu dàng rất ra dáng thiếu nữ.\""
1469 = "Vì muốn tôi đâm vào tử cung,\\nvòng eo thon nhỏ kia, lại bắt đầu đong đưa."
1471 = "Đôi đầu gối gầy guộc run lẩy bẩy,\\ntưởng chừng như có thể sụp xuống bất cứ lúc nào."
1473 = "Giọng nói run rẩy, không phải vì sợ hãi, mà là vì mong đợi."
1474 = "Em cất giọng đầy vẻ có lỗi——"
1476 = "Chuyển động của hông càng lúc càng mạnh mẽ hơn,\\ndù có dừng lại thì sự cựa quậy bên trong âm đạo chật hẹp vẫn tiếp tục mang đến khoái cảm mãnh liệt."
1480 = "Nhỏ bé. Chật hẹp. Vô cùng nóng."
1482 = "Cảm giác rùng mình. Cổ họng giật giật, tôi bất giác nuốt nước bọt."
1483 = "Một chút nữa thôi,\\nchỉ cần thêm một chút điểm nhấn nữa thôi thì——"
1493 = "Miệng tử cung cũng đóng mở liên hồi, như đang khao khát tôi."
1494 = "Trước sự phối hợp nhịp nhàng giữa tử cung và âm đạo, run rẩy và hút chặt lấy tinh dịch,\\ntôi cũng không hề chống cự, chỉ đơn giản giải phóng khoái cảm của mình."
1506 = "Khi tôi cảm thấy rùng mình——dương vật đã,\\nngoạm chặt lấy nơi sâu nhất của Nagi, từng đợt tinh dịch ồng ộc tuôn ra."
1510 = "Chắc là do khoái cảm và sự nóng bức lẫn lộn.\\nĐôi mắt Nagi đang lờ đờ bỗng lấy lại ánh sáng khi hiểu ra."
1520 = "Cảm giác như có một khối gì đó, vừa bay vọt ra ngoài.\\nNagi cong người lại, và trong khoảnh khắc, tôi lại bị siết chặt lấy——"
1521 = "Mà, nói đúng hơn, đây là——"
1525 = "Chậm rãi đến mức chính bản thân tôi cũng nôn nóng như muốn cháy rụi——\\nVới tốc độ chậm đến nỗi có thể bị con sâu đo bò qua mặt."
1527 = "Tôi dùng đầu ngón tay lau đi,\\nrồi lột chiếc quần lót cùng với mồ hôi dính nhớp nháp ra."
1528 = "Mặc kệ dương vật vẫn còn run rẩy sau khi xuất tinh,\\ntôi rút hông về sát mép cửa âm đạo."
1530 = "Tôi chẳng hề có một thời khắc nào\\nđể có thể nhận ra được khoảnh khắc đó."
1532 = "Tôi cũng cảm nhận được rất rõ ràng.\\nSự run rẩy, nhịp đập, mồ hôi của Nagi. Mùi hương, làn da, nhiệt độ cơ thể."
1535 = "Ép chặt da thịt vào nhau hết mức có thể, hòa quyện mồ hôi,\\ntôi dùng những chuyển động nhịp nhàng để dẫn dắt đến khoảnh khắc ấy."
1536 = "Da thịt của cả hai đều đang run rẩy.\\nĐã dâng trào đến tột đỉnh."
1537 = "Cẩn thận để không làm em đau,\\ntôi dùng phần thịt mềm của ngón tay, vuốt ve nới lỏng khe rãnh đơn thuần ấy."
1539 = "Khi tôi bất ngờ xoay mạnh hông, cơ thể Nagi run lên bần bật."
1541 = "Dùng lòng bàn tay vớt mồ hôi từ ngực, bụng, hông gom lại,\\nrồi xoa bóp vuốt ngược về trung tâm——hướng về phía núm vú."
1543 = "Tôi và Nagi đã hoàn toàn thỏa mãn lẫn nhau——\\nDù vậy, tôi vẫn cảm thấy một khoảng trống mang hình dáng của một cô gái, một khoảng trống dành cho một người."
1545 = "Học theo Nagi, tôi cũng xoa mồ hôi lên người em."
1548 = "Khi tôi xắn chiếc áo sơ mi dính đầy mồ hôi lên như thể lột nó ra,\\nNagi cũng lôi phần đang cương cứng của tôi ra khỏi quần."
1549 = "Vào khe hẹp do ba bộ phận tạo ra,\\ntôi mạnh mẽ, một hơi nhét phần cương cứng đang bị bỏ không vào!"
1552 = "Dù rất muốn cứ thế mà cắm vào,\\nnhưng tôi đã kìm nén lại."
1555 = "Tôi thấy vui sướng, nhưng đồng thời cũng cảm thấy có lỗi."
1557 = "Khi tôi rụt rè chạm vào thử,\\nnhận lại là tiếng kêu lớn pha lẫn giữa ngạc nhiên và khoái cảm."
1558 = "Đến giờ tôi mới nhận ra, mắt em to thật đấy.\\nĐen láy, sâu thẳm……một đôi mắt thật tĩnh lặng, tôi nghĩ vậy."
1561 = "Rất muốn hôn, nhưng bây giờ lại không thể."
1563 = "Gần như đồng thời,\\nngón tay của cả hai bắt đầu kích thích núm vú và dương vật đang cương cứng của nhau."
1565 = "Tôi ấn vào đó, rồi khẽ rút ra——\\nChỉ đơn giản lặp đi lặp lại như vậy."
1567 = "Tôi vội vàng đỡ lấy cơ thể Nagi đang mất hết sức lực, chực ngã khuỵu xuống."
1568 = "Không phải là lỗ, mà là thịt."
1569 = "Thay vì thỏa mãn khoái cảm của bản thân, để mang lại khoái cảm cho Nagi,\\ntôi dùng dương vật cương cứng vuốt ve, chà xát, đè ép âm đạo em để âu yếm."
1573 = "Ngón giữa của tôi di chuyển dọc theo đường rãnh,\\ntoàn bộ đều ướt đẫm, thậm chí có thể nhũn cả ra."
1575 = "Tôi dồn sức dập hông, để da thịt chạm nhau ở khoảng cách số không."
1576 = "Tôi xoa nắn bờ mông tròn trịa của Nagi,\\ndùng lòng bàn tay vuốt ve nó."
1578 = "Khi tôi thử dùng lòng bàn tay ấn nhẹ xuống,\\ntừ miệng Nagi bật ra tiếng thở nóng bỏng, ướt át."
1580 = "Tôi dùng đầu ngón tay mở nó ra lại——\\nvà nhẹ nhàng hôn lên âm đạo đang run rẩy đáng yêu ấy."
1581 = "Đứng dậy. Chỉnh đốn trang phục, nắm tay nhau.\\nRồi chúng tôi cùng chung bước, trở về \"nhà\"."
1584 = "Cảm giác chẻ vào đó, sự thắt chặt quá đỗi mãnh liệt đó,\\nnếu có thể nếm trải bên trong lớp thịt mềm mại trơn tuột này thì——"
1585 = "Phản ứng đó khiến tôi thấy thích thú,\\ntôi thử tăng thêm chút lực vào chuyển động của ngón tay."
1588 = "Cứ thế nằm trên bãi cỏ,\\ntôi ôm đầu Nagi vào lòng và vuốt ve âu yếm."
1589 = "Có lẽ vì kích thích ở núm vú quá sướng,\\nNagi gần như mất hết lực ở tay phải."
1591 = "Thế nên, tôi túm lấy eo em."
1600 = "Sau đó, em há miệng ra ngậm vào vài cái,\\nrồi cố gắng nối tiếp giọng nói đã kìm nén."
1601 = "Rồi, một khoái cảm trắng xóa ập đến.\\nHông tôi tự động chuyển động như đang khao khát tham lam, không thể dừng lại được."
1602 = "Rồi, bên tai Nagi,\\ntôi thì thầm một cách dịu dàng và ôn tồn nhất có thể."
1603 = "Thay vào đó, tôi liên tục thúc nhẹ và chụt chụt,\\nnhư thể đang trao vô vàn nụ hôn lên miệng tử cung của em."
1605 = "Nếu đã nói là cứ làm theo ý mình, nếu muốn tham lam tận hưởng hết mình,\\nthì việc chỉ nếm trải lớp thịt âm đạo quá đỗi tuyệt vời này quả là quá xa xỉ."
1607 = "Chắc là do cảm nhận được sự âu yếm ở mông chăng?\\nÂm đạo Nagi đã hoàn toàn nới lỏng và ướt sũng."
1608 = "Phải.\\n\"Cũng\" là hẹn hò."
1609 = "Mùi cỏ mùa hè, và mùi của Nagi."
1619 = "Trơn tuột, nhớp nháp.\\nThế nhưng lại thắt chặt, đơn thuần là rất sướng."
1626 = "Bên trong, bây giờ không thể tiến vào được.\\nNhưng chỉ cần kích thích xung quanh thôi, cũng đã đủ——"
1636 = "Lần đầu tiên, bản thân tôi cũng quá sức chịu đựng,\\nnên đã không thể dồn hết tâm trí để làm Nagi sung sướng."
1639 = "Bị tinh dịch đập vào tử cung, chắc hẳn Nagi cũng đã lên đỉnh rồi."
1643 = "Co rút, mút chặt——Lần lên đỉnh tĩnh lặng mà mạnh mẽ của Nagi."
1647 = "Đáp lại giọng nói như đang nôn nóng đó,\\ntôi thử đẩy nhẹ đầu ngón tay vào sâu bên trong chỗ chật hẹp ấy."
1648 = "\"Nghe em ấy nói vậy, tôi mới chợt nhớ ra.\""
1654 = "\"Nơi hút lấy giọng nói vui tươi của Nagi là những tán cây xanh mướt và đường ray.\\nNgoài ra, phóng tầm mắt ra xa chẳng có gì khác.\""
1655 = "Tôi thật sự rất vui vì đã làm em sướng,\\nnhưng thế này thì, tôi lại có chút trống vắng."
1668 = "Mật ngọt chảy dọc lòng bàn tay xuống cổ tay, với thế muốn làm ướt cả cánh tay tôi."
1670 = "Lớp thịt mềm mại bên trong khe rãnh bám dính lấy,\\nrun rẩy hối thúc tôi mau cắm vào đi, cắm vào đi."
1673 = "Bị ngoạm lại quá mãnh liệt, bản năng tự vệ khiến tôi rụt ngón tay lại."
1687 = "\"Một biểu cảm tinh tế và trưởng thành không giống Nagi chút nào,\\nnhưng kỳ lạ thay, tôi lại cảm thấy 'À, đúng là Nagi rồi'.\""
1688 = "Với màn xuất tinh như một vụ tai nạn thế này,\\nthì không thể nào gọi là 『Làm tình chậm rãi』 được."
1691 = "Nếu vậy, chắc cũng đến lúc rồi——\\nNghĩ vậy, tôi tạm thời rút hết lưỡi ra……"
1693 = "Dưới sự mềm mại khiêm nhường ấy,\\ntôi cảm nhận được nhịp đập nóng bỏng và mạnh mẽ thình thịch, thình thịch."
1694 = "Nếu vậy tôi muốn bắt em nói ra những lời dâm đãng hơn nữa——\\nThứ dục vọng méo mó ấy chợt trỗi dậy mãnh liệt."
1697 = "Nếu vậy, giờ tạm thời không đụng đến lỗ mông, cứ coi như đối tượng để nghiên cứu sau vậy."
1698 = "Nơi có Fukami. Nơi có những ngày tháng của ba chúng tôi.\\nHướng về nơi đó——trở về."
1700 = "Đôi mắt ngấn lệ, đôi gò má đỏ bừng,\\nnhững núm vú nhỏ nhắn cương cứng, đã thành thật cho tôi biết điều đó."
1703 = "Cảm giác thắt chặt đến mức quá khít vẫn không đổi,\\nnhưng thớ thịt đã hoàn toàn trơn tuột, mềm mại và nới lỏng ra."
1704 = "\"Đường ray cũng không còn vướng cành cây nào,\\ntình trạng bảo trì đường ray khác hẳn so với lúc đó.\""
1707 = "Âm đạo, đùi, và đùi."
1709 = "Dịch nhờn hòa quyện cùng mồ hôi tay,\\ntạo nên độ trơn trượt tuyệt diệu, làm tăng thêm khoái cảm từ ma sát của Nagi."
1712 = "Cảm giác quy đầu chẻ vào trong,\\nhoàn toàn khác biệt so với lần đầu tiên."
1714 = "（Nhưng——mà）"
1765 = "（Với cái lỗ chật hẹp này……mà Nagi——\\nđã chấp nhận dương vật cương cứng của tôi sao）"
1766 = "（Ư）"
1767 = "（Phụt! Phụt phụt! Phụt! Phụt!）"
1768 = "（Phập pppppppppppppppppppp!!!）"
1769 = "（Phụt!）"
1770 = "（Ư——Nhóp nhép——Chụt——Trơn tuột——）"
1771 = "（Chụt! Chụt! Chụt! Bụp!）"
1772 = "（Trườn! Liếm! Ngoáy!）"
1773 = "（Thắt tim! Siết chặt!）"
1774 = "（Nhóp nhép!）"
1775 = "（Nhóp nhép）"
1777 = "（A——Không, ra vậy. Đơn giản thôi mà）"
1778 = "（Ư!）"
1779 = "（Phụt!）"
1780 = "（Ư——Phụt）"
1784 = "（Bóp nhẹ——Mềm mềm——Xoa nắn——Cọ xát——）"
1785 = "（Xoa nắn!）"
1786 = "（Bóp nhẹ）"
1787 = "（Xoa xoa——Chạm nhẹ——Nắn nắn——Xoa nắn——）"
1788 = "（Mềm mềm——Xoa nắn）"
1790 = "（Mềm mềm——Cứng cứng——）"
1791 = "（Phập——Phập——Ư——Ư——Ư——）"
1792 = "（Ư——Ư ư——Cộc——Ư——Ngoáy）"
1793 = "（Phập——Phập——Trượt——Tuột——）"
1794 = "（Trượt——tuốtttttt）"
1795 = "（Trượt! Phập! Phập! Bụp!）"
1796 = "（Ư! Ngoáy! Chà! Chà!）"
1797 = "（Trượt tuốtttttttttt!!!）"
1798 = "（Ngoáy!）"
1799 = "（Xoa xoa）"
1800 = "（Bịch!）"
1801 = "（Lảo đảo）"
1802 = "（Tách ra——）"
1803 = "（Có vẻ là nơi có độ nhạy cảm cao nhưng……\\nCũng khá mỏng manh và có vẻ khó chiều đây）"
1805 = "（Xoa xoa）"
1808 = "（Siết chặttttttttttttt!!!）"
1809 = "（Kít kít kít kít!）"
1811 = "（Thế này——thì——）"

[selections]
