# ポーレット12_解放.txt

[info]

[characters]
1225 = "Paulette"
1294 = "Soutetsu"

[character_subs]
1441 = "Paulette"
1515 = "Soutetsu"

[script]
812 = "“Không ai có lỗi cả”\\nKhi sự mất mát quá lớn, người ta không thể nghĩ như vậy được."
815 = "“Tôi sẽ gọi điện, nên mong anh hãy ở lại đây”"
817 = "“Có lẽ là vậy, nếu được như vậy thì tốt quá”, lẩm bẩm như vậy,\\nPaulette mỉm cười với khuôn mặt đã trút bỏ được mọi gánh nặng."
822 = "「――」"
823 = "「――Ừm.」"
827 = "「…………Phù.」"
836 = "「……Một cuộc trò chuyện đàng hoàng――thật sự là bao nhiêu năm rồi nhỉ?\\nKể từ lúc mẹ và ba xảy ra xích mích……mẹ hoàn toàn hoảng loạn.」"
838 = "「……Cũng có thứ tình yêu mang hình hài như vậy sao.」"
841 = "「……Ừm.」"
843 = "「……Paulette.」"
845 = "「……Thật đau lòng anh nhỉ. Những chuyện thế này. Dù có nghe rõ ngọn ngành,\\ndù có hiểu, dù có tha thứ――thì quả nhiên vẫn thấy đau lòng.」"
847 = "「……Được nói chuyện với mẹ――được nghe mẹ nói con rất vui.\\nCó thể không phải là ngay lập tức, nhưng con nghĩ con sẽ gọi lại.」"
951 = "「Không――tôi lại thấy thế là ngắn đấy chứ?」"
953 = "「Không――Tôi thì, chẳng có tha thứ gì cả……\\nChắc chắn, tôi chỉ nghĩ là mình không có tư cách để oán hận thôi.」"
955 = "「Thực ra, cả tôi và Paulette đều “muốn làm như vậy”.\\nVì thế, chắc chắn chúng ta đã nắm bắt cơ hội đó theo cách có lợi cho bản thân.」"
958 = "「Không, có gì đâu――」"
961 = "「Cái đó thì……chắc là, cũng có một chút――khá nhiều?\\nTôi nghĩ là cũng có ở một mức độ nào đó. Nhưng mà, quả nhiên là」"
969 = "「Nhưng――điều đó rốt cuộc cũng có nghĩa là,\\nmẹ đã chọn ba, thay vì chọn tôi.」"
971 = "「Nhưng, rõ ràng là――」"
973 = "「Tôi cũng……được cô dạy cho biết yêu là gì.」"
975 = "「Nghĩ đến những chuyện chất chứa trong lòng ấy.\\nĐã bao nhiêu năm rồi nhỉ? Cuộc trò chuyện giữa hai mẹ con.」"
976 = "「Là tha thứ cho con người.\\nMặc dù vết thương của anh Soutetsu, chắc chắn còn sâu hơn của tôi rất nhiều.」"
984 = "「Chỉ toàn là những bất đồng, cãi vã trở thành chuyện thường ngày.\\nBa và mẹ――đã kiệt sức, và chọn cách ly hôn.」"
990 = "「Vậy là từ trước đến giờ, tôi đã hiểu lầm rồi nhỉ.」"
991 = "「Thì ra là vậy sao.」"
992 = "「Ban đầu chỉ là giúp đỡ vào những lúc rảnh rỗi trong công việc,\\nnhưng ngày qua ngày, chẳng biết bên nào mới là lúc rảnh rỗi nữa.」"
997 = "「Ấm quá. Ngon thật――\\nThì ra cổ họng tôi đã khô khốc rồi.」"
1005 = "「Có thể làm được, là――làm được gì?」"
1007 = "「Vậy mà cái vẻ u ám trên mặt anh Soutetsu lại tan biến đi.\\nLúc đó tôi đã nghĩ――a, thì ra là có thể làm được.」"
1011 = "「Hả?」"
1012 = "「Hả?」"
1013 = "「Hửm?」"
1015 = "「A――ra là vậy.」"
1016 = "「A……Đúng vậy nhỉ.」"
1017 = "「A……」"
1018 = "「A.」"
1019 = "「Vâng……con hiểu rồi.」"
1021 = "「Ừm. Paulette, cô không hề bị vứt bỏ.」"
1022 = "「Ừm.」"
1023 = "「Ừm. Có lẽ vậy.\\nĐó mới chính là việc hợp nhau hay không.」"
1026 = "「Vâng, anh Soutetsu.」"
1030 = "「Bởi vì……con người ai cũng mắc sai lầm.\\nDù không có ác ý――thì con người vẫn sẽ mắc sai lầm.」"
1031 = "「Vì không thể chọn nên tôi đã im lặng. Tôi đã nghĩ nếu mình cố gắng làm một đứa trẻ ngoan,\\nthì ba và mẹ có thể sẽ làm hòa lại với nhau.」"
1032 = "「Nếu không tìm được nơi để trút giận thì……\\nBởi vì, tôi không thể chấp nhận được.」"
1033 = "「Nếu nói là hiểu lầm thì tôi cũng vậy. Tôi――\\nđã nghĩ mình nhận được một lời khuyên chan chứa tình yêu đường sắt cơ đấy.」"
1038 = "「Mẹ cũng……nói với tôi như vậy.」"
1039 = "「Mẹ là người dù chỉ có một mình vẫn có thể cố gắng. Nhưng,\\nba chắc chắn là người không thể sống thiếu mẹ được.」"
1040 = "「Mẹ nói là, dù có phải chia tay, dù có oán hận.\\nNhưng……mẹ vẫn luôn yêu ba.」"
1042 = "「Đúng vậy. Vì được cứu rỗi, nên dù là hiểu lầm,\\nnó vẫn trở thành một kỷ niệm quan trọng và chân thực. A――không.」"
1044 = "「Gọi điện thoại lâu cũng phải có mức độ thôi, anh nhỉ.」"
1049 = "「Tôi cũng bị ép phải lựa chọn. Nhưng, tôi không thể chọn được.\\nLàm sao có thể chọn giữa ba và mẹ được chứ.」"
1050 = "「Ngay từ lần đầu tiên gặp gỡ――\\nchúng ta đã rất, rất hợp nhau rồi nhỉ.」"
1054 = "「Yêu――?」"
1055 = "「Tôi không bênh vực đường sắt. Tôi muốn anh cùng tôi trách móc.\\nMuốn anh Soutetsu thấy rằng――quả nhiên, lỗi là ở con người.」"
1058 = "「Tôi cũng vậy――rất vui vì cô đã ở bên tôi.\\nVì vậy, tôi muốn cô hãy ở bên tôi.」"
1059 = "「Tôi cũng vậy――\\nkhông hề muốn cứ ôm mãi sự oán hận đó.」"
1061 = "「Trường hợp của tôi cũng vậy.\\nSự oán hận, đột nhiên tuôn trào khi tôi vừa mới quen với nỗi đau.」"
1063 = "「Tôi cũng, yêu――\\nanh.」"
1065 = "「Cả hai chúng ta, đều đã hiểu lầm rồi nhỉ.\\nChúng ta đã luôn trân trọng ôm ấp một kỷ niệm hiểu lầm.」"
1067 = "「Thực ra ngay từ đầu,\\ntôi đã không hề muốn oán hận mẹ.」"
1069 = "「Chắc là vậy rồi.」"
1071 = "「Ba mẹ tôi từng kinh doanh.\\nLàm đại lý nhập khẩu cá nhân――có vẻ như công việc làm ăn rất thuận lợi.」"
1072 = "「Tôi thì……thực sự chỉ ở đây thôi.」"
1074 = "「Tôi nghĩ là tôi hiểu được.」"
1076 = "「Tôi chưa bao giờ chơi cờ bạc cả――\\nnhưng chắc chắn cảm giác lún sâu vào nó cũng giống như vậy.」"
1078 = "「Vì vậy, cả hai chúng ta đã hiểu nhau theo cách có lợi cho bản thân……\\nvà biến nó thành cái cớ để làm như vậy nhỉ.」"
1080 = "「Vì vậy――chắc chắn, điều đó gần giống với sự bỏ cuộc hơn.\\nTừ bỏ việc tiếp tục oán hận……kết quả là, tôi cảm thấy nhẹ nhõm hơn.」"
1083 = "「Vì vậy, khi gặp anh Soutetsu. Nghe chuyện về vụ tai nạn――」"
1084 = "「Vì vậy, tôi rất vui vì anh đã ở đây.\\nỞ bên cạnh tôi, anh Soutetsu.」"
1086 = "「Ở bên cạnh tôi.\\nNgười đã dạy tôi biết yêu――anh Soutetsu, đã ở bên cạnh tôi.」"
1087 = "「Tôi đã nghĩ là do mình làm một đứa trẻ ngoan chưa đủ.\\nNếu tôi cố gắng hơn nữa thì……」"
1088 = "「Đúng, vậy nhỉ. Vâng――con không sao đâu. Vậy nhé, hẹn gặp lại.\\nA! Còn nữa, Mama……không, mẹ ơi.」"
1090 = "「Chính cô đã giúp tôi nhìn thấy.\\nTôi có thể nghĩ về cô nhiều đến thế, và trở nên ấm áp đến thế.」"
1092 = "「Có vẻ là vậy nhỉ.」"
1093 = "「Ừm……」"
1094 = "「Đúng vậy nhỉ.\\nViệc tôi được cứu rỗi là sự thật.」"
1095 = "「Vâng. Tôi hiểu――nhưng mà.」"
1097 = "「Vậy sao anh?」"
1099 = "「Vâng, anh Soutetsu. Tôi cũng vậy.」"
1105 = "「Vì yêu ba, nên dù không thể ở bên nhau nữa,\\nmẹ cũng không thể nào bỏ mặc ba được.」"
1110 = "「Paulette.\\nTôi, đã――yêu cô rồi.」"
1111 = "「Paulette.」"
1112 = "「Paulette, cô không làm gì sai cả.」"
1113 = "「Mẹ cô cũng rất coi trọng Paulette. Cảm thấy cô là người không thể thay thế.\\nChính vì vậy――bà ấy mới không thể cướp cô khỏi ba cô.」"
1115 = "「Thế rồi, mẹ đã bỏ đi.\\nBỏ lại tôi mà đi――và không bao giờ quay lại nữa.」"
1120 = "「Ba quyết định tranh cử thị trưởng, công ty không thể hoạt động được nữa.\\nMẹ――vì nhiều chuyện nên có vẻ như đã đến giới hạn chịu đựng.」"
1121 = "「Nghe nói có chuyện mời gọi nhà máy \\x%lエアクラ;#00ffc040;Aircra%l;# đến Ohimitera――\\nNên ba tôi quyết định hợp tác với phong trào phản đối.」"
1124 = "「Bây giờ nghĩ lại, chắc chắn――tôi lúc đó,\\nkhông phải là muốn bênh vực đường sắt đâu.」"
1126 = "「Đúng là……cách lý giải, có thể là một sự hiểu lầm.\\nNhưng, việc chúng ta tiếp tục ôm ấp nó――không phải là hiểu lầm.」"
1130 = "「Nhờ vậy mà tôi――chắc chắn đã,\\nđược anh Soutetsu cứu rỗi.」"
1132 = "「Dù vậy Paulette vẫn dạy cho tôi mà.\\n“Việc trút sự oán hận lên đường sắt là sai lầm”.」"
1133 = "「Nghe chuyện đó xong, quả nhiên tôi vẫn cảm thấy hơi buồn.\\nNhưng, cũng cảm thấy an tâm vì biết mình không bị vứt bỏ.」"
1134 = "「Cảm ơn anh. Vì đã ở đây.」"
1135 = "「Cảm ơn mẹ――vì đã kết hôn với ba――\\nvà trở thành mẹ của con.」"
1136 = "「Cảm ơn anh.」"
1144 = "「Những chuyện như vậy, chắc chắn là do hợp nhau nhỉ.」"
1147 = "「Quả nhiên là?」"
1149 = "「Tôi dần quen với cuộc sống chỉ có hai người với ba.\\nĐó là lúc tôi bắt đầu cảm thấy không thể tha thứ cho mẹ.」"
1151 = "「Ngày hôm đó――tôi, đã rất buồn.」"
1153 = "「Không phải vậy đâu.」"
1158 = "「Anh Soutetsu cũng――」"
1159 = "「Anh Soutetsu cũng biết đúng không.\\nSự đau lòng này――sự bất lực này.」"
1160 = "「Anh ở đây, là tôi vui rồi.」"
1161 = "「!」"
1162 = "「!? Không――Tôi thì――」"
1241 = "Hơi ấm và nhịp đập,\\ntruyền đến từ bàn tay của Paulette."
1242 = "Đúng hơn là……\\nPhải rồi. Nói cách khác, đúng hơn là――"
1245 = "Dù vậy, vẫn có một người ấm áp ở bên cạnh tôi――\\nChỉ vậy thôi, tôi đã cảm thấy mãn nguyện đến nhường này."
1246 = "Không, đó có lẽ vốn dĩ,\\nlà những thứ phát ra từ chính tôi."
1248 = "Có những sự hiểu lầm đẩy những người yêu nhau đến bờ vực chia ly,\\nvà cũng có những sự hiểu lầm giúp họ cứu rỗi lẫn nhau, để rồi đoàn tụ."
1252 = "Sau đó là tiếng bước chân――\\nPaulette đang tiến về phía này."
1261 = "Khoảng trống vô phương cứu vãn đã sinh ra đó――\\nCon người chắc chắn chỉ có thể bắt đầu lấp đầy nó bằng sự oán hận trước tiên."
1262 = "Nghĩ kỹ lại thì, đây chẳng phải chỉ là nghe lén thôi sao――"
1268 = "Nhưng, tôi không hề đánh mất.\\nMichiko đã bảo vệ tất cả――đã để lại cho tôi."
1271 = "Nụ cười gượng gạo mà Paulette tạo ra,\\ncười không được tự nhiên cho lắm."
1275 = "Nếu lúc đó, tôi đưa ra một quyết định khác,\\nthì Michiko, ba, và mẹ――chắc chắn đã không phải chết."
1286 = "Bàn tay đang đan vào nhau nóng rực, ướt đẫm mồ hôi như thể đang hòa tan vào nhau."
1291 = "Ban đầu, thực sự chỉ là nhúng tay vào một cách vô tư――\\nNhưng dần dần, những thứ tích tụ lại ngày càng phình to ra."
1293 = "Gánh nặng vốn dĩ chia sẻ cho hai người, nay đổ dồn lên một mình mẹ.\\nViệc nhà cũng không kham nổi nữa."
1303 = "Chỉ đơn giản là……\\nMẹ của Paulette cũng không đủ sức lực mà thôi."
1307 = "A, quả nhiên――cả hai chúng ta,\\nvào ngày hôm đó, khoảnh khắc đó. Chỉ là đã nhận ra mà thôi."
1313 = "Dòng chảy dừng lại."
1315 = "Bởi vì Houshou Mototada――Ngân hàng Kumamoto,\\nđã bắt đầu hậu thuẫn cho phong trào mời gọi."
1317 = "Thật đẹp――\\nTôi chỉ có thể nghĩ như vậy."
1318 = "Những thứ đã mất đi, sẽ không bao giờ quay trở lại.\\nKhoảng trống đã được tạo ra, chỉ còn cách tiếp tục mang theo nó."
1321 = "Cú sốc của sự mất mát quá lớn, thực sự quá lớn.\\nNgoài việc làm quen với nó, tôi chẳng thể làm được gì khác――"
1323 = "Từ đó trở đi, không còn lời nào được thốt ra nữa."
1325 = "Muốn cứu cả hai người cùng lúc, nhưng bản thân lại đạt đến giới hạn――\\nNên, bất đắc dĩ……bà ấy bị buộc phải làm như vậy."
1327 = "Bàn tay buông ra."
1329 = "Một bàn tay vươn ra.\\nRụt rè, và vô cùng yếu ớt."
1332 = "Âm thanh, thay đổi. Chuyển sang tiếng Hinomoto.\\nChuyển sang âm thanh――ngôn ngữ mà tôi có thể hiểu được."
1334 = "Bức màn mí mắt được vén lên.\\nĐôi mắt xanh biếc đang nhìn tôi."
1336 = "Việc chuyển sang tiếng Hinomoto = để cho tôi nghe,\\ntôi đã tự ý cho là như vậy."
1337 = "Sự im lặng. Dài――quá dài.\\nĐến mức người nghe ở đầu dây bên này là tôi cũng ngày càng thấy bất an……!?"
1339 = "Nói rồi, cô ấy cất giọng \"aha\" đầy kịch tính."
1341 = "Một tiếng thở dài,\\nnghe như kiệt sức, nhưng cũng nghe như hoàn toàn mãn nguyện."
1343 = "Đôi mắt nhắm nghiền lại.\\nNước mắt không rơi――thay vào đó, những lời nói tuôn trào."
1345 = "Cái gật đầu.\\nCảm giác thật mong manh."
1346 = "Khoảng cách giữa cái trước và cái sau……nếu không phải là do may mắn,\\nthì có lẽ chỉ có thể gọi là sự hợp nhau mà thôi."
1351 = "Đại tư tế và mọi người đã về từ lâu. Chỉ để lại lời nhắn sẽ tuân theo quyết định của chúng tôi.\\nDù đã cố gắng chống cự, Reina cũng bị cơn buồn ngủ đánh bại."
1359 = "Như thể cạn lời trước một câu chuyện ngớ ngẩn.\\nNhưng nụ cười ấy lại rạng rỡ như một bông hoa đang nở."
1361 = "Tên của người đang ở ngay trước mắt tôi,\\nngười đang nắm lấy tay tôi."
1363 = "Dù đó là điều hiển nhiên,\\ndù có làm gián đoạn câu chuyện đi chăng nữa――tôi vẫn không thể không nói ra."
1365 = "Thật may vì tôi đã không gượng ép tìm kiếm một thứ gì đó thay thế,\\nđể lấp đầy bản thân mình."
1367 = "Thật may vì tôi đã không để sự oán hận lấp đầy bản thân mình."
1381 = "Tôi không đủ mặt dày để làm điều đó――\\nHay đơn giản chỉ là do tôi quá yếu đuối."
1383 = "Chúng tôi, trao nhau nụ hôn đầu tiên."
1385 = "Tôi đã nghĩ mình không có tư cách.\\nTôi đã nghĩ mình đánh mất tư cách để yêu một người, để nắm lấy tay một người."
1387 = "Ngay cả tôi, người chỉ nghe thứ tiếng Frank không hiểu ý nghĩa,\\ncũng cảm thấy khát khô cả cổ từ lúc nào không hay."
1389 = "Chỉ là, toàn bộ con người tôi đang dần bị lấp đầy\\nbởi hơi ấm, nhịp đập và ánh mắt của Paulette."
1390 = "Tôi hoàn toàn không nghĩ như vậy.\\nBởi vì, người giết chết Michiko……theo một nghĩa nào đó, quả nhiên là tôi."
1394 = "Đó là tất cả những gì Paulette yêu cầu,\\nkhi tôi đưa cho cô ấy số điện thoại nhận từ cô Miyamoto."
1395 = "Ba của Paulette, cựu thị trưởng, ông Hinai Kouzou.\\nTôi chỉ biết đến đánh giá rằng ông ấy là một người tài năng, nhưng――"
1397 = "Tôi cảm thấy như mình muốn nói điều gì đó,\\nnhưng lại không thể thốt nên lời, cũng chẳng thể nghĩ ra từ ngữ nào."
1399 = "Khi đón lấy, tôi cảm nhận được sự run rẩy truyền đến.\\nDù vậy, lòng bàn tay của Paulette vẫn rất ấm áp."
1402 = "Chính bản thân tôi là minh chứng rõ ràng nhất,\\nlàm sao tôi có thể tự cho mình là ngoại lệ được chứ……"
1403 = "Ngày hôm đó, là ngày nào.\\nTôi thậm chí không cảm thấy cần phải xác nhận lại."
1406 = "Toàn bộ con người tôi được lấp đầy, trào ra khỏi cổ họng.\\nNó chỉ đơn thuần――hóa thành một cái tên vô cùng quan trọng."
1408 = "Nỗi đau đó, tôi cũng biết. Nỗi đau ấy đến giờ vẫn không thể xóa nhòa.\\nVậy mà hiện tại, giọng nói của Paulette lại không hề mang cảm giác u ám."
1409 = "Tôi đã được cứu rỗi bởi câu nói đó."
1411 = "Tôi bảo cô ấy đợi một chút rồi đi pha trà xanh,\\nchuẩn bị tư thế sẵn sàng lắng nghe và ngồi xuống."
1418 = "Ba của Paulette đã thuê người giúp việc để giải quyết vấn đề đó――\\nKết quả là, đó lại trở thành ngòi nổ cho sự đổ vỡ."
1422 = "Rõ ràng là muốn giải quyết tình hình, muốn giúp đỡ những người quan trọng,\\nnhưng bản thân khi còn nhỏ lại quá bất lực, chẳng thể làm được gì――"
1424 = "Lỗi không phải ở sự vật, mà là ở con người.\\nCô ấy đã dạy tôi rằng, người mắc sai lầm, lúc nào cũng là con người."
1428 = "Mỗi khi âm điệu hỉ nộ ái ố thay đổi, tôi lại tưởng tượng ra nội dung\\n――đến mức lòng bàn tay ướt đẫm mồ hôi dính dấp."
1442 = "Paulette bật cười khúc khích."
1443 = "Paulette chậm rãi uống ngụm trà xanh,\\nrồi thở ra một hơi dài ấm nóng."
1444 = "Mệt mỏi,\\nPaulette tựa hẳn người vào ghế."
1445 = "Nụ cười nở trên môi Paulette, yếu ớt và đầy vẻ buồn bã.\\nNhưng nó đang――chấp nhận, và tha thứ cho tất cả."
1446 = "Phải khiến họ rút lui trước khi tiếng nói ủng hộ mời gọi trở nên sôi nổi――\\nTuy nhiên, suy nghĩ đó đã không diễn ra suôn sẻ."
1447 = "Tôi nói chuyện này được không? Ánh mắt Paulette như muốn hỏi vậy.\\nTất nhiên, tôi không có lý do gì để từ chối."
1448 = "Phừng phực.\\nLòng bàn tay Paulette trở nên ấm áp."
1449 = "Giọng kể lại như chuyện của người khác.\\nPaulette khi đó còn là một đứa trẻ, tất nhiên cũng là người trong cuộc, vậy mà――"
1450 = "Mỉm cười dịu dàng, Paulette hướng mắt về phía chiếc đồng hồ treo tường.\\nĐã qua ngày mới, và hơn hai tiếng đồng hồ đã trôi qua."
1455 = "Giọng nói như thể cạn lời của Paulette,\\nlại mang một âm hưởng dịu dàng."
1462 = "Chằm chằm, chằm chằm――nhìn tôi."
1464 = "Một giọng nói nhẹ nhàng.\\nMột giọng nói sảng khoái."
1472 = "Đến lúc nhận ra thì nó đã trở thành một lượng khổng lồ,\\nvà bản thân đang đứng ở một nơi hoàn toàn không thể rút lui được nữa."
1478 = "Một câu nói đó, đã rũ bỏ một cách ngoạn mục\\nnhững lời răn đe của quá khứ vẫn luôn trói buộc bản thân cô ấy."
1479 = "Nghe tôi nói thật,\\nPaulette lộ vẻ ngạc nhiên."
1487 = "Cảm giác đó, ngột ngạt và vô cùng chân thực――\\nTim đập quá nhanh, nhưng lại thật dễ chịu."
1502 = "Không phải là nghe lén.\\nQuả nhiên Paulette đang muốn truyền đạt cho tôi."
1503 = "Đây là――vết thương của Paulette.\\nVì vậy, cô ấy mới trở nên cố gắng gượng ép bản thân đến mức đó."
1504 = "Đó không phải là một kỷ niệm cay đắng sao?"
1506 = "Chính vì giọng điệu thản nhiên ấy,\\nmà tôi có cảm giác như nhìn thấy rõ mồn một hình dáng của nó."
1507 = "Người được cứu rỗi, là tôi cơ mà――\\nChưa kịp nói ra, giọng nói của Paulette đã tuôn trào."
1508 = "Thuê nhân viên, mở thêm văn phòng, đơn đặt hàng liên tục tăng cao――\\nĐiều phá vỡ vòng tuần hoàn tốt đẹp đó, chỉ là một nguyên cớ rất nhỏ."
1510 = "Dòng âm thanh――\\nnhư một khúc ca buồn, như một cơn mưa phùn――đã dừng lại."
1512 = "Nếu vậy, cô ấy đang cho tôi nghe.\\nPaulette đang cho tôi nghe tâm tư của cô ấy."
1514 = "Đôi bàn tay vừa buông ra ấy vươn tới,\\náp lên má tôi."
1520 = "Nơi cô ấy đã đi đến,\\nsau cuộc trò chuyện tuôn trào như thác đổ bằng tiếng Frank."
1525 = "（Không――khoan đã, mình）"
1527 = "（A, không, chắc chắn là vì “còn là một đứa trẻ”……\\nNên dù là người trong cuộc, cô ấy cũng không thể can thiệp vào sự việc.）"
1528 = "（A……）"

[selections]
