# ポーレットh3_誘惑アイスコーヒー.txt

[info]

[characters]
1134 = "Paulette"
1230 = "Soutetsu H"

[character_subs]
1448 = "Paulette"
1580 = "Soutetsu"

[script]
37 = "(Sột——soạt——sột——）"
703 = "（Mơn trớnnnnn）"
705 = "「——Em cứ vắt bao nhiêu sữa của anh tùy thích.」"
709 = "「……Tôi sẽ thử dùng phương pháp cổ điển xem sao.\\nChúng ta di chuyển thôi. Xin hãy đi cùng tôi.」"
711 = "「……Em——muốn có, em bé.」"
864 = "「Không,\\nngười đáng được cảm ơn không phải là anh, mà là ông Taito chứ.」"
867 = "「Trước đây, đã từng xảy ra một vụ náo động nhỉ.」"
872 = "（Phập!）"
873 = "「Nhé? Anh Soutetsu——, cùng nhau——, cùng nhau nhé——」"
874 = "「Cà phê đá à?」"
890 = "Tôi kéo nhẹ phần thịt xung quanh,\\nnong rộng lỗ hậu dễ thương ra một chút."
893 = "「Á——a——mông——bị xoa bóp——\\nThế này——thì——ưm——」"
894 = "「Á——bị ngoáy sâu——vào rồi——nhưng mà——\\nHơn nữa——a——hơn, nữa——sâu, hơn——nữa——」"
897 = "「Á……a——mông……phù——\\nBản thân em……chưa từng……chạm vào……nhưng——」"
898 = "「Á」"
899 = "（Siếttttttt!）"
900 = "「Đúng vậy nhỉ——Anh cũng——, tuyệt nhất là——\\nTuyệt nhất là——anh vẫn muốn làm thế——」"
901 = "「Hyan!!」"
902 = "「Á!!?」"
903 = "「Á!?」"
904 = "Ngón tay không đút vào.\\nCũng chưa chạm trực tiếp vào hậu môn."
906 = "「Ư——a——」"
907 = "「!」"
908 = "「っ!」"
910 = "「Hừm——cái này à?」"
912 = "「Hà——á! Anh Soutetsu——mặt——khuôn mặt anh,\\nEm muốn nhìn——muốn nhìn quá——」"
914 = "「Phù——ưm——chụt——chụt——\\nchu——ưm——chu——chu」"
915 = "「Phù——a——hà——a——」"
917 = "「Phù——a——nhiều quá——nhiều quá——\\nƯm, của anh Soutetsu——tinh dịch——vào trong, tử cung——rồi——」"
919 = "（Phập! Phập! Phập! Nhóp nhép!）"
920 = "「Phiaaaaaa!!!」"
923 = "「Sụtttttttttt!!!」"
924 = "「Ưm!? Ưm——ưm——ưm——\\nƯm——ực——ực——ưm——ưm——」"
926 = "「E hèm——\\n『A, anh Soutetsu. Anh làm thêm giờ vất vả rồi.』」"
927 = "「Í——a á a a a a a a a a a a!!」"
928 = "「Í!!」"
929 = "「Uo!?」"
931 = "「Ngoạm——chụt——chụtttt——chụt!\\nChu! Chụt! Chụtttt! Liếm!」"
933 = "「Ngoạm——ưm——chu——chụt——\\nliếm——liếm——liếm——chụtttt」"
934 = "「っ!」"
935 = "「っ——」"
937 = "Dù vậy, hông tôi vẫn không dừng lại."
938 = "「A——a——」"
940 = "「A——ưm——phù——a, anh Soutetsu——\\nEm——em——chuyện đó——」"
942 = "「Ngoạm——ưm——ưm～～\\nliếm, liếm——chu——chụt」"
944 = "「A——Paulette——」"
946 = "「A……ưm——chụt——chu——\\nThích——thích anh lắm——ưm——anh Soutetsu」"
948 = "「A……ưm——ưm——ực——ưm——\\nPhù——hà! Hààà!」"
950 = "「A……sướng quá……sướng quá……anh ơi……\\nPhù——của, anh Soutetsu——dương, vật——a」"
951 = "「A……\\nVáy cũng bị ố mất rồi.」"
953 = "「A」"
954 = "「っ!」"
955 = "「Á!?」"
956 = "「A, thôi chết——Nó cũng dính vào người em rồi.」"
958 = "「Chụt」"
965 = "「Chụt——chụt——liếm——liếm——」"
966 = "「Chụt——chu——liếm——liếmmmm」"
967 = "「Chụt——ưm……\\nAnh Soutetsu đã chuẩn bị sẵn——si-rô đường rồi nhỉ.」"
968 = "「Liếmmmmm!」"
969 = "「Chụt! Chu! Chụt! Chu!!」"
970 = "「Chu! Liếm! Chụt! Chụtttt!\\nChụt! Chụt! Chu! Chụtttt!!」"
971 = "「Ừm——」"
972 = "Không biết có phải do kích thích lỗ hậu hay không,\\nâm đạo của Paulette trơn ướt và quấn chặt hơn bình thường."
974 = "「Ưm——chụt——chụt——chụt——\\nSụt——!——Sụtttttt!!!」"
976 = "「Ưm……a——sướng, quá——ạ——\\nƯm——Tay, anh Soutetsu——cứng——quá」"
977 = "「Ưm……nhóp nhép——ưm——ực——phù. Ngon quá.\\nNhưng mà……em nghĩ nếu có thêm sữa thì sẽ ngon hơn nữa.」"
980 = "「Ừ. Cụ thể là, anh muốn xem cái dáng vẻ em vừa ý thức được ánh nhìn của anh,\\nvừa giả vờ như tình cờ để quyến rũ anh ấy.」"
981 = "「Ừ.」"
982 = "Thử dập hông vào sâu hơn,\\ncơ thể Paulette lại run lên bần bật."
986 = "「A, có vẻ là nó đấy. Cho em xem với. ...Đúng rồi! Cái này,\\nchính là nó! May quá~, cảm ơn Soutetsu nhé!」"
987 = "「Ừ. Anh cũng muốn cô bé của Paulette.」"
988 = "「Ừ, anh cũng vậy.」"
989 = "「Ừ, anh muốn.」"
990 = "「Ừ, thực sự rất đẹp. Hơn nữa——」"
991 = "「Vâng, anh Soutetsu. Em cũng vậy.」"
992 = "「Vâng, anh Soutetsu.」"
993 = "「Hửm?」"
994 = "「Ưm～～ưm——ưm～～～」"
995 = "Đầu ngón tay vừa thử đút vào,\\nđã bị hậu môn siết chặt dữ dội như muốn đẩy ra."
996 = "「Anh hiểu rồi.」"
998 = "「Vâng! Anh Soutetsu. Vậy thì, em làm đây nhé?」"
999 = "「Nếu được thì, anh cũng muốn em……làm cho chỗ đó được thư giãn.」"
1002 = "「X... Xin lỗi anh!?」"
1005 = "「Đúng vậy nhỉ~」"
1006 = "「Thì……em cũng có nghe——người ta, nói, vậy——ưm——\\nNhưng, mà——thực tế——lại đến mức này, thì——a——á」"
1009 = "「Đâu chỉ một chút, anh rất muốn xem là đằng khác. Không phải xem quần lót,\\nmà là muốn ngắm nhìn dáng vẻ quyến rũ của Paulette.」"
1011 = "「Ngay cả ở mông, cũng có thể đạt được khoái cảm tình dục nhỉ.」"
1013 = "「Sướng——Em vui lắm. Anh Soutetsu」"
1014 = "「Em muốn anh Soutetsu được thư giãn nên……\\nThật sự xin lỗi anh. Em sẽ lau ngay đây——Ủa?」"
1016 = "「Em hiểu rồi. Nếu đó là mong muốn của Soutetsu,\\nthì em sẽ cố gắng thử xem.」"
1018 = "Lỗ hậu môn đang co bóp nhấp nháy."
1019 = "「Cô bé——không thể chịu đựng——được nữa, rồi——\\nNên là——xin hãy cho em——dương, vật——của anh Soutetsu」"
1021 = "「Em hiểu rồi——vậy thì」"
1022 = "「Em……ừm, em tự thấy——\\nĐường nét sau lưng mình, cũng khá là, đẹp, nên là」"
1024 = "「Có rồi. Khăn giấy.\\nEm sẽ lau ngay bằng cái này đây.」"
1026 = "（Phập——phập——nhóp——nhép——）"
1033 = "「Pau……lette」"
1034 = "「Paulette……Anh muốn làm tình với em.」"
1035 = "「Paulette」"
1036 = "「Paulette! Paulette! Paulette!!」"
1040 = "「Nếu là bây giờ... anh có muốn xem một chút không?」"
1045 = "「Đồ lót màu xanh đen cực kỳ tôn lên làn da trắng của em.\\nAnh nghĩ cởi hết ra thì phí lắm.」"
1048 = "「Được chứ? Anh Soutetsu đang nghỉ giải lao sau khi làm thêm giờ.\\nKhi em gọi, anh hãy quay lại nhé?」"
1050 = "「Anh biết ngực em đẹp rồi——nhưng không ngờ mông em cũng vậy.\\nCơ thể Paulette, chỗ nào cũng tuyệt vời hết.」"
1052 = "（Phụt）"
1054 = "「Ra mất——xuất tinh——anh xuất tinh mất——」"
1058 = "「Cái này……là lỗi của em, đúng không?」"
1059 = "「Thế này thì, anh không thể thư giãn được nhỉ?」"
1060 = "「Tài liệu ở đây không thể nghi ngờ gì nữa, toàn là hàng cực phẩm mà.\\nTrước đây cũng——」"
1062 = "（Siếtttt!）"
1064 = "「Nếu vậy thì, sữa——」"
1066 = "「Lúc đó em xin lỗi nhé. ...Đột nhiên Reina bảo là, ừm...\\nthấy quần lót... nên em hoảng quá.」"
1067 = "「Đương nhiên rồi.\\nBởi vì em đã dạy cho anh một sự thật mang tính chấn động đối với anh mà.」"
1068 = "「Tại sao ông ấy lại thu thập những thứ này——anh không thể hiểu nổi,\\nnhưng thực tế là bộ sưu tập này đã giúp ích rất nhiều.」"
1069 = "「Anh Soutetsu——a——anh Soutetsu」"
1070 = "「Anh Soutetsu, cũng——ưm——đã——thế này rồi——\\nCứng, quá——nóng, quá——phù——」"
1071 = "「Soutetsu...\\nAnh vẫn nhớ những gì em từng nói sao?」"
1072 = "「Q, quyến rũ——sao anh?」"
1181 = "Do trang phục, hay do bầu không khí đây."
1182 = "Chỉ cần như vậy thôi, lời nói dường như đã trở nên quá dư thừa."
1185 = "Paulette cẩn thận lau sạch toàn bộ dương vật,\\nchỉ trong chốc lát, độ cứng và dục vọng lại trỗi dậy."
1189 = "Nhưng Paulette lại đang mong đợi ra mặt.\\nNếu vậy, tôi không thể chần chừ được nữa."
1191 = "Nhưng Paulette không hề dừng lại."
1211 = "Bị lau đi——hay đúng hơn là được dọn dẹp sạch sẽ."
1212 = "Chỉ với một tờ khăn giấy mỏng manh mơn trớn như thế,\\ndương vật cương cứng càng trở nên tham lam, tự động giật nảy lên."
1235 = "Trông như thể nó đang đòi hỏi ngón tay tôi,\\nđang cầu xin tôi đút vào vậy."
1246 = "Cảm giác thật dễ chịu, khiến tôi đâm ra nôn nóng.\\nTôi muốn cô ấy chạm vào trực tiếp hơn nữa——"
1247 = "Bởi vì lúc này, gần như trong vô thức, tôi đang dán chặt ánh mắt——\\nchằm chằm vào nửa thân dưới của Paulette."
1249 = "Sau đó, đến giới hạn tưởng chừng như sắp nôn ra,\\nPaulette từ từ rút đầu lại——"
1251 = "Mỗi lần trượt lên trượt xuống, môi lớn lại lật ra quấn lấy,\\nmàu hồng bên trong Paulette làm mãn nhãn tôi."
1252 = "Tờ khăn giấy đặt trên đùi\\nbất giác khiến tôi liên tưởng đến tình dục."
1255 = "Nhận được thông báo về các câu hỏi liên quan, chúng tôi đã vội vàng tìm kiếm,\\nnhưng cả trong Tòa thị chính lẫn Đường sắt Ohimitera đều không có."
1257 = "Kể cả sau khi làm tình, khi dục vọng thể xác đã nguội lạnh,\\nchỉ cần những nụ hôn nũng nịu lặp đi lặp lại trên môi thôi là đủ."
1258 = "Sự kích thích do bị đè nén truyền đến dương vật,\\nquá sướng, khiến tay tôi càng xoa bóp mạnh hơn."
1262 = "Dòng tinh dịch phun ra xối xả,\\nchỉ trong chốc lát đã lấp đầy tử cung của Paulette."
1268 = "Rằng con gái đặc biệt nhạy cảm với ánh nhìn của người khác giới mà mình thích,\\nvà những thứ tưởng chừng như vô tình để lộ, thực chất là cố ý cho xem."
1270 = "Toàn bộ dương vật cương cứng bị cô ấy nuốt trọn một hơi."
1271 = "Thỉnh thoảng, đầu lưỡi cô ấy mơn trớn rãnh quy đầu,\\nđôi môi mím lại bằng lực mút mạnh quấn lấy tôi."
1273 = "Trầm tư suy nghĩ——\\nMột lát sau, đôi mắt xanh biếc mở ra, ánh lên một tia sáng mạnh mẽ."
1275 = "Hơi thở gấp gáp thoang thoảng mùi tinh dịch."
1277 = "Cô ấy há miệng thật to, cho tôi thấy bên trong đã trống rỗng,\\nrằng cô ấy đã nuốt trọn tinh dịch của tôi."
1279 = "Cô ấy dùng dương vật của tôi như một cái nắp, nhốt toàn bộ tinh dịch lại——"
1280 = "Đỉnh của dương vật cương cứng, cho đến rãnh quy đầu.\\nCô ấy ngậm trọn vào miệng đến tận đó."
1283 = "Ánh mắt ngước nhìn tôi dịu lại như muốn nói 'Em biết rồi'.\\nHơi thở ngắn và nhẹ của cô ấy khẽ mơn trớn những sợi lông tơ của tôi."
1284 = "Để vắt cạn tinh dịch——sữa của tôi,\\ncô ấy ra sức gật gù đầu liên tục."
1288 = "Cô ấy đang tìm khăn tay sao?"
1290 = "Paulette đưa ánh mắt có phần mơ màng\\nnhìn quanh đống tài liệu chất như núi."
1292 = "Khuôn mặt hơi ửng đỏ,\\ncô ấy cựa quậy, tỏ vẻ ngượng ngùng——À."
1293 = "「Tinh dịch——của anh Soutetsu——nhận vào, tử cung——ưm——\\nVào cô bé——vẫn là, tuyệt nhất, nên là——」"
1297 = "Cúc áo ngực, một cái, hai cái——\\nRồi ba cái, bị mở ra khá rộng."
1298 = "Cô ấy tháo móc cài ở eo, khéo léo cởi váy ra,\\nrồi lục lọi trong túi chiếc váy vừa cởi……"
1300 = "Ở phần đỉnh——chỉ phần đỉnh, một cách cẩn thận đến dai dẳng,\\nchiếc lưỡi nhỏ màu hồng dễ thương truyền nước bọt và hơi nóng vào."
1303 = "Sự kích thích mà tôi hằng mong đợi, lại quá yếu ớt."
1306 = "「Cái đó……lỗ hậu——tự nhiên, em……\\nCũng cảm thấy rất có hứng thú——nhưng mà」"
1311 = "Đã xuất tinh xong.\\nNhưng Paulette vẫn ra sức đè hông xuống."
1314 = "Lực hút như đang vòi vĩnh tinh trùng.\\nCả tôi và Paulette đều đã đến giới hạn."
1334 = "Tóm chặt lấy hông cô ấy,\\ntôi ép sát đầu dương vật vào cửa tử cung, cọ xát và vặn sâu vào."
1337 = "Vừa xoa bóp, tôi vừa kéo quần lót của cô ấy xuống,\\nđẩy nhẹ về phía trước như muốn giúp một tay——"
1339 = "Tôi cũng muốn ra. Muốn tận hưởng khoái cảm nhiều hơn nữa.\\nSuy nghĩ ấy dẫn đến hành động một cách thành thật."
1344 = "Rõ ràng chúng tôi là người yêu của nhau,\\nnhưng lại có cảm giác như đang làm chuyện mờ ám, khiến tôi toát cả mồ hôi."
1345 = "Hai hông dính sát vào nhau đến mức như muốn lún vào,\\nđầu dương vật ấn mạnh vào cửa tử cung của Paulette."
1346 = "Cứ thế khao khát, và được khao khát.\\nChúng tôi đan lấy nhau, trao nhau nụ hôn dài và chậm rãi."
1347 = "Dữ liệu thống kê về số lượng tàu chở hàng đến và đi tại ga Ohimitera,\\ncùng với tổng khối lượng vận chuyển của chúng."
1349 = "「Em không biết——đâu——nên là——như thế này——\\nPhù——a——mông——lại có cảm giác, như vậy」"
1352 = "Muốn chạm vào, nhưng tay không với tới.\\nNên thay vào đó, tôi lại xoa nắn đường cong tròn trịa của cặp mông——"
1354 = "Tôi muốn tóm lấy đầu cô ấy và dập hông thật mạnh——\\nNhưng tôi đành cố dùng lý trí để kìm nén sự thôi thúc bạo lực đó."
1356 = "Có vẻ như độ co giãn khá tốt.\\nHơn nữa, nó còn đang ngọ nguậy như thèm khát——"
1358 = "Tôi tạm dừng tay xoa mông,\\nchờ xem Paulette định nói gì tiếp."
1359 = "Cứ thế cô ấy lả đi, mất hết sức lực.\\nCó vẻ như chỉ việc chống đỡ cơ thể mình thôi cũng đã tốn hết sức rồi."
1362 = "Thật dễ chịu——và cũng thật thú vị.\\nGiọng nói của Paulette cũng không chỉ đơn thuần là kinh ngạc."
1363 = "Ánh nhìn và ý thức của tôi lúc đó chỉ hướng đến việc tìm kiếm tài liệu,\\ndo đó Paulette hoàn toàn không bận tâm đến chuyện ấy."
1365 = "Cảm giác như bị nhìn thấu tâm can, tôi thoáng bối rối,\\nnhưng ngay lập tức nhận ra rằng việc đoán được suy nghĩ của tôi cũng dễ thôi."
1366 = "Chỉ đơn thuần kích thích xung quanh phần lõm vào nhất,\\nnhư thể đang xoa tròn, nắn bóp."
1369 = "Hơi thở của tôi và Paulette,\\nnhịp điệu của cả hai dần hòa làm một."
1371 = "Quần tôi bị ướt.\\nPaulette đang ngồi xổm xuống."
1372 = "Tôi có cảm giác như nó đang đập vào sâu trong cổ họng cô ấy.\\nHoàn toàn không phải là thứ lỏng lẻo như sữa."
1374 = "Bị quyến rũ mất rồi.\\nDù chẳng cần cà phê đá, hay bất cứ hoàn cảnh nào đi nữa."
1376 = "Nếu vừa rồi là dương vật của tôi thì——\\nNghĩ đến thôi cũng khiến hai hòn bi sun lại."
1379 = "Càng xoa bóp, cảm giác ẩm ướt càng tăng lên."
1380 = "Tôi vuốt tóc cô ấy với ý cảm ơn vì đã vất vả,\\nPaulette ngước lên nhìn tôi bằng đôi mắt hạnh phúc——"
1382 = "Tinh dịch đặc sệt đến mức chính tôi đang xuất tinh cũng cảm nhận được,\\nnhưng Paulette vẫn một mực nuốt cạn."
1387 = "Chạm vào có cảm giác như lòng bàn tay bị hút chặt,\\nđộ đàn hồi mềm mại, thật dễ chịu."
1389 = "Thứ làm ướt quần tôi, đây là……"
1401 = "Một khi đã nhận thức rõ điều đó,\\nquả nhiên tôi vẫn muốn tự mình——muốn tự mình tận hưởng cho thỏa thích!"
1403 = "Cô bé trần trụi\\nvừa trượt vừa mút lấy dương vật cương cứng của tôi."
1414 = "Mùi mồ hôi hòa quyện cùng mùi hương nồng nàn của một người phụ nữ trưởng thành.\\nSự kích thích ấy xộc vào mũi khiến cơ thể tôi cũng nóng ran lên."
1449 = "Nuốt trọn tôi vào sâu một mạch,\\nngay khoảnh khắc đó, Paulette cong người lên như một cánh cung——"
1450 = "Chiếc lưỡi hồng thò ra.\\nPaulette liếm môi cho ướt——"
1451 = "Như muốn lột tung rãnh quy đầu,\\nPaulette vừa hút nhanh và mạnh, vừa tiết nước bọt sủi bọt."
1452 = "Chỉ cần có Paulette ở đó,\\ntôi lúc nào cũng bị quyến rũ."
1453 = "Đó là điều Paulette đã dạy cho tôi."
1454 = "（Nhóp! Nhép! Nhóp! Nhép!!）"
1455 = "Mỗi lần tay Paulette sờ soạng tìm kiếm\\ntrong túi áo ngực và túi quần sau——"
1456 = "Paulette cố gắng ngoái đầu nhìn về phía này,\\nhông cũng vặn theo, tạo ra một lực xoắn bất ngờ lên dương vật."
1457 = "——Tử cung, trứng, đang ngập chìm trong tinh dịch của tôi.\\nPaulette đang khao khát điều đó."
1458 = "——Quệt nước bọt lên dương vật cương cứng của tôi——"
1459 = "Paulette hòa quyện si-rô rỉ ra từ tôi với cà phê dính trên quần\\ntrong miệng, rồi hạnh phúc nuốt xuống."
1460 = "Có vẻ như khó bắt nhịp trượt,\\nchuyển động hông của Paulette trở nên loạn nhịp."
1461 = "Khuôn mặt đỏ bừng,\\nPaulette truyền đạt cho tôi bằng cả cơ thể lẫn lời nói."
1462 = "Dịu dàng, và——\\nVới đôi má ửng hồng, cô ấy nở một nụ cười mềm mại đầy mãn nguyện."
1463 = "Cặp mông.\\nCặp mông trắng trẻo, đẫy đà, tròn trịa."
1464 = "Bàn tay dừng lại.\\nĐôi mắt xanh biếc đang chăm chú nhìn chằm chằm vào háng tôi."
1465 = "Đùi tôi, cả phần đùi trong,\\nđược cọ xát bởi những ngón tay với lực vừa phải."
1466 = "Hông Paulette bắt đầu nhảy múa.\\nMật ngọt ở nơi giao hợp đã sủi bọt đục ngầu và dính dớp."
1467 = "Mật ngọt của Paulette bắt đầu tuôn trào,\\nthấm ướt và quấn lấy dương vật đang bị đè nén của tôi."
1468 = "「A——của anh Soutetsu——to hơn, bình thường——\\nPhù——to, quá——bị nong rộng, ra——a」"
1469 = "Paulette cởi áo sơ mi thả xuống sàn.\\nVà khi cô ấy đưa tay định cởi áo lót, tôi đã lên tiếng ngăn lại."
1470 = "Bộ ngực của Paulette rung lên bần bật.\\nĐôi gò bồng đảo tuyệt hảo đó thu hút ánh nhìn của tôi."
1471 = "Paulette cựa quậy cọ xát hai đùi vào nhau."
1472 = "Trọng lượng cơ thể Paulette, sức nặng của da thịt đập vào tôi theo từng nhịp chuyển động."
1473 = "Tay Paulette cởi cúc quần tôi.\\nCô ấy kéo khóa xuống, mở rộng phía trước, và rồi——"
1474 = "Paulette hôn lên đỉnh đầu tôi thật dịu dàng và ngọt ngào.\\nCứ thế, cô ấy nhẹ nhàng, nhẹ nhàng luồn lách đầu lưỡi."
1475 = "Một cái gật đầu thật sâu."
1476 = "Hông Paulette bắt đầu cựa quậy."
1477 = "Đỏ ửng cả lưng, run rẩy ngượng ngùng,\\nnhưng Paulette vẫn nói rõ yêu cầu của mình."
1479 = "Sự ngọ nguậy của âm đạo không thể theo kịp nhịp điệu và tốc độ."
1482 = "Bóc tách phần thịt mềm nhão bám chặt lấy,\\nrồi lại tiếp tục chẻ vào bên trong——"
1487 = "Sau đó, cô ấy rút một tờ khăn giấy——"
1488 = "（Thế này thì——）"
1489 = "Như đang lăn một viên kẹo lớn,\\nlưỡi Paulette ướt át trêu đùa tôi."
1490 = "Rồi lời chỉ điểm của Reina bất ngờ bay tới, đánh úp——\\nKết quả là mới gây ra một trận cuống cuồng như vậy."
1492 = "Dù vậy, cô ấy vẫn vui vẻ——"
1494 = "……Thế nên ý thức của tôi bị thu hút.\\nVào một nơi khác, một lỗ nhỏ màu hồng dễ thương đang co giật run rẩy."
1495 = "「Á——a——ưm——lỗ, hậu, của em——\\nBị anh Soutetsu——nong……rộng, ra——ưm——」"
1498 = "Thật xấu hổ.\\nĐó tuyệt đối không phải là lời có thể nói ra lúc tỉnh táo."
1500 = "（Nhóp——nhép——trơn——tuột——）"
1509 = "Cảm giác như tinh dịch bị hút ra trực tiếp,\\ntôi nhanh chóng bị đẩy đến ngưỡng xuất tinh."
1512 = "Tinh dịch, tuôn trào."
1513 = "Qua những cái mơn trớn nhẹ nhàng, chậm rãi,\\nlượng tinh dịch chảy ra nhiều chưa từng thấy."
1516 = "Vừa nói xong, Paulette lập tức bày ra một vẻ mặt\\npha trộn giữa vui sướng và e thẹn, trông vô cùng bẽn lẽn."
1534 = "Âm đạo co thắt lại dữ dội không kịp suy nghĩ,\\nbáo cho tôi biết Paulette đã lên đỉnh."
1536 = "「Có muốn thử làm tình……bằng lỗ hậu không?」"
1539 = "Lớp thịt âm đạo cứ thế siết chặt và bám riết lấy,\\nsự kích thích đơn thuần ấy khiến đầu óc tôi trở nên trống rỗng!"
1554 = "Nói đến đó, giọng Paulette bỗng im bặt."
1555 = "Nói xong, Paulette nhắm mắt lại."
1556 = "Cùng với lời nói, cơ thể trắng ngần bật lên đầy sức sống——"
1557 = "Đẩy tôi nằm xuống,\\nPaulette trèo lên người tôi như muốn quấn lấy."
1565 = "Khoái cảm đó còn ngọt ngào và cuồng nhiệt hơn cả khi xuất tinh,\\nchỉ trong tích tắc đã lấp đầy tủy sống, não bộ và tinh hoàn của tôi."
1566 = "Nhận ra điều đó khiến tôi có chút sợ hãi, nhưng hạnh phúc lại nhân lên gấp bội.\\nThế rồi, tôi ôm người mình yêu thật chặt, thật chặt."
1567 = "Nếu vậy thì chẳng cần phải che giấu điều gì cả.\\nNhững gì tôi cảm nhận, những gì tôi nghĩ. Cứ thế chân thật biến chúng thành lời."
1570 = "Hồi đó, tôi hoàn toàn không hiểu tại sao chỉ vì cái quần lót\\nmà lại ầm ĩ lên đến thế——"
1575 = "Toàn bộ dương vật cương cứng bị nắm lấy bởi những ngón tay thạch có lực bóp mạnh,\\nbị siết chặt đến mức như muốn nghiền nát, nhưng tốc độ vẫn không ngừng tăng lên."
1576 = "Vừa được giải phóng khỏi lớp đồ lót, dương vật cương cứng bật lên,\\nsuýt chút nữa thì đập vào mặt Paulette."
1578 = "Mỗi lần Paulette chuyển động,\\nđôi gò bồng đảo cũng rung lên bần bật đầy quyến rũ."
1579 = "Khe ngực phơi bày ra toàn bộ. Hình dáng núm vú lúc ẩn lúc hiện\\nkích thích trí tưởng tượng và dục vọng trong tôi."
1588 = "Cảm giác sung sướng râm ran, cùng dục vọng tựa như sự nôn nóng,\\ntích tụ dần qua sự mơn trớn ở đỉnh đầu tựa như chim nhỏ mổ mồi."
1589 = "Đầu dương vật của tôi bị lực hút đẩy tới,\\nchọc vào vách thịt mềm mại sâu trong miệng Paulette."
1637 = "（Nhưng mà... giờ nghĩ lại, thấy cũng hơi tiếc nhỉ.）"
1638 = "（Ngoáy）"
1639 = "（!?）"
1640 = "（Phập!!!）"
1641 = "「Á!」"
1642 = "「A——không được——em——lại——\\nLại——ra——ra mất!!」"
1643 = "「Vâng——làm đi! Hãy làm, đi ạ——ưm——\\nBắn tinh dịch——vào sâu, nhất——bên trong, em đi」"
1645 = "「Phù——a——sâu, quá——thế này——\\nƯm——sướng quá——cảm giác, như đâm, vào tận bụng, vậy」"
1647 = "（Sụt——chụt——sụt——nhóp nhép——）"
1648 = "（Ư, m……）"
1649 = "（Roạt——）"
1650 = "「Hyaaaaaaa!!」"
1652 = "（Phụt——phụtttt——phụt——phụtttt）"
1655 = "（Phụt! Phụt! Phụt! Phụtttt!）"
1656 = "（Phụt! Phụt! Phụtttt! Phụt!!）"
1658 = "Hông Paulette giật mạnh."
1661 = "（Xoa xoa——nắn nắn——bóp bóp——nắn nắn——）"
1662 = "（Nắn bóp）"
1664 = "「Á!? A——mông——ưm——lỗ, hậu——\\nE, em——chưa từng, tự làm——bao giờ——ưm」"
1666 = "（Nhẹ nhàng）"
1667 = "（Xoay người）"
1668 = "（Sột——soạt——lau——lau——）"
1669 = "（Chà chà）"
1671 = "（Nhóp——nhép——siếttttt）"
1673 = "「Đau——」"
1675 = "（Pặc——Pặc——）"
1676 = "Dùng ngón tay thấm đẫm mật ngọt từ cô bé vuốt ve quanh lỗ hậu,\\nâm đạo của Paulette lập tức co thắt lại."
1681 = "（Đây là……cảm giác khi yêu sao.）"
1682 = "Với tư thế này, tôi không thể cử động mạnh được.\\nCho đến khi cơn sóng khoái cảm dịu xuống, Paulette có lẽ cũng không thể nhúc nhích."
1683 = "（Nếu vậy, lúc đó Paulette vẫn chưa có tình cảm với mình...\\nÀ không, sai rồi. Đơn giản là do mình \"không thèm nhìn\" sao.）"
1684 = "（Hự）"
1686 = "（Giật nhẹ）"

[selections]
