# ポーレットh2_制服変更？.txt

[info]

[characters]
1203 = "Paulette"
1276 = "Soutetsu H"

[character_subs]
1468 = "Paulette"
1560 = "Soutetsu"

[script]
715 = "「...Ẩm thực gia đình đúng là tuyệt thật đấy.」"
878 = "「Không đâu. Thế thì phí lắm. Vì nó tiện dụng thế này cơ mà.」"
880 = "「Không được——em——tè dầm——không được đâu—— Đã là người lớn, rồi mà——em lại——tè dầm mất.」"
882 = "「Để anh phải đợi rồi.」"
883 = "「Cũng không to tát đến mức gọi là ẩm thực Pháp đâu ạ——」"
886 = "「Món hôm nay là ẩm thực Pháp sao? Cảm giác hơi giống món bò hầm một chút.」"
889 = "「Nhưng mà... trực giác mách bảo em đó có thể là một ý tưởng hay. Vừa ít tốn kém, lại có thể quảng bá cho Đường sắt Ohimitera mới... có lẽ vậy.」"
891 = "「Nhưng, thực tế là anh đang——」"
894 = "「Em không có gì phải xin lỗi cả. Đây là phòng của Paulette mà, nếu phải dọn dẹp thì anh cũng sẽ giúp một tay.」"
896 = "「Paulette giỏi quyến rũ thật đấy.」"
897 = "「Hỏi thì chắc họ sẽ chỉ cho thôi. Dù là chị Mayami hay Hibiki thì cũng――――hửm.」"
900 = "「Soutetsu thích món ăn gia đình nào vậy?」"
901 = "「Âm đạo cũng đã hoàn toàn tan chảy rồi.」"
903 = "「Nếu thấy xấu hổ, em cứ nhắm mắt lại là được.」"
909 = "「Một chút——nữa thôi——hự——á—— Nếu ra——, thì cùng nhau——」"
913 = "「Em nghĩ đồng phục ở một mức độ nào đó sẽ nhấn mạnh sự khác biệt giới tính. Nhưng mà, bộ này cũng không đến mức đặc biệt khủng khiếp đâu ạ.」"
923 = "「Nhưng mà——nhưng mà——em——em—— á——fuaaaaaaaaaaan!」"
925 = "「May quá. Hợp khẩu vị của Soutetsu là tốt rồi.」"
927 = "「Đừng——vừa nãy——hi——á—— em——hi——đang——đang ra——rồi——ưm.」"
928 = "「Kia——á——hio——ưm——」"
929 = "「Hya——á! Ưm——phuê——phuya.」"
931 = "「Hya——ưm——tử cung——bị đâm, phập——vào——a.」"
932 = "「Hya——ưm——âm, đạo——đang được dọn dẹp—— phá——dọn dẹp, cẩn thận quá——đừng, mà.」"
935 = "「Á——nhấn cả——quần lót vào——sao——!?」"
937 = "「Hyafuuuu!? Bị húúúút——vào——rồi—— á——uống mất rồi——ưm——hôn——nữa!」"
938 = "「Hyua——sắp bong——ra—— ưm hyu——cái này——tuyệt quá——ưm!」"
940 = "「Yaaaaaaaaa!!」"
941 = "「Hyau!」"
942 = "「Hya! Á——to——to, quá——」"
943 = "「Hian!!」"
944 = "「Á!?」"
946 = "「Á!? Đừng——ưm——đừng có vừa mút mát, vừa——ưm——nói, chuyện——chứ, á——」"
948 = "「Hya!? Khoan, ơ? Soutetsu, này?」"
950 = "「Hya un!? B, bẩn lắm——bởi vì, có nước tiểu——ưm——Soutetsu, này——!」"
951 = "「À——」"
952 = "「!」"
954 = "「Hà——á——không được——thế này—— em——lại——lại——ra mất!」"
955 = "「Hi——ưm——hya——á——」"
956 = "「Phù... phu... phúa.」"
957 = "「Phu... a... fuyahaaa.」"
959 = "「Hà... ưm... chụt——chùn chụt——chuút——」"
960 = "「Anh đang dọn dẹp——giúp em mà.」"
961 = "「Phù.」"
962 = "「Fuaaaaaaaaan!」"
963 = "「Afuuuuuuuuuuun!!!」"
964 = "「I——á——cọ xát——này——ưm——phù—— âm——đạo——bị, nong——rộng——hyua.」"
966 = "「Phì.」"
967 = "「Á.」"
969 = "「Ehehe. Là do mẹ dạy cho em đấy ạ.」"
970 = "「Hô.」"
971 = "「Ồ!」"
972 = "「Ư... a... khó chịu quá à ...nhớp nháp quá.」"
974 = "「Ưm... phụt——」"
975 = "「Ư.」"
977 = "「Á——hi, a——thế này——thích, lắmmmm.」"
978 = "「Ồ——hự——」"
979 = "「Ư——phù——」"
980 = "「Á——á——khôngggggg.」"
982 = "「A——á——á——phụt, vào——rồi—— phù——á——trong, bụng——nóng quá——đập vào, rồi.」"
983 = "「Á——cậu, nhỏ——ưm—— cậu, nhỏ——của Soutetsu——ưm.」"
985 = "「Á——!」"
986 = "「A...」"
990 = "「A... nhưng mà. Đợi em một chút nhé, một chút thôi.」"
991 = "「A... hia... á——phá——á——á——a.」"
992 = "「A... phù——á――――hà——hà——」"
993 = "「A... oa... người em, nhão nhoét hết rồi——」"
995 = "「A... ưm——Soutetsu, này——」"
997 = "「A... Sàn nhà, các thứ——phải dọn dẹp, thôi.」"
999 = "「Á... ngón tay——cọ cọ, này——ưm——hà, âm đạo——như đang bị——trêu chọc——khi cọ xát——vậy.」"
1000 = "「A... Soutetsu, này——nhé—— trực tiếp... ngực đi anh.」"
1001 = "「A... Soutetsu, này——Soutetsu.」"
1002 = "「A.」"
1003 = "「Khà!」"
1004 = "「!!?」"
1006 = "「Liếm——ưm——chụt——chùn chụt.」"
1007 = "「Ưm——」"
1008 = "「Ưm... phù——á——a.」"
1009 = "「Ưm... a——Soutetsu... tay anh, lớn quá—— ưm——」"
1010 = "「Vâng... vâng. Em cởi... cởi đây.」"
1013 = "「Thế này... Nhìn thấy đồng phục ở một nơi không phải chỗ làm việc, phải nói sao nhỉ——có cảm giác rất cuốn hút đấy.」"
1014 = "「Vâng. Em cũng... muốn anh làm vậy. Âm đạo tè dầm này... em muốn, Soutetsu bịt nó lại.」"
1017 = "「Ừm. Anh cũng không nắm bắt được thời cơ, nên rốt cuộc lại phải hỏi thẳng thừng thế này đây.」"
1018 = "「À——」"
1019 = "「Ưm hyu! Á——ưm fuuuuu——」"
1020 = "「Ưm!!?」"
1021 = "「Ưm hyuuuuuuuuuuuuuu!!!」"
1022 = "「Ưm hyuuuuuun!!」"
1023 = "「Ưm hyuuuuuun!」"
1025 = "「Ưm yu! Á——âm——vật... ưm—— đừng có... mân, mê... mà.」"
1026 = "「Ưm hyu!?」"
1027 = "「Hửm?」"
1028 = "「Ufufu, nếu vậy. Anh có muốn nhìn kỹ hơn nữa không?」"
1031 = "「T, tại anh ấn... vào——Soutetsu, này—— Rượu vang, em... bởi vì——cứ thế, thay đồ luôn.」"
1036 = "「Cảm ơn vì bữa ăn. Thật sự rất ngon đấy.」"
1040 = "「Em ấy bảo anh hỏi khéo Paulette xem. Có dự định thay đổi thiết kế đồng phục hay không.」"
1042 = "「T, tiện dụng...」"
1044 = "「Tuyệt——sướng——sướng, quá anh ơi——ưm—— núm vú... ngực... sắp tan chảy, mất rồi——」"
1046 = "「Xin——xin lỗi anh——Soutetsu——ưm.」"
1048 = "「Sao vậy? Paulette.」"
1051 = "「Để anh làm cho. Paulette đi tắm rồi thay đồ đi.」"
1054 = "「Phải cẩn thận lau cho thật sạch mới được.」"
1055 = "「Anh nghĩ vậy, nhưng dữ kiện đánh giá vẫn chưa đủ. Anh nghĩ cũng nên kiểm tra cả độ bền nữa.」"
1059 = "「Anh biết, mà——nên là—— lần này——nhất định——cùng, nhau——」"
1060 = "「Đã cất công hỏi thế này, anh nghĩ Hibiki có quen biết nhà thiết kế nào đó. Nếu được, chúng ta thử triển khai chuyện này xem sao nhé?」"
1061 = "「Em nghĩ là xem thực tế rồi để Soutetsu cân nhắc xem có nên thay đổi hay không thì sẽ tốt hơn.」"
1064 = "「Nhờ chuyện gì ạ?」"
1069 = "「Hibiki vốn không thích làm giống chị Mayami... Nhưng riêng món thịt hầm khoai tây thì lại có vị giống nhau đến mức chẳng thể phân biệt được.」"
1070 = "「Thay đổi đồng phục...」"
1071 = "「Không sao. Thế này lại càng dễ lau sạch hơn.」"
1072 = "「Không sao đâu. Anh sẽ lau sạch ngay đây.」"
1073 = "「À không, anh chợt nhớ ra. Hibiki có nhờ anh một chuyện.」"
1074 = "「Không——」"
1082 = "「Paulette. Thay vì lau sạch, anh muốn dùng nút bịt—— bịt kín âm đạo của em lại.」"
1083 = "「Paulette.」"
1084 = "「Paulette. Đứng dậy được không? Vào nhà vệ sinh nhé.」"
1086 = "「Dùng loại rượu vang đã mở nắp một thời gian, hầm cùng thịt bò và các loại rau gia vị. Cơ bản chỉ có vậy thôi ạ.」"
1087 = "「Có vẻ, là vậy nhỉ.」"
1089 = "「Tóm lại là cởi đồ ra đã. Cứ để ướt thế này, nhỡ cảm lạnh thì nguy.」"
1096 = "「Ngực... khác quá... ưm——so với tự mình, làm, thì—— phù, á... tay của, Soutetsu——sướng, hơn——á.」"
1101 = "「Xấu hổ quá... em, trong bộ dạng... thế này...」"
1111 = "「Bộ đồng phục này... gợi dục đến mức này sao. Cho đến giờ, anh hoàn toàn không hề nhận ra đấy——」"
1112 = "「Thế này, là...」"
1113 = "「Đó quả là một câu hỏi khó để có thể hỏi khéo đấy nhỉ.」"
1114 = "「Đó là vì chúng ta là người yêu của nhau, và chỉ có hai người. Là do em đang quyến rũ Soutetsu đấy ạ.」"
1115 = "「Đây là món Bœuf Bourguignon, một món ăn gia đình của Pháp. Thịt bò hầm rượu vang đỏ, không dùng những phần thịt đắt tiền đâu ạ.」"
1116 = "「Vậy sao.」"
1119 = "「Vậy thì chắc em đã phải hầm rất cẩn thận nhỉ. Thịt mềm, thấm gia vị, cực kỳ ngon luôn.」"
1120 = "「À này! Em! Em cũng muốn—— học được hương vị đó. Món thịt hầm khoai tây của nhà Soutetsu.」"
1122 = "「Vậy thì cứ làm thế đi.」"
1123 = "「Anh thấy chứ? Trong gương ấy. Cái mũ có vướng víu không?」"
1127 = "「Anh không nghĩ mình hiểu biết về trang phục đâu. Nhưng mà——」"
1128 = "「Soutetsu... ưm.」"
1129 = "「Soutetsu? Đồng phục... tính sao đây? Có nên thay đổi thiết kế không anh?」"
1130 = "「Soutetsu? Có chuyện gì sao anh?」"
1132 = "「Là món thịt hầm khoai tây.」"
1133 = "「Thịt hầm khoai tây ạ.」"
1135 = "「~~~~~~~~!!!」"
1246 = "Mùi amoniac xộc vào mũi, cuối cùng chúng tôi cũng nhớ ra tình hình hiện tại."
1249 = "Không... Có lẽ đây đã là vị mật ngọt của Paulette rồi."
1251 = "Mật ngọt không ngừng tuôn trào, làm ướt sũng cả quanh miệng, lan xuống cằm và tận cổ họng tôi."
1253 = "Nhưng mà, đẹp lắm. Theo ý kiến cá nhân anh thì không cần phải bàn cãi, vô cùng xuất sắc."
1256 = "Có lẽ vì bị kìm nén, không được tiếp xúc với không khí, hay do thể chất của Paulette..."
1259 = "Nhưng tôi không thể dừng lại. Không thể nghỉ ngơi."
1272 = "Tăng thêm nhiệt lượng, áp lực và ma sát, tôi liên tục báo cho cô ấy biết tinh dịch của tôi đã đến đó rồi, hãy chuẩn bị sẵn sàng để đón nhận đi."
1282 = "Chỉ thấy nong nóng, hơi chát—— Nếu phải nói thì, nó mang một vị chua gần giống với vị đắng."
1283 = "Bầu ngực đáng yêu lộ ra."
1286 = "Có lẽ chiếc quần tất dày và quần lót, chỉ truyền tải được một cách mờ nhạt chuyển động của ngón tay."
1289 = "Khi tôi rời mặt ra và trở lại tư thế cũ, trên bàn, Paulette đã hoàn toàn tan chảy."
1290 = "Đồng thời với việc rẽ lớp thịt bám chặt để tiến vào, dương vật của tôi cũng cảm nhận được sức ép như thể đang bị lột ngược ra."
1293 = "Khi khoảnh khắc dữ dội qua đi, cảm giác tội lỗi vì đã thấy việc tè dầm này thật tuyệt lại dâng lên trong tôi."
1295 = "Cho đến khi Paulette hoặc tôi kiệt sức, triệt để, hết lần này đến lần khác, vô số lần."
1296 = "Khoảnh khắc chạm đến tận cùng, cổ tử cung liền mút chặt lấy đầu dương vật của tôi!"
1302 = "Đôi mắt có phần đờ đẫn dường như đã lấy lại được tiêu cự và ý thức."
1303 = "Mật ngọt, nhiều quá. Chiếc khăn tay thoáng chốc đã sũng nước."
1306 = "Động tác tay vô cùng tinh tế, nhưng lại dai dẳng và ướt át, cô ấy đang dạy tôi qua tấm gương xem cô ấy muốn được xoa bóp như thế nào."
1307 = "Khuôn miệng cứ há hốc ra, chiếc lưỡi đáng yêu thò ra ngoài, đẫm nước bọt."
1310 = "Đôi chân cô ấy giãy giụa, nhưng có vẻ như không hề có chút sức lực nào."
1312 = "Chiếc quần tất đã hoàn toàn đổi màu."
1314 = "Cơ thể thì cứng đờ, nhưng chỉ có âm đạo là co giật liên hồi——hả!?"
1315 = "Dễ thương quá. Thực sự rất dễ thương. Khi ý nghĩ ấy vừa lóe lên, tôi đã kéo cơ thể đang định ngồi dậy của cô ấy xuống."
1318 = "Cô ấy đã có thể kể về mẹ mình một cách tự nhiên đến thế."
1320 = "Chật chội. Nhỏ hẹp. Trơn tuột."
1326 = "Đúng vậy. Paulette đã dạy cho tôi biết. Rằng con gái luôn ý thức được ánh nhìn của người mình thích."
1330 = "Cảm giác như dương vật đã chọc đến tận cổ họng, ép cô ấy phải thở hắt ra vậy——"
1332 = "Chỉ một chút nữa——một chút xíu nữa thôi là ra rồi, bỏ mặc tôi, Paulette đã run rẩy bần bật từng cơn."
1338 = "Nước tiểu có vị mặn. Theo kiến thức, hay đúng hơn là định kiến thì là vậy, nhưng——"
1344 = "Khoái cảm quá mạnh khiến tôi theo phản xạ rụt hông lại, làm toàn bộ dương vật bị những nếp gấp miết ngược một cách thô ráp."
1347 = "Đáng tiếc là tôi đã không thể kế thừa hương vị của gia đình ruột thịt... Nhưng nếu hỏi tôi thích món nào nhất trong hương vị nhà Migita, thì câu trả lời đã quá rõ ràng."
1356 = "Vừa nắn bóp, tôi vừa dùng khớp ngón tay nhẹ nhàng miết lên núm vú."
1358 = "Tôi bất giác rụt tay lại. Không phải vì tôi thấy nước tiểu bẩn thỉu gì đâu——"
1363 = "Da thịt và cơ thể của cả hai hô ứng lẫn nhau, phần sâu thẳm nhất gọi mời nhau, quấn quýt lấy nhau."
1364 = "Phần kết nối sủi bọt."
1366 = "Tôi nhấp hông liên hồi, xoay tròn, miết và dùi đầu dương vật vào cổ tử cung."
1367 = "Nếu chỉ đứng nhìn thì tôi không thể chịu đựng nổi."
1369 = "Nếu cứ để mặc em ấy, nếu không đỡ lấy, em ấy sẽ khóc mất."
1370 = "Tôi rút chiếc khăn tay từ trong túi ra, rồi thấm đẫm nước bọt."
1371 = "Khi tôi liếm từ tóc xuống cằm, Paulette liền quay mặt lại."
1373 = "Khung cảnh mà tôi \"muốn xem\", đang dần trở thành hiện thực."
1374 = "Chỉ với một cử động ngón tay thật nhẹ nhàng, cơ thể Paulette đã giật nảy lên đầy thú vị."
1377 = "Tôi ngăn bàn tay đang định cử động của cô ấy lại, và tự mình cởi từng chiếc cúc áo trước ngực Paulette."
1379 = "Cởi bỏ chiếc quần tất và quần lót ướt sũng dính chặt vào người, Paulette lại một lần nữa ngồi lên người tôi."
1381 = "Tôi thử ép phần hạ bộ đang cương cứng của mình vào mông Paulette."
1383 = "Khi tôi nhẹ nhàng áp vào lối vào, Paulette liền cựa quậy lắc mông, khao khát tôi."
1385 = "Tôi bế thốc Paulette lên, rồi đặt cô ấy nằm gập người trên chiếc bàn viết nhỏ."
1386 = "Tôi di chuyển dương vật như muốn khoét sâu vào âm đạo đang co thắt."
1389 = "Màn vuốt ve bắt chước đó ngay lập tức khiến cơ thể Paulette run rẩy từng hồi."
1390 = "Thúc mạnh vào cổ tử cung, đôi mắt đờ đẫn của cô ấy cuối cùng cũng lóe lên tia sáng của ý thức."
1392 = "Tôi dùng chiếc khăn tay cẩn thận lau chùi, làm sạch âm đạo đang bóng nhẫy vì nước tiểu và mật ngọt."
1395 = "Tôi dùng bánh mì baguette vét nốt chút nước sốt còn sót lại trên đĩa rồi bỏ tọt vào bụng."
1397 = "Tôi không cởi chiếc cúc dưới cùng, và dĩ nhiên vẫn giữ nguyên chiếc cà vạt. Sau đó tôi kéo tuột áo lót của cô ấy xuống——"
1399 = "Cảm giác tội lỗi bị cuốn trôi. Dục vọng hiện rõ đã định hướng cho tôi."
1400 = "Thấy rất rõ."
1401 = "Thúc vào, thúc vào, không hề nới lỏng để xuất tinh. Thúc vào, thúc vào, chỉ một mực thúc sâu vào trong."
1404 = "Muốn trút tinh dịch vào tử cung, muốn xuất tinh, muốn nhuộm đẫm Paulette bằng màu sắc của tôi, trong đầu tôi giờ chỉ còn duy nhất suy nghĩ đó."
1405 = "Tôi thử nhấn nhẹ vào, và trong giọng nói của Paulette xen lẫn sự vui sướng rõ rệt."
1406 = "Thành thật với trái tim và cơ thể mình, tôi vùi mặt vào mái tóc của Paulette."
1409 = "Phủ lên cơ thể đang rã rời, tôi trao cô ấy một nụ hôn ướt át, cuồng nhiệt."
1412 = "Mặc nguyên cả áo sơ mi lẫn áo lót, tôi đặt tay lên như để nâng đỡ bầu ngực của cô ấy——"
1413 = "Thế nên, việc vô tình nhìn thấy quần lót—— Không phải là vô tình, mà thực chất là cô ấy đang \"cho xem\"."
1416 = "Nếu vậy, lúc này đây. Không còn cách nào khác ngoài việc tôi phải là người dẫn dắt."
1424 = "Sau đó, cô ấy khẽ lắc mông, như muốn báo cho tôi biết rằng cô ấy đã cảm nhận được sự cương cứng của tôi."
1427 = "Nếu em đã muốn thế, thì anh sẽ chiều ý."
1429 = "Nếu đã vậy thì... Nhắm vào phần nhạy cảm nhất——"
1430 = "Nếu là một sự quyến rũ ngọt ngào đến thế này, thì ngoài việc bị dụ dỗ ra, tôi chẳng thể làm gì khác."
1433 = "Nếu em ấy đã cảm nhận mãnh liệt đến thế này thì——"
1442 = "Có lẽ đã vượt quá giới hạn thấm hút mất rồi."
1469 = "Vừa thoăn thoắt dọn dẹp chiếc đĩa trống trơn, Paulette vừa cất giọng vui tươi."
1470 = "Paulette không nhắm mắt lại. Trái lại, cô ấy còn đang chằm chằm nhìn chính mình trong gương."
1471 = "Bàn tay của Paulette cũng bắt đầu mềm mại xoa bóp ngực mình từ dưới lên."
1472 = "Đó là tiếng thở dốc, đúng hơn là tiếng kêu."
1473 = "Paulette thở ra một hơi nóng hổi——"
1474 = "Paulette thở hổn hển, dốc từng ngụm khí lớn. Khoái cảm xuất tinh, đỉnh điểm mạnh mẽ đến mức vắt kiệt mọi hơi thở."
1475 = "Từ lượng nước tiểu còn sót lại của Paulette, hầu như không cảm nhận được chút vị mặn nào."
1476 = "Paulette lẩm bẩm nhắc lại như vẹt, rồi bật cười khúc khích như thể thấy chuyện gì đó buồn cười lắm."
1477 = "Paulette từ nãy đến giờ vẫn luôn tươi cười rạng rỡ."
1478 = "Paulette vội vã biến mất vào căn phòng bên cạnh."
1479 = "Cất lên tiếng rên rỉ không thành lời, Paulette lại run lên bần bật."
1480 = "Tử cung của Paulette lại bắt đầu mút mát. Lần này, tôi sẽ không trốn tránh. Không rụt hông lại."
1481 = "Đôi má Paulette đỏ bừng lên."
1482 = "Nước mắt lưng tròng, Paulette đã hoàn toàn kiệt sức."
1483 = "Khuôn mặt và âm đạo của Paulette đều tan chảy, chỉ còn biết để nước dãi chảy ròng ròng."
1484 = "Tôi tưởng âm đạo của Paulette hẹp lại, hoặc cũng có thể do tôi đang cương cứng hơn bình thường."
1485 = "Đột nhiên, cơ thể Paulette cứng đờ lại."
1486 = "Paulette run rẩy cả người, rồi chậm rãi chớp mắt."
1487 = "Trên trán Paulette, những giọt mồ hôi khác hẳn với lúc nãy ứa ra đầm đìa."
1488 = "Cơ thể Paulette nóng dần lên, những phần da thịt chạm vào nhau trở nên ẩm ướt, đẫm mồ hôi."
1489 = "Khuôn mặt Paulette nhanh chóng giãn ra. Cô ấy gật đầu đáp lại đầy vui sướng."
1490 = "Khịt khịt mũi ngửi mùi trên người mình, cô ấy nhíu chặt mày lại."
1491 = "Mật ngọt rỉ ra từ âm đạo của Paulette, tràn qua quần lót, và bắt đầu chảy dọc từ quần tất xuống đùi."
1494 = "Để cả hai cùng lúc tận hưởng khoái cảm xuất tinh tuyệt vời nhất, tôi chỉ biết đâm hông vào, đâm sâu hơn nữa——"
1495 = "Cả bầu ngực lấp ló sau lớp áo sơ mi được tôn lên bởi chiếc cà vạt, lẫn chiếc quần lót lấp ló sau lớp quần tất."
1498 = "Rồi cô ấy từ từ chống tay ngồi dậy—— được một nửa, Paulette lại nhìn chằm chằm vào tôi."
1499 = "Hướng về phía cặp mông đang chĩa vào tôi——"
1508 = "Tôi cảm nhận được rằng Paulette đã hoàn toàn vượt qua được bức tường lớn đó, và thấy thật vui."
1514 = "Tinh dịch dâng trào lên cùng một lúc, tôi có thể tự mình cảm nhận được dương vật đang căng phồng lên."
1525 = "Một chút nước tiểu còn đọng lại giữa hai cánh môi bằng thịt bắn ra ngoài."
1533 = "Tiếng áo quần cọ xát... Thế này chẳng lẽ là——"
1535 = "Vượt qua lớp lưới của quần tất, cơn mưa vàng óng róc rách trút xuống sàn nhà."
1541 = "Nếu vậy thì, lời nói hay dọn dẹp thế là đủ rồi. Từ giờ trở đi, cứ làm theo những gì cả hai mong muốn——"
1548 = "Kết quả là tinh dịch bắn ra với lực mạnh chưa từng thấy, đập vào bức tường sâu thẳm của Paulette, gọi mời sự co giật của vách thịt âm đạo——"
1549 = "Một nụ hôn hòa quyện đầu lưỡi vào nhau."
1550 = "Lần này, tôi thọc sâu ngón giữa vào trong âm đạo."
1552 = "Nếu vậy, hãy tiếp tục bài kiểm tra nào."
1556 = "Phía bên kia tấm gương, từ đũng quần đến hai đùi của Paulette, vết ướt đang loang ra một cách mãnh liệt."
1564 = "Cơn mưa chẳng mấy chốc đã tạnh, và rồi vết ướt trên quần tất lại từ từ, từ từ loang rộng thêm một chút."
1565 = "Chiếc cà vạt trở thành một điểm nhấn mang tính biểu tượng, làm nổi bật vẻ trắng ngần của làn da và sự căng tròn của bầu ngực một cách đầy khiêu gợi."
1624 = "（Co giật!）"
1627 = "（Múúúúúúúúút!!）"
1628 = "（Cạch!）"
1630 = "（Bốp）"
1631 = "（Phập——phụtttt）"
1632 = "（Phập! Phập! Chát! Phập!!）"
1634 = "（Phụt! Phụt! Phụt! Phụt!）"
1636 = "（Phụt! Phụt! Phụt! Phụt!）"
1639 = "（Chuúúúút——ực——liếm——liếm——）"
1640 = "（Chụt!?）"
1641 = "（Hửm?）"
1642 = "（Rào rào rào rào rào）"
1643 = "（Phập phậpppppp——phập!!）"
1644 = "（Phập!!!!）"
1645 = "（Nhóp nhép）"
1649 = "（Phụt——phụt——phụttt! Phụt!）"
1650 = "（Phụt! Phụt! Phụttt——phụt）"
1651 = "（Phụt! Phụt!!!!）"
1653 = "（Bật ra）"
1655 = "（Anh đâu có định trêu chọc em đâu.）"
1657 = "（Nắn nắn——nắn bóp——nắn——nắn nắn——）"
1658 = "（Nắn nắn!）"
1660 = "（Đút vào）"
1661 = "（Xoa——miết——miết——nhóp nhép）"
1663 = "（Nhẹ nhàng——xoa xoa）"
1666 = "（Xột xoạt）"
1667 = "（Cọ xát）"
1668 = "（Sờ nhẹ）"
1669 = "（Cọ——miết——nhóp nhép——chùn chụt）"
1671 = "（Nhấc lên——）"
1672 = "（Rào rào rào rào rào）"
1674 = "（Nghiêng người）"
1675 = "（Rỉ ra——）"
1676 = "（Tí tách!）"
1679 = "（Siết chặtttttt!!）"
1680 = "（Thúc mạạnnnnh!!!）"
1681 = "（Phập——phụt——miết——nhóp nhép——）"
1682 = "（Hự——hựựựựự——）"
1684 = "（Phập——phập——hự——phụt!）"
1687 = "（Vạch ra）"
1688 = "（Ấn——ấn ấn——）"
1690 = "（Nhấn nhẹ）"
1693 = "（Thế này——sao?）"
1694 = "（Ấn vào——）"
1695 = "（Siết chặt!）"
1696 = "（Đâm phập!）"

[selections]
