# ポーレットh4_クリーム＆クリーム.txt

[info]

[characters]
1099 = "Paulette"
1177 = "Soutetsu"
1178 = "Soutetsu H"

[character_subs]
1367 = "Paulette"
1470 = "Soutetsu"

[script]
678 = "——Trao thêm một nụ hôn nữa."
687 = "……Không, hay là. Có lẽ Paulette đã chuẩn bị tâm lý\\ncho việc quan hệ lỗ hậu đầy đủ rồi cũng nên."
689 = "……Với một Paulette đang hoàn toàn động dục,\\ndường như ngay cả dòng nước cũng trở thành kích thích tình dục."
691 = "……Trong vòng tay tôi, người tôi yêu\\nđã chìm vào giấc ngủ say sưa."
699 = "……Quả thật, cái này ẩm ướt trơn tuột rất sướng.\\nNếu đút vào trong tình trạng này thì——Vừa nghĩ vậy tôi đã hành động luôn!"
702 = "「……Anh muốn——anh muốn——Paulette」"
851 = "「Mưa rào……ưm……tuyệt, quá——\\nNóng, quá——anh ơi——」"
853 = "「Không, là do anh đột nhiên gọi em ra mà.\\nAnh mới phải xin lỗi, giờ này rồi còn……」"
856 = "「Không, có vẻ như dạo này bà ấy hay thức khuya.\\nNên bà ấy bảo buồn ngủ quá.」"
859 = "「Cái gì?! Hả!? V, vẫn còn——\\nNkyu! Phù——a——a——ưm hya!」"
863 = "「Em ra phòng thay đồ nghỉ ngơi một chút đi.\\nNgủ thiếp đi cũng không sao đâu.」"
866 = "「Hachiroku đâu rồi anh?」"
870 = "「Đằng nào thì cũng phải dọn dẹp toàn bộ.\\nNếu vậy, nhân cơ hội này thử sức với lỗ hậu thì——」"
871 = "「Hya——hà——a——em cho, anh——ưm——\\nCho anh, hết——a——toàn, bộ——toàn bộ」"
873 = "「Hya——a——cô bé——đến rồi——\\nTinh dịch——nóng quá——nóng quá——ưm hya!?」"
876 = "「Hí——a——mông——ưm——của em——\\nMông——đang bị liếm——anh Soutetsu, a」"
878 = "「Hyafu——ưm——a——ahi——ưn!」"
879 = "「Á——ưm——lỏng——ra mất, rồi——\\nEm——mông——bị làm cho lỏng, ra——phù」"
880 = "「Hyaaa」"
881 = "「Kyafuuuuuuuuuuuu!!!」"
882 = "「Kyafua!?」"
883 = "「Hyan!」"
884 = "「Nkyu!!」"
885 = "「Á!?」"
887 = "「Hyaau!? Ưm——a——\\nThế này——ưm——sướng——quá!」"
889 = "「Í!? Ưm——a——vào rồi——\\nƯ——lưỡi——lưỡi——lưỡi」"
891 = "「Hya!? Tử cung——ưm——bị ấn, vào——rồi」"
892 = "「Ư——hự——」"
893 = "「Ư——á!?」"
894 = "「Hự!」"
895 = "「Hà——a——ưm——ưm」"
896 = "「Phù——ưm——ưm——ưm——\\nƯ——phù——phù——ư ư ư ư ư ư～～!!!」"
897 = "「Hà——sâu quá——anh ơi——ưm——bụng——\\nDương, vật——chạm vào——chạm vào mất」"
899 = "「Hà——này——Soutetsu——anh Soutetsu!\\nRửa đi——chỗ này——cả chỗ này nữa——bằng vòi sen……đi anh」"
901 = "「Hà……a——funya——」"
902 = "「Ư——」"
903 = "「Phuyan——a——ưm——hí——ưm!」"
904 = "「Hà——a——ưm——phù——\\nMông——ưm——lỗ hậu——đang——」"
906 = "「Phù——a——Paulette——\\nAnh thích em——Anh yêu em——Yêu em nhiều lắm.」"
908 = "「Hà——a——bị ngoáy sâu——phù——\\nCô bé——đang——bị nong ra——bị lộn ra——ưm」"
910 = "「Phù——vui quá——ưm——anh Soutetsu——\\nThích anh——thích anh——thích anh——thích anh lắm——」"
911 = "「Phuyaaaaaaaaaa!!」"
912 = "「Hya! Phù——ưm——ưm ư ư ư ư ư!」"
914 = "「Fuhya——anh Houhehu——\\nEm, hạnh phúh quá……nên hỉu mấh rồi」"
915 = "「Phù!? A——mưa rào——tinh dịch——ưm\\n——Tinh dịch, như mưa rào——phụt phụt, tuôn, trào」"
917 = "「Hả? Chìa khóa sao——\\nChủ nhân Tororyu-yu có chuyện gì sao anh?」"
919 = "「Ồ.」"
920 = "「À, vậy thì tốt rồi.」"
921 = "「Ư——ưm」"
922 = "「Hửm」"
923 = "「A——」"
926 = "「Á——á——bằng mông——ưm——\\nAnh Soutetsu——em——bằng lỗ hậu——!」"
928 = "「A——a——mưa rào——ưm——\\nCủa anh Soutetsu——tinh dịch——như mưa rào, a——」"
930 = "「A——ngoạm——ưm——chụt——chu——\\nchụt——ưm——phù——chụt」"
932 = "「～——ưm! Ưm——chụt——chụtttt——\\nƯm——phù——liếm——liếm——liếmmmm」"
934 = "「A——nóng——quá——ưm——phù——\\nTo, thế——mà——lại trơn——tuột」"
936 = "「A——tay——tay của anh Soutetsu——ưm——\\nTrơn trượt——quá——to, quá——a」"
937 = "「A——anh Soutetsu——phù——ưm——chuyện đó——\\nNửa thân, trên……ưm——ngực, nữa——」"
939 = "「A……ưm——hà……Tự mình——\\nTắm……hoàn toàn——khác, biệt——」"
940 = "「A——」"
941 = "「っ!」"
943 = "「A! Anh Soutetsu.」"
945 = "「Chụt——chu——chụt——ưm——phù——\\nNên là——hãy cho em——em——cho em——」"
947 = "「Chụt——chu——chụtttt——chu——\\nPhù——ưm——liếm——chụtttt——chụt」"
949 = "「Này——Paulette, Paulette!?」"
950 = "「Ưm——phù——a——a!」"
951 = "「Ư——hự——」"
952 = "「Nkyu——a——phù——ưm——\\nLỗ hậu——mông——bên trong——bị ngoáy——ưm」"
954 = "「——Ưm, hự」"
956 = "「Vâng——anh Soutetsu.」"
957 = "「Ưm……a——này——anh Soutetsu」"
959 = "「Ồ.」"
960 = "「Ưm ááá——mút. Không——ưm——\\nLỗ hậu, của em——đừng, mút, mà」"
961 = "「Ưm hya——á——ưm ư ư ư ư ư ư!!?」"
963 = "「Ưm——á——hả!? Hôn——ưm——\\nAnh Soutetsu——đang——phù——vào lỗ hậu, của em」"
965 = "「Ưm a! Hya——ngực——trơn tuột, mất——」"
967 = "「V-vâng. Tất nhiên rồi, em rất hoan nghênh.」"
969 = "「Tuyệt——quá——thế này——ưm——a,\\nCô bé——đang——hí——đầy——đầy ứ」"
970 = "「Vâng ạ……anh Houhehu……funya」"
972 = "「Xin lỗi anh. Em để anh đợi lâu rồi nhỉ.」"
973 = "「Là tinh dịch của anh——không gì khác.」"
975 = "「Anh Soutetsu cứ làm theo ý thích——\\nĐược anh tắm cho……em vui lắm.」"
977 = "「Gần đúng rồi đó anh Soutetsu.\\nĐó là kem dưỡng da mặt loại cấp ẩm đấy.」"
979 = "「Làm gì có chuyện đó.」"
981 = "「Em cũng đoán chừng là vậy nên——\\nỪm, anh xem thử giỏ đồ tắm của em được không?」"
982 = "「Em——toàn, bộ——cho anh, hết——nên là——\\nƯm——nhé——anh Soutetsu——anh Soutetsu」"
984 = "「Anh để em ấy về trước rồi. Với lại, chuyện là thế này——」"
986 = "「Nếu đã thoa lên mặt được thì……\\nỪm, em nghĩ là——bên trong cơ thể, chắc cũng không sao đâu.」"
989 = "「Ừ. Bà ấy bảo chỉ cần dọn dẹp sạch sẽ, khóa cửa cẩn thận,\\nvà trả chìa khóa vào sáng mai là có thể dùng tùy thích.」"
991 = "「Cái này——dùng để làm gì nhỉ.」"
992 = "「Không, không sao đâu ạ.\\nBình thường giờ này em vẫn còn thức mà.」"
993 = "「Đúng không anh!\\nThực sự là một sân khấu hoàn hảo luôn.」"
998 = "「Paulette——Anh cũng——anh cũng, sắp rồi!」"
999 = "「Paulet...te」"
1003 = "「Tinh, dịch——em bé——ưm——\\nCủa anh——Soutetsu——em bé——xin hãy cho em!」"
1005 = "「Chất lỏng tiến vào bên trong cô bé của Paulette——」"
1008 = "「Ra——mất——a——a——a——\\nPhù————A a a a a a a a a a a!!!」"
1010 = "「Đừng——cho em nghỉ——hí——phù——\\nCô bé, nóng quá——sắp bỏng——mất rồi」"
1012 = "「Bên trong……Ra là vậy.\\nThoa vào lỗ hậu, dùng làm chất bôi trơn chứ gì.」"
1018 = "「Thế này cũng đủ dùng rồi.\\nNhưng, trước khi thoa kem——」"
1019 = "「Đây là……gì vậy? Kem dưỡng da tay à?」"
1020 = "「Được tự do sử dụng một bồn tắm rộng thế này\\nsuốt cả đêm, tuyệt thật đấy nhỉ.」"
1021 = "「Nên thả lỏng cơ thể trước đã.\\nCho phép anh tắm cho em nhé?」"
1023 = "「Vậy, anh Soutetsu……\\nGọi em đến là để phụ dọn dẹp sao?」"
1025 = "「Ừm thì, hình như cũng có loại chuyên dụng cho việc đó.\\nNhưng mà em——không tài nào——bấm mua trên mạng được.」"
1030 = "「～～～～～～～～～!!」"
1133 = "Không chỉ vậy, cô ấy còn tựa vai vào tôi.\\nLàn da ướt đẫm nước nóng và mồ hôi dính vào nhau thật dễ chịu."
1137 = "Nhưng——"
1140 = "Nhưng, dục vọng vẫn lấn át tất cả.\\nMọi thứ trong tôi chỉ một mực khao khát Paulette."
1141 = "Nhưng không dữ dội như lần đút ngón tay vào trước đó.\\nCó lẽ màn âu yếm cũng đã làm cho lỗ hậu giãn ra phần nào."
1143 = "Và nhờ sự trống rỗng đó,\\ntôi lại cảm thấy mãn nguyện vô bờ bến."
1145 = "Nhưng ngay lập tức, phần cửa miệng bị siết chặt lại.\\nPhản ứng mạnh hơn cả lúc dùng ngón tay hay dùng lưỡi."
1166 = "Mới chỉ cọ bằng miếng bọt biển thôi,\\nmà Paulette đã phát ra âm thanh như đang động dục."
1170 = "Hơn nữa lớp kem lại quá sền sệt——"
1172 = "Âm đạo vốn chỉ run rẩy bám víu sau khi lên đỉnh, giờ lại bắt đầu ngọ nguậy."
1183 = "Cô bé và lỗ hậu cũng rung lên thật dễ thương,\\nchỉ vậy thôi cũng đủ kích thích khiến dương vật của tôi giật nảy."
1189 = "Ùn ùn, xối xả.\\nToàn bộ tinh dịch của tôi tuôn ra, cạn kiệt."
1191 = "Trong khi để tử cung và dương vật hôn nhau,\\nđôi môi chúng tôi lại tạo ra khoái cảm còn mãnh liệt hơn thế."
1192 = "Chừng nào tôi còn đứng vững để nâng đỡ,\\nPaulette có thể hoàn toàn yên tâm mà lả đi."
1194 = "Cú siết chặt và cơn run rẩy ngọt ngào mà mãnh liệt ngay khi vừa đút vào,\\nkhiến dương vật vốn đã nhạy cảm không thể chịu đựng nổi mà xuất tinh. Nhưng——"
1197 = "Chắc là do hoàn cảnh.\\nNó khiến tôi liên tưởng đến tinh dịch——"
1198 = "Làm chuyện đó trong phòng tắm có vẻ quá hao tổn sức lực,\\ntôi đành nén sự tiếc nuối, nói lời tạm biệt với trò chơi bọt biển."
1204 = "Không phải là cự tuyệt, mà là siết chặt để không cho trốn thoát."
1207 = "Em bảo anh cứ tắm theo ý thích——\\nCuối cùng tôi cũng hiểu được giá trị của câu nói ấy."
1208 = "Chiếc giỏ nhỏ màu hồng đan lưới.\\nTrong đó có dầu gội, miếng bọt biển tắm và——"
1211 = "Thật đáng yêu, thật không thể kìm lòng được.\\nNên tôi lén lút, cẩn thận để không đánh thức cô ấy——"
1212 = "Cô ấy cử động chiếc lưỡi run rẩy, liếm lưỡi, nướu và khắp vòm miệng,\\ntruyền cho tôi vô vàn nước bọt và tình yêu thương."
1214 = "Đôi mắt ướt át.\\nCơ thể mềm mại ngả vào người tôi."
1216 = "Bụng cô ấy co giật một cách khó coi,\\nnhưng cô ấy vẫn cố gắng hết sức để khơi gợi khoái cảm trong tôi."
1219 = "Cú siết chặt cùng lúc lên đỉnh quá mạnh,\\nkhi tôi vừa kéo hông lại thì theo đà tuột ra hết."
1222 = "Nếu phải tắm cả nửa thân trên,\\nchỉ dùng hai tay thì e là kém hiệu quả quá."
1226 = "Không dừng lại được. Không thể dừng lại. Thậm chí tôi còn chẳng có ý định dừng lại."
1247 = "Hạnh phúc đến lú lẫn cả đầu óc.\\nTôi cũng suýt nữa thì bị như vậy."
1254 = "Vừa lên đỉnh, đôi mắt đẫm lệ hoàn toàn,\\nnhưng Paulette vẫn tuyệt vọng âu yếm bên trong khoang miệng tôi."
1259 = "Cảm giác chinh phục và khao khát chiếm hữu phình to,\\nkhiến tôi muốn lấp đầy tất cả bằng chính bản thân mình."
1262 = "Thứ đang bị lộn ra là dương vật cương cứng của tôi mới đúng."
1263 = "Mặc kệ, tôi kéo hông lại thật mạnh."
1266 = "Tôi cũng đang rất khổ sở.\\nCảm giác như phổi đã cạn kiệt không khí, cơ bắp thì nóng ran, đau nhức và trĩu nặng."
1270 = "Vẫn duy trì sự kết nối, chúng tôi lại trao nhau nụ hôn."
1271 = "Chúng tôi xác nhận điều đó qua tình dục.\\nVà rồi, thề ước với nhau qua nụ hôn."
1273 = "Chuyển động. Cử động được rồi. Thật dễ chịu.\\nTôi tha hồ đào sâu vào bên trong hậu môn."
1276 = "Khối thịt tuyệt hảo mang tên Paulette,\\nđược bao bọc bởi sự trượt đi của toàn bộ cơ quan sinh dục trên cơ thể tôi."
1277 = "Nếu báo trước, Paulette sẽ cảnh giác mất.\\nNếu vậy, cách duy nhất tôi nên làm là."
1280 = "Tôi xoa xà phòng ra tay, vừa nắn bóp vừa tạo bọt cọ xát."
1282 = "Chất dịch trắng đục bắn ra từ tôi\\ndính chặt lên người Paulette, làm vấy bẩn cô ấy."
1284 = "Dùng hông nhấp từng nhịp nhỏ, từng nhịp nhỏ,\\ncọ xát và ấn vào điểm nhạy cảm, Paulette lại run lên bần bật."
1285 = "Tay trái không ngừng ngoáy bên trong lỗ hậu,\\ncòn tay phải thì xoa kem lên dương vật cương cứng."
1287 = "Từ đầu đến chân,\\nkhông chỉ là vùng nhạy cảm, mà dường như đã biến thành cơ quan sinh dục mất rồi."
1289 = "Tôi muốn hòa tan cùng Paulette,\\nmuốn mọi thứ sụp đổ, hòa quyện làm một!"
1291 = "Từ từ cọ rửa phần mông,\\ncô bé và lỗ hậu lại rung lên mời gọi tôi."
1293 = "Vặn nắp ra xem thử bên trong,\\nquả thực là có lớp kem trắng trông rất mọng nước."
1294 = "Tôi xoa xà phòng tạo bọt khắp cơ thể mình,\\nbiến toàn thân thành một miếng bọt biển——"
1296 = "Rút ngón tay ra, đẩy dương vật vào lỗ hậu,\\ncó lẽ nhờ lớp kem mà nó tiến vào trơn tru hơn tôi tưởng——"
1299 = "Bị thu hút, tôi xịt vòi hoa sen vào núm vú, vào lỗ hậu,\\nhơi thở của Paulette càng lúc càng gấp gáp và dâm đãng hơn."
1301 = "Khi tôi mạnh mẽ rút lưỡi ra,\\nphát ra một tiếng 'Bóp!' thật vui tai."
1302 = "Lấy một lượng kem bằng hai đốt ngón tay——"
1303 = "——Mỗi lần thoa vào sâu trong lỗ hậu,\\ntôi lại có cảm giác như đang nhuộm Paulette bằng chính mình."
1307 = "Mỗi lần tôi kéo hông, phần thịt âm đạo bám víu nũng nịu\\nlại dính chặt vào rãnh quy đầu, kích thích đến mức như muốn lộn ngược nó ra."
1309 = "Tôi cho sữa tắm vào miếng bọt biển hình con vật,\\nthấm nước, vò nhẹ tạo bọt."
1311 = "Như sụp đổ, như thèm khát\\nTôi ép sát cơ thể và trao nụ hôn."
1314 = "Tôi muốn trút toàn bộ tinh dịch trong tinh hoàn\\nvào tử cung Paulette không sót một giọt."
1315 = "Với vòi hoa sen——\\nTôi cảm thấy ghen tị."
1317 = "Không nói ra nhưng tôi báo hiệu cho em ấy có thể ra,\\nlỗ hậu môn lập tức co rút mạnh mẽ."
1318 = "Khi tôi di chuyển thật chậm và rộng,\\ndù cố kìm nén, những âm thanh kỳ lạ vẫn tự động bật ra khỏi cổ họng."
1321 = "Tôi cảm nhận được Paulette cũng có chung suy nghĩ ấy."
1322 = "Trao nhau những nụ hôn khao khát. Hôn. Hôn. Hôn."
1323 = "Bọt phủ kín toàn thân tôi,\\ntrượt dọc trên khắp cơ thể Paulette."
1324 = "Xoay cô ấy về phía này, rồi một hơi,\\ntôi nhấc bổng toàn bộ cơ thể Paulette lên."
1328 = "Ngâm mình trong bồn tắm."
1330 = "Tôi vội vàng dùng vòi hoa sen thật,\\nxả sạch cơ thể Paulette."
1332 = "Thế nên tôi dội nước ấm từ chậu tắm,\\nưu tiên rửa sạch bọt ở những điểm quan trọng."
1334 = "Quả thật là 'trơn' và 'tuột'.\\nDù tiến sâu vào lỗ hậu cũng không cảm nhận được nếp gấp thịt nào."
1368 = "Vừa nói,\\nPaulette vừa ngó nghiêng nhìn quanh quất."
1369 = "Toàn thân cô ấy co giật bần bật, nước mắt nước dãi giàn giụa."
1370 = "Dang rộng hai chân, gập người xuống,\\ncô ấy nhìn tôi qua khe hở giữa hai đùi."
1371 = "Khi Paulette thốt lên,\\nđiều đó tạo ra một chút không gian nới lỏng."
1372 = "Paulette đang ngập ngụa trong bọt xà phòng một cách hoàn hảo."
1373 = "Dù đã rã rời, cô ấy vẫn thốt lên tiếng kêu sung sướng."
1374 = "Bày ra dáng vẻ khêu gợi thế này trước mặt tôi,\\nmà Paulette lại đỏ mặt ngượng ngùng vì một chuyện thật kỳ lạ."
1375 = "Paulette biết tỏng rồi mà còn cố tình hỏi.\\nGiọng nói nũng nịu rót vào tai khiến dục vọng trong tôi dâng trào."
1376 = "Ngón tay Paulette vạch rộng cô bé ra cho tôi thấy.\\nNgay lập tức, máu nóng dồn lên não tôi."
1377 = "Mông Paulette run bần bật.\\nHậu môn thắt chặt lại."
1378 = "Cơ thể Paulette thoáng chốc cứng đờ.\\nĐầu khẽ lắc nguầy nguậy."
1379 = "Khuôn mặt đang hơi căng ra của Paulette giãn ra mềm mại."
1380 = "Toàn thân bị tôi ôm trọn, cơ thể gần như không thể cử động tự do,\\nnhưng Paulette vẫn ráng di chuyển hông."
1381 = "Cơ thể Paulette khẽ đung đưa."
1385 = "Cả cô bé lẫn lỗ hậu mà tôi cố tình không chạm vào để tránh bị xót,\\ngiờ cũng đã bị bọt che khuất."
1389 = "Sau đó, cô ấy quỳ gối xuống khu vực tắm rửa——"
1390 = "Nhưng——\\nKhông cần phải nhịn đâu."
1393 = "Dù vậy, âm đạo và tử cung vẫn tham lam\\nngọ nguậy không ngừng, như muốn vắt kiệt tinh dịch của tôi."
1395 = "Dù vậy, Paulette không hề có vẻ gì là căng thẳng.\\nCô ấy duỗi tay duỗi chân, ngay cả lời nói cũng thong thả."
1399 = "Khối thịt mềm mại hễ nắm lấy là tràn ra, nhưng giờ tôi không thể nắm trọn được.\\nTrơn quá, đến cả núm vú cũng trượt khỏi đầu ngón tay tôi."
1407 = "Sẽ trở thành cha.\\nSẽ trở thành mẹ."
1410 = "Kem dưỡng da mặt màu trắng, ẩm ướt."
1423 = "Và khi tôi gục ngã,\\nchắc chắn Paulette sẽ là người nâng đỡ tôi."
1424 = "Nghe tiếng gọi, tôi vẫy tay lại,\\nPaulette nở nụ cười, chạy bước nhỏ lại gần."
1430 = "Kể từ lần đầu tiên chạm môi,\\nchúng tôi đã hôn nhau không biết bao nhiêu lần."
1433 = "Bên trong lỗ hậu không hề có mùi vị kinh khủng như tôi sợ——\\nChỉ cảm thấy mùi vị hệt như đang liếm da thịt mềm mại mà thôi."
1436 = "Tinh dịch đặc sệt cũng trào ra từ hậu môn,\\nnhỏ giọt xuống như thể đang nhắm thẳng vào cô bé."
1437 = "Thắt lại, nhưng không cắn chặt."
1440 = "Lỗ hậu, cô bé, hai núm vú——\\nChỉ cần nhấn mạnh những điểm đó thôi cũng đủ thấy dâm đãng đến không ngờ."
1442 = "——Rõ ràng là đang bị siết chặt, vậy mà lại trơn tuột.\\nCảm giác như không có điểm dừng, có thể đi sâu đến vô tận."
1444 = "Tận dụng tối đa cảm giác dính chặt đầy đặn,\\nâm đạo uốn éo quấn lấy, ôm chặt dương vật của tôi từ mọi hướng."
1460 = "Đó là sự dịu dàng vô bờ bến.\\nLà tình yêu thương không chút tiếc nuối."
1461 = "Không phải là sự cự tuyệt mãnh liệt, mà giống như đang khao khát khoái cảm hơn,\\nnhư một hành động nũng nịu."
1462 = "Có lẽ vì xấu hổ, Paulette đỏ mặt,\\nlắc đầu, lắc mông nguây nguẩy."
1463 = "Cứ thế này thì, tôi sẽ xuất tinh mất.\\nCả Paulette chắc cũng sẽ lên đỉnh không biết bao nhiêu lần."
1464 = "Bọt trơn tuột khiến tôi không thể nắm chặt như mọi khi,\\nthật sốt ruột, thật dâm đãng, cảm giác thực sự rất tuyệt."
1465 = "Nghĩ lại thì,\\nđây là lần đầu tiên tôi và Paulette ở riêng bên nhau thế này."
1466 = "Mèo……hay là chồn hương gì đây nhỉ?"
1467 = "Cảm giác sốt ruột lại mang đến sự dễ chịu.\\nBằng cách trêu chọc lẫn nhau, chúng tôi đang chuẩn bị cho sự kết nối."
1468 = "Tinh dịch bắn cả lên tóc cô ấy mất rồi.\\nCảm giác tội lỗi lấn át cả cảm giác chinh phục lẫn cảm giác thành tựu."
1469 = "Lời tôi còn chưa dứt, Paulette đã đáp lời\\nvà nhanh chóng bước ra khỏi bồn tắm."
1473 = "Bên trong đã vơi đi khá nhiều,\\nchắc hẳn là món đồ cô ấy vẫn thường xuyên sử dụng."
1481 = "Trước tiên, cứ bình thường từ eo lên lưng——"
1482 = "Với cơ thể đã nhũn ra như bùn, với hơi thở đứt quãng thoi thóp,\\nPaulette vẫn đáp lời tôi."
1562 = "（Cọ xát——nắn bóp——）"
1564 = "（Nhưng……nụ hôn này, cũng là nụ hôn đầu tiên.）"
1565 = "（Hử）"
1566 = "（Chà——vò——）"
1567 = "（Siết! Siếtttt!!）"
1568 = "（Cọ xát）"
1570 = "（Tùm）"
1572 = "（Ưm）"
1573 = "（Tí tách……a——）"
1575 = "（Phập! Rút! Nhóp nhép! Phập!!!）"
1576 = "（Chụt——）"
1579 = "（Chu——chụt——chụt——chụtttt）"
1580 = "（Phập! Nhóp! Phập! Nhép!）"
1581 = "（Chụt）"
1583 = "（À——phải rồi）"
1584 = "（Rào rào rào rào）"
1587 = "（Phập! Phập! Phụt! Phụt!!）"
1588 = "（Phụt! Phụt! Phụtttt! Phụt!）"
1590 = "（Phụtttt! Phụt!）"
1592 = "（Phụt! Phụt! Phụtttt! Phụt!）"
1593 = "（Bôi trơn）"
1594 = "（Nắn bóp——trơn tuột——xoa nắn——chụt）"
1596 = "（Siếtttttt!）"
1598 = "（Mở ra）"
1600 = "（Tách ra!）"
1602 = "（Ngoáy!）"
1603 = "（Nhấc bổng!!）"
1604 = "（Rút ra!）"
1605 = "（Nắn nắn——trơn tuột——cọ xát——xoa bóp——）"
1607 = "（Nắn bóp! ——Trơn tuột!）"
1608 = "（Ngoáy——nắn——trơn tuột——trơn tuột）"
1609 = "（Phập!!!!）"
1610 = "（Nắn bóp——xoa nắn——）"
1612 = "（Siết——siếtttt!）"
1615 = "（Lả đi）"
1617 = "（Phậppppppp!!!）"
1618 = "（Trơn tuộtttttt——）"
1620 = "（Trơn tuộtttt）"
1622 = "（Cứ như thế, chúng tôi——\\nchắc chắn sẽ trở thành cha mẹ, sẽ trở thành một gia đình.）"
1623 = "（Hự! Dập! Ngoáy! Ngoáyyy!）"
1624 = "（Liếmmmmm）"
1627 = "（Siết! Siếtttttt!!）"
1632 = "（Cái này……thì——sướng quá——\\nĐến mức——đầu óc——cũng nổi bọt——mất thôi——）"
1633 = "（Không ổn rồi）"
1634 = "（Đây là——nụ hôn thề ước mới.）"
1635 = "（Thế này thì——vào được chưa nhỉ?）"
1636 = "（Áp sát）"
1637 = "（Phập! Nhóp! Phập! Ngoáy!）"
1638 = "（Ngoáyyyyyyy!!）"

[selections]
