# ポーレット12_解放.txt 
[info]

[characters]
1294 = "双鉄"
1225 = "ポーレット"

[character_subs]
1515 = "雙鐵"
1441 = "波萊特"

[script]
# lines: 197 
# 【双鉄】
# display as 雙鐵
# JP: 「ん？」
1013 = "「唔？」" 

# monologue
# JP: 流れが止まる。
1313 = "四周安靜了下來。" 

# monologue
# JP: 悲しく歌うようだった、\nそぼふる雨のようだった――音の流れが。
1510 = "那宛若悲歌一般的聲音，宛若淅瀝雨點一般的聲音——停了下來。" 

# 【ポーレット】
# display as 波萊特
# JP: 「うん……わかった」
1019 = "「嗯……我知道了」" 

# monologue
# JP: 音が、変わる。日ノ本語に。\n僕にわかる音――言葉へと。
1332 = "她的聲音變了，變成了日語。我聽得懂的語言。" 

# 【ポーレット】
# display as 波萊特
# JP: 「……ママと話せて――聞かせてもらえてうれしかった。\nすぐにじゃないかもしれないけど、また電話すると思う」
847 = "「……能和媽媽說上話，我真的很開心。雖然可能不是最近，不過我會再給媽媽打電話的」" 

# monologue
# JP: ならば、聞かせてくれている。\nポーレットは僕に、自分の気持ちを。
1512 = "那就代表著，她願意讓我聽懂她此刻的心情。" 

# monologue
# JP: フランク語で交わし合っていた奔流のような会話の果て、\n行き着いた場所が、どこであるかを。
1520 = "願意讓我聽到她和她母親用法語交流所得出的結果。" 

# 【ポーレット】
# display as 波萊特
# JP: 「そう、だね。うん――大丈夫だよ？　それじゃあ、また。\nあ！　あとね、ママ……ううん、おかあさん」
1088 = "「是……啊。嗯——我沒事的。那先掛了。啊！　那個，媽媽……不，媽」" 

# monologue
# JP: 沈黙。長い――あまりに長い。\n端で聞いてる僕がどんどん不安になるほど……っ！？
1337 = "她突然陷入了長時間的沉默，長得就連在旁邊聽她打電話的我都有些擔心……！？" 

# monologue
# JP: （いや――まて、僕）
1525 = "（不——等等）" 

# monologue
# JP: 日ノ本語への切り替え＝僕にも聞かせてくれるため、と\n勝手に思い込んでしまっていたが。
1336 = "她突然換成了日語，也許並不是想讓我聽懂。" 

# monologue
# JP: よく考えれば、これは単なる立ち聞きなのでは――
1262 = "仔細想想，我這會不會只是在偷聽——" 

# 【ポーレット】
# display as 波萊特
# JP: 「パパと結婚してくれて――\nわたしのおかあさんになってくれて、ありがとう」
1135 = "「謝謝你願意和爸爸結婚——願意成為我的媽媽」" 

# monologue
# JP: （ああ……）
1528 = "（啊……）" 

# monologue
# JP: 立ち聞きではない。\nポーレットは、やはり伝えてくれていたのだ。
1502 = "這不是我單方面的偷聽。波萊特果然是希望我能聽到。" 

# monologue
# JP: 自らを縛り続けてきた過去の戒めを、\n鮮やかに振りほどく、その一言を。
1478 = "聽到她說出那堅定的一言，來擺脫一直以來束縛著自己的過去。" 

# 【ポーレット】
# display as 波萊特
# JP: 「…………ふぅ」
827 = "「…………呼」" 

# monologue
# JP: 疲れきっているようにも聞こえ、\n満足しきったようにも聞こえる、長い息。
1341 = "她長舒了一口氣，聽起來十分疲憊，但同時也很滿足。" 

# monologue
# JP: そうして足音――\nポーレットがこちらへと近づいてくる。
1252 = "之後是腳步聲——波萊特在向我這邊走來。" 

# 【ポーレット】
# display as 波萊特
# JP: 「ありがとうございます。居てくれて」
1134 = "「謝謝你。願意陪在我身旁」" 

# 【双鉄】
# display as 雙鐵
# JP: 「いや、何――」
958 = "「不，我什麼也——」" 

# monologue
# JP: “電話をするから、居て欲しい”
815 = "“我想要打電話，請陪在我身旁”——" 

# monologue
# JP: 宮本さんから受け取った電話番号を伝えた僕に、\nポーレットが頼んだのはただ、それだけだった。
1394 = "我將從宮本女士那裡拿到的電話號碼告訴波萊特之後，她只提出了這一個請求。" 

# 【双鉄】
# display as 雙鐵
# JP: 「僕など……本当に居ただけだ」
1072 = "「我真的只是……就站在那裡而已」" 

# 【ポーレット】
# display as 波萊特
# JP: 「居てくれるのが、嬉しいんです」
1160 = "「雙鐵君願意陪在我身邊，只是這樣就讓我很高興」" 

# monologue
# JP: おっとり微笑み、ポーレットは目を、壁の時計へと向ける。\n日付が変わって、二時間以上が経過している。
1450 = "波萊特靜靜地笑著，看了看牆上的時鐘。時間已經過了午夜，波萊特打了兩個小時多的電話。" 

# monologue
# JP: 宮司達はとうに帰った。僕らの結論に従うとただ言い残し。\n奮戦むなしく、れいなも睡魔に打ち負かされた。
1351 = "宮司他們後來表示會尊重我們的決定，然後就早早回去了。玲奈雖然與睡魔苦戰了一番，但最終還是敗下陣來。" 

# 【ポーレット】
# display as 波萊特
# JP: 「長電話にも程がある、って話ですよね」
1044 = "「就算是煲電話粥也沒這麼久的呢」" 

# 【双鉄】
# display as 雙鐵
# JP: 「いや――むしろ短かったんじゃないか？」
951 = "「不——不如說時間還算比較短吧？」" 

# 【ポーレット】
# display as 波萊特
# JP: 「え？」
1011 = "「哎！？」" 

# 【双鉄】
# display as 雙鐵
# JP: 「つのる話を考えればさ。\n何年ぶりかなのだろう？　[おやこ,1]母娘の会話は」
975 = "「你們母女之間不是有很多年沒聊過了嗎？　一定有很多想說的吧」" 

# 【ポーレット】
# display as 波萊特
# JP: 「あー……そうですね」
1016 = "「啊……是啊」" 

# monologue
# JP: くったりと、\nポーレットは椅子に体を預けきる。
1444 = "波萊特有些無力地坐到椅子上。" 

# 【ポーレット】
# display as 波萊特
# JP: 「……まともな会話は――ほんと、何年ぶりでしょう？\nパパとこじれてからの間は……ママ、完全にパニックで」
836 = "「……上次像這樣好好談談，是有多少年了呢？自從和爸爸鬧彆扭以來……媽媽就完全陷入了神經過敏的狀態」" 

# monologue
# JP: 話していいか？　とポーレットは目で問うてくる。\nもちろん、僕に否やは無い。
1447 = "波萊特用眼神詢問我是否願意聽她娓娓道來。而我自然不會拒絕。" 

# monologue
# JP: 少しだけ待てと緑茶を淹れて、\nじっくりと聞く体勢を整え、腰をかけ直す。
1411 = "我讓她稍等一會，起身泡好綠茶，做好了傾聽的準備後，重新坐回座位。" 

# 【ポーレット】
# display as 波萊特
# JP: 「ありがとうございます」
1136 = "「謝謝你！」" 

# monologue
# JP: ゆるやかに、ポーレットは緑茶を喉へと落とし、\n長く熱っぽい息を吐く。
1443 = "波萊特姿勢優雅，喝了一口綠茶，長長吐出一口氣。" 

# 【ポーレット】
# display as 波萊特
# JP: 「あったかいです。おいしい――\nわたし、喉カラカラだったんですね」
997 = "「又溫暖又好喝——我自己都沒發現原來我都這麼渴了」" 

# 【双鉄】
# display as 雙鐵
# JP: 「だろうな」
1069 = "「我想也是」" 

# monologue
# JP: 意味がわからぬフランク語を聴き続けてただけの僕さえ、\nいつの間にか喉がカラカラだ。
1387 = "我只是在旁邊聽著完全聽不懂的法語，都不知不覺間覺得有些渴了。" 

# monologue
# JP: 喜怒哀楽、声の調子が変わる度、内容を想像してしまい\n――手にはじっとり、ねばつく汗さえ握ってしまった。
1428 = "每當她改變語調，我都會不禁地想像她們談話的內容——聽得我手心都攥出了汗。" 

# 【ポーレット】
# display as 波萊特
# JP: 「わたしの両親、事業をやってたんです。\n個人輸入の代行業で――上手くまわってたみたいです」
1071 = "「我的父母原本有自己的事業。也就是代購——原本很順利的」" 

# monologue
# JP: 社員を雇い事務所を増やし、受注は右肩上がりを続け――\nその好循環を崩したのは、ほんの小さなきっかけだった。
1508 = "還雇了員工，開了多家辦事處，訂單也是越來越多——而打破這良性循環的，只是一個小小的轉機。" 

# 【ポーレット】
# display as 波萊特
# JP: 「\x%lエアクラ;#00ffc040;エアクラ%l;#;工場誘致の話が御一夜にあるって聞いて――\nそれでパパ、反対運動に協力することにしたんです」
1121 = "「爸爸聽說\\x%lエアクラ;#00ffc040;空凝機%l;#;工廠要在御一夜落戶，就表示要去參與反對運動」" 

# monologue
# JP: 誘致の声が活発化する前に撤回させる――\nその考えは、しかし上手くは運ばなかった。
1446 = "波萊特父親原本的打算是在支持落戶的聲音還不強烈之前阻止它，但並沒有成功。" 

# monologue
# JP: 宝生元忠――隈元銀行が、\n誘致運動の後押しを開始したからだ。
1315 = "因為寶生元忠——也就是隈元銀行開始了推進工廠落戶的行動。" 

# 【ポーレット】
# display as 波萊特
# JP: 「最初はお仕事の片手間に、って感じの手伝いだったのに、\n日が経つごとに、どっちが片手間かわからなくなって」
992 = "「原本爸爸只是利用工作的空閒時間來做這件事，但是過了一段日子，原本的工作卻反倒是變成了空閒時間才做的」" 

# monologue
# JP: 苦い思い出ではないのだろうか？
1504 = "這應該是痛苦的回憶才對吧？" 

# monologue
# JP: あきれたようなポーレットの声は、\nむしろ優しい響きを帯びている。
1455 = "然而波萊特有些無奈的語調中，卻帶有一點溫柔。" 

# 【ポーレット】
# display as 波萊特
# JP: 「賭け事って、わたししたことが無いんですけど――\nきっと、ああいう感じにハマっちゃうんだと思います」
1076 = "「我雖然沒有賭博過——不過我想，爸爸當時的心情一定和賭徒差不多」" 

# monologue
# JP: 最初は、本当に気軽に手を出し――\nけれども徐々に、積み重ねたものが膨らんでいく。
1291 = "原本是抱著就試一試的心情，結果卻漸漸陷了進去。" 

# monologue
# JP: いつの間にかそれは途方も無い量になり、\n完全に引込みのつかない場所に立っている自分に気付く。
1472 = "等回過神來，發現自己已經陷入了完全無法脫身的泥潭。" 

# 【ポーレット】
# display as 波萊特
# JP: 「市長選にパパが出るって決めて、会社が回らなくなって。\nママ――それで色々、限界に来ちゃったそうなんです」
1120 = "「爸爸決定競選市長，公司那邊就完全顧不上了。所以媽媽就忍耐不了了」" 

# monologue
# JP: 二人で分担していた負担が、自分ひとりにのしかかる。\n家事方面も追いつかなくなる。
1293 = "原本由兩人分擔的負擔完全落在了一個人身上，自然也沒辦法做家務。" 

# monologue
# JP: ポーレットの父はその対策に家政婦を雇い――\n結果的には、それが破綻の引き金となった。
1418 = "於是波萊特的父親決定請保姆——結果這件事就成了兩人決裂的導火線。" 

# 【ポーレット】
# display as 波萊特
# JP: 「すれ違いばっかりになって、ケンカが日常になって。\nパパとママは――疲れ果てて、離婚を選択したそうです」
984 = "「兩人完全無法達成共識，每天都在吵架。爸爸和媽媽在感情都被消磨掉之後，選擇了離婚」" 

# monologue
# JP: 他人ごとのような伝聞調。\n子供であったポーレットは、当然、当事者なのに――
1449 = "波萊特的語氣像是在講述和自己無關的事情。但當時還是個孩子的她，毫無疑問是當事人之一——" 

# monologue
# JP: （ああ、いや、“子供であった”からこそきっと……\n当事者なのに、事態に関与できなかったのか）
1527 = "（不，正因為當時的她“還是個孩子”……所以雖然是當事人，卻無法進行干預）" 

# monologue
# JP: 事態を解決したいのに、大事な人たちを助けたいのに、\n幼い自分はあまりに無力で、何ひとつさえできなくて――
1422 = "明明想幫忙解決問題，想幫助她最愛的人。可年幼的她卻是那麼無力，連一件事都無法做到——" 

# monologue
# JP: その苦しみは、僕も知ってる。痛みは未だに無くせない。\nなのに今、ポーレットの声は暗さを感じさせない。
1408 = "我能理解這份痛苦。它至今還深藏於我心底。但現在波萊特的聲音卻並不顯得陰暗。" 

# 【ポーレット】
# display as 波萊特
# JP: 「わたしにも選択を迫られました。でも、選べなかった。\nパパかママかなんて、選べるわけが無いじゃないですか」
1049 = "「很快我也面臨選擇。但是，我並沒有選。跟爸爸走還是跟媽媽走，根本沒有辦法選呀」" 

# 【双鉄】
# display as 雙鐵
# JP: 「うん」
1022 = "「嗯」" 

# 【ポーレット】
# display as 波萊特
# JP: 「選べないから黙ってました。頑張っていい子にしてたら\nパパとママ、仲良しに戻ってくれるかもって、思って」
1031 = "「因為做不出選擇，所以只能沉默。我一直以為只要自己當個好孩子，爸爸和媽媽就會和好如初，回到我身邊」" 

# 【双鉄】
# display as 雙鐵
# JP: 「……うん」
841 = "「……嗯」" 

# 【ポーレット】
# display as 波萊特
# JP: 「そしたら、ママは出て行きました。\nわたしを置いて出て行って――二度と帰ってこなかった」
1115 = "「然後媽媽就一個人走了。丟下我——再也沒有回來」" 

# monologue
# JP: 淡々とした声だからこそ、\nまざまざ、形が見える気がする。
1506 = "通過她平淡的口吻，我似乎終於觸碰到了整件事的核心。" 

# monologue
# JP: これが――ポーレットの傷で。\nだから、あれほどの無理をするようになったのだろう。
1503 = "這就是波萊特的心理陰影。所以她才變得那麼愛勉強自己。" 

# 【ポーレット】
# display as 波萊特
# JP: 「いい子にするのが足りなかったって。\nわたしがもっと頑張れたらって……だから、思って」
1087 = "「於是我覺得是自己“好孩子”的程度還不夠。要是我更努力的話……」" 

# 【双鉄】
# display as 雙鐵
# JP: 「それは違う」
1153 = "「那是不對的」" 

# monologue
# JP: 言わずもがなのことであろうと、\n話の邪魔になったとしても――言葉にせずにいられない。
1363 = "就算這是不言自明的道理，就算我這樣會打斷她——我也必須出言否定。" 

# 【双鉄】
# display as 雙鐵
# JP: 「ポーレットは、何も悪くない」
1112 = "「波萊特什麼都沒有做錯」" 

# 【ポーレット】
# display as 波萊特
# JP: 「ママも……そう言ってくれました」
1038 = "「媽媽她……也是這麼說的」" 

# 【双鉄】
# display as 雙鐵
# JP: 「っ！」
1161 = "「！」" 

# monologue
# JP: 美しい――\nただ、それだけしか思えない。
1317 = "太美了——這三個字占據了我的腦海。" 

# monologue
# JP: ポーレットの浮かべた笑みは、弱々しくて悲しげで。\nだけれど全てを――受け入れ、そして許してる。
1445 = "波萊特此刻的笑容既柔弱又充滿哀傷。但同時也接受、原諒了這一切。" 

# 【ポーレット】
# display as 波萊特
# JP: 「ママはただ、別れることになっても恨んでも。\nそれでも……パパを、やっぱり愛していたそうです」
1040 = "「媽媽就算和爸爸分開，就算心有記恨……她還是愛著爸爸的」" 

# 【双鉄】
# display as 雙鐵
# JP: 「愛して――？」
1054 = "「愛著？」" 

# 【ポーレット】
# display as 波萊特
# JP: 「愛してたから、一緒には居られなくなっても、\nパパのことを、見捨てるなんて出来なかった」
1105 = "「正是因為愛著，所以在分開之後，還是沒能拋棄爸爸」" 

# 【双鉄】
# display as 雙鐵
# JP: 「ああ……」
1017 = "「啊…」" 

# monologue
# JP: ポーレットの父、前市長、雛衣幸三氏。\n有能だと、その評価しか僕は知らぬが――
1395 = "我對波萊特父親——前市長雛衣幸三的了解，僅限於別人評價他是個優秀的市長。" 

# 【ポーレット】
# display as 波萊特
# JP: 「ママは、一人でもがんばれる人。でも、\nパパはきっと、一人じゃダメになっちゃう人だったから」
1039 = "「媽媽就算一個人也能活下去。但爸爸要是變成一個人，一定會一蹶不振的」" 

# 【双鉄】
# display as 雙鐵
# JP: 「……そういう形の、愛もあるのか」
838 = "「……也有這種形式的愛嗎」" 

# 【ポーレット】
# display as 波萊特
# JP: 「みたいですね」
1092 = "「是呀」" 

# monologue
# JP: 頷き。\nとても儚く感じる。
1345 = "她點了點頭，給人一種縹緲的感覺。" 

# 【ポーレット】
# display as 波萊特
# JP: 「けど――それってママは結局、\nわたしより、パパを選んだってことでもあるから」
969 = "「但——這也意味著媽媽比起我，還是選擇了爸爸」" 

# monologue
# JP: 言って、あはっと芝居がかった声。
1339 = "她說完這句話，故意笑了一聲。" 

# monologue
# JP: ポーレットの作る苦笑は、\nあまり上手に、笑えていない。
1271 = "但這聲苦笑——雖然有苦，卻並沒有笑。" 

# 【ポーレット】
# display as 波萊特
# JP: 「その話を聞いてもやっぱり、ちょっと寂しい気はします。\nでも、捨てられたんじゃなかったんだって、安心もして」
1133 = "「聽到她這麼說，我還是有一些落寞。不過同時也放心了，我並不是被她拋棄了」" 

# 【双鉄】
# display as 雙鐵
# JP: 「うん。ポーレットは、捨てられてなどいない」
1021 = "「嗯。波萊特才沒有被拋棄」" 

# monologue
# JP: ただ単に……\nポーレットのお母様も、力が足りなかっただけなのだ。
1303 = "只不過是因為……波萊特的母親也還不夠強大。" 

# monologue
# JP: 二人を同時に救いたくって、自分自身も限界で――\nだから、やむなく……そうすることを、強いられた。
1325 = "她希望能夠同時拯救父女二人，但自己也已經無法堅持下去了——所以只能選擇了這麼做。" 

# 【双鉄】
# display as 雙鐵
# JP: 「お母様もポーレットが大切で。かけがえないと感じてて。\nだからこそ――お父様から、奪えなかった」
1113 = "「波萊特的母親也非常重視波萊特，覺得你是不可或缺的。所以才沒辦法將波萊特從父親手中奪走」" 

# 【ポーレット】
# display as 波萊特
# JP: 「はい。わかります――けど」
1095 = "「是啊。我明白的——但是」" 

# monologue
# JP: ぎゅっと、瞳が閉じられる。\n涙は流れず――代わりのように、言葉が[こぼ]零れる。
1343 = "她閉上眼睛，卻沒有流下淚水——只有話語從口中斷斷續續地散落出來。" 

# 【ポーレット】
# display as 波萊特
# JP: 「……切ないですよね。こういうの。事情を聞いて、\nわかったつもりで、許しても――やっぱり切ない」
845 = "「……真是叫人難過呀。就算聽她解釋了原因，自己心裡也明白，就算寬恕了這一切——卻還是好無奈」" 

# 【双鉄】
# display as 雙鐵
# JP: 「ああ……」
1093 = "「是啊……」" 

# 【ポーレット】
# display as 波萊特
# JP: 「双鉄くんも――」
1158 = "「雙鐵君也——」" 

# 【双鉄】
# display as 雙鐵
# JP: 「ん？」
# 1013 = "「唔？」" 

# monologue
# JP: まぶたのカーテンが持ち上がる。\n青い瞳が、僕を見ている。
1334 = "她睜開眼睛，用藍色的眼睛注視著我。" 

# monologue
# JP: まっすぐ、まっすぐ――見つめてる。
1462 = "直直地、直直地——凝視著我。" 

# 【ポーレット】
# display as 波萊特
# JP: 「双鉄くんも知ってるんですよね。\nこの切なさを――やるせなさを」
1159 = "「雙鐵君也能理解吧。這種悲傷又無奈的心情」" 

# 【双鉄】
# display as 雙鐵
# JP: 「――うん」
823 = "「——嗯」" 

# monologue
# JP: 手が、伸びてくる。\nおずおずと、とても弱々しく。
1329 = "她朝我伸出手。那隻手畏畏縮縮的，看起來十分柔弱。" 

# monologue
# JP: 受け取れば、震えが伝わってくる。\nそれでもやはり、ポーレットのてのひらはあたたかい。
1399 = "我握住她的手，感到她在微微顫抖。即使如此，她的手心還是十分溫暖。" 

# 【ポーレット】
# display as 波萊特
# JP: 「あの日――わたし、すごく悲しかったんです」
1151 = "「那天——我真的非常悲傷」" 

# monologue
# JP: あの日が、どの日か。\n確かめる必要さえも感じない。
1403 = "我甚至不必詢問，究竟是哪一天。" 

# 【ポーレット】
# display as 波萊特
# JP: 「パパと二人の暮らしに少しずつ慣れてきて。\nママを、許せなく感じ始めていたころだったんです」
1149 = "「那個時候，我漸漸習慣了和爸爸的兩人生活，開始有些記恨起媽媽」" 

# 【双鉄】
# display as 雙鐵
# JP: 「わかる気がする」
1074 = "「我能懂」" 

# monologue
# JP: 喪失の衝撃は大きくて、あまりにも大きすぎるから。\nそれに慣れることの他、何一つさえできなくて――
1321 = "失去的痛苦太過強烈，實在是太過強烈。而除了慢慢去習慣以外，找不到其它任何出路——" 

# 【双鉄】
# display as 雙鐵
# JP: 「僕の場合も、そうだった。\n憎しみは、慣れたころ突然に、噴き出してきた」
1061 = "「我也是一樣。仇恨在逐漸習慣以後，突然爆發出來」" 

# 【ポーレット】
# display as 波萊特
# JP: 「ぶつけどころが見つからないと……\nだって、納得できないですから」
1032 = "「因為實在無法接受……所以必須找個發洩口」" 

# 【双鉄】
# display as 雙鐵
# JP: 「うん」
# 1022 = "「嗯」" 

# monologue
# JP: “誰が悪いわけではない”\n喪失があまりに大きいと、そんなことはとても思えない。
812 = "“並不是有人做錯了什麼”——當失去的痛苦過於強烈，我們便無法看清這一點。" 

# monologue
# JP: 生じてしまったどうしようも無い空白を――\n人はまず、憎しみで埋め始めるしか、きっとできない。
1261 = "人們總會最先想到——用仇恨來填補這片無能為力的空白。" 

# 【ポーレット】
# display as 波萊特
# JP: 「だから、双鉄くんに会って。事故の話を聞いて――」
1083 = "「所以，當年見到雙鐵君，聽你講了那場事故——」" 

# 【双鉄】
# display as 雙鐵
# JP: 「それでもポーレットは教えてくれたな。\n“鉄道に憎しみをぶつけることが間違ってる”と」
1132 = "「而波萊特你也告訴了我——把仇恨發洩給鐵路是錯誤的」" 

# monologue
# JP: 僕は、あの言葉に救われた。
1409 = "我被她的那句話救贖了。" 

# monologue
# JP: 悪いのは物ではなく、人。\n間違えるのは、いつだって、人と、教えてもらえて。
1424 = "是她教會我——會犯錯的從來不是物，而是人。" 

# 【ポーレット】
# display as 波萊特
# JP: 「それでわたし――双鉄くんに、\nきっと、救ってもらったんです」
1130 = "「而我當時一定——是被雙鐵君拯救了」" 

# 【双鉄】
# display as 雙鐵
# JP: 「え？」
1012 = "「哎？」" 

# monologue
# JP: 救われたのは、僕の方だ――\n言うより早く、ポーレットの声が流れ込んでくる。
1507 = "還沒等我說出“被拯救的是我”，波萊特就搶先說道。" 

# 【ポーレット】
# display as 波萊特
# JP: 「今考えると、きっと――あのときのわたしって、\n鉄道をかばいたかったわけじゃないんですよ」
1124 = "「現在想想，當時的我一定——並不是想要為鐵路脫罪」" 

# 【双鉄】
# display as 雙鐵
# JP: 「しかし、確かに――」
971 = "「但是，你確實說過——」" 

# 【ポーレット】
# display as 波萊特
# JP: 「鉄道をかばったんじゃなく。一緒に責めて欲しかった。\n双鉄くんに――やっぱり、悪いのは[ひと,1]人間なんだって」
1055 = "「我並不是想要為鐵路脫罪。而是希望雙鐵君跟我一起責備人類。想讓雙鐵君認為——錯的一直都是人類」" 

# 【双鉄】
# display as 雙鐵
# JP: 「っ！？　いや――僕は――」
1162 = "「！？　但是——我並沒有——」" 

# monologue
# JP: まるで、そんなことを思えなかった。\nだって、路子を殺したのは……ある意味やはり、僕だから。
1390 = "我完全沒有想到她還有這個意思。畢竟在某種意義上，路子就是我害死的。" 

# monologue
# JP: 僕がどこかで、別の判断をしていたのなら、\n路子も父さんも母さんも――きっと、死なずに済んだから。
1275 = "假如我在當時做出了別的判斷，路子和父親母親肯定就不會死了。" 

# 【ポーレット】
# display as 波萊特
# JP: 「なのにスって、双鉄くんの顔から暗いのが消えて。\nそれでわたし――ああ、出来るんだって、思ったんです」
1007 = "「可我卻看到雙鐵君臉上的陰霾一下子都消失了。於是我就發現——原來是可以做到的」" 

# 【双鉄】
# display as 雙鐵
# JP: 「出来る、って――何が」
1005 = "「可以做到——做到什麼」" 

# 【ポーレット】
# display as 波萊特
# JP: 「人を、許すことがです。\n双鉄くんの傷は、絶対、わたしのより深いのに」
976 = "「做到原諒人類。雙鐵君的傷口，絕對比我的要深得多」" 

# 【双鉄】
# display as 雙鐵
# JP: 「いや――僕は、許すも何も……\n憎める立場に無いと……きっと、思っただけだった」
953 = "「不——我沒什麼原諒不原諒的……我當時只是覺得，我根本沒有憎恨的資格」" 

# monologue
# JP: 素直に言えば、\nポーレットは驚いた顔になる。
1479 = "聽我這麼說，波萊特似乎很驚訝。" 

# 【ポーレット】
# display as 波萊特
# JP: 「そうなんですか？」
1097 = "「是這樣的嗎？」" 

# 【双鉄】
# display as 雙鐵
# JP: 「だって……人間は間違えるから。\n悪意が無くても――人は間違ってしまうから」
1030 = "「因為……人類是會犯錯的。就算沒有惡意——人類還是會犯錯」" 

# monologue
# JP: 僕自身がその最たるものであるというのに、\n自分を棚にあげるなど……
1402 = "我明明就是最典型的一個例子，又怎能對這樣的自己視而不見……" 

# monologue
# JP: そうできるほど、僕は図々しくなくて――\nあるいは単に、弱かったのだ。
1381 = "我並沒有厚顏無恥到，可以跳過自己去憎恨別人——或者，只是我太弱小了。" 

# 【双鉄】
# display as 雙鐵
# JP: 「だから――きっと、それは諦めに近かったと思う。\n憎み続けることを諦めて……結果として、楽になった」
1080 = "「所以我想——將那稱之為放棄比較妥當。放棄繼續憎恨下去……結果，使我得到了解放」" 

# 【ポーレット】
# display as 波萊特
# JP: 「そうだったんですか」
991 = "「原來是這樣啊」" 

# monologue
# JP: くすっと、ポーレットが笑う。
1442 = "波萊特噗嗤一聲笑了出來。" 

# monologue
# JP: バカな話とあきれたように。\nなのに、花開くように鮮やかに。
1359 = "就好像聽到一件愚蠢的事情一般。可是，卻笑得那麼燦爛。" 

# 【ポーレット】
# display as 波萊特
# JP: 「ならずっと、わたし、勘違いしてたんですね」
990 = "「原來我一直都誤會了」" 

# 【双鉄】
# display as 雙鐵
# JP: 「勘違いというのなら僕もだな。僕は――\n鉄道愛に満ちるがゆえの助言をもらったと思っていた」
1033 = "「如果要說誤會，我也是一樣。我一直以為你是因為太熱愛鐵路了，所以才會那麼說的」" 

# 【ポーレット】
# display as 波萊特
# JP: 「それも……多分、すこしは――結構？\nある程度あったとは思います。けど、やっぱり」
961 = "「也有一點……不，也有不少這方面的原因。不過最重要的還是——」" 

# 【双鉄】
# display as 雙鐵
# JP: 「やっぱり？」
1147 = "「還是？」" 

# 【ポーレット】
# display as 波萊特
# JP: 「わたしたち、ふたりとも勘違いしてたんですね。\n勘違いした想い出を、ずっと大事に抱えてた」
1065 = "「我們兩人一直都誤會了呀。還把這誤會當做珍貴的回憶，一直珍藏於心底」" 

# 【双鉄】
# display as 雙鐵
# JP: 「確かに……解釈は、勘違いだったかもしれない。\nけれど、抱え続けてきたことは――勘違いじゃない」
1126 = "「的確……我們腦海中的解釋可能都是誤會。不過，珍藏於心底這件事——並沒有錯」" 

# 【ポーレット】
# display as 波萊特
# JP: 「あ」
1018 = "「啊」" 

# monologue
# JP: ぽわっと。\nポーレットの手のひらがあたたかくなる。
1448 = "波萊特的掌心，忽然燙了起來。" 

# 【ポーレット】
# display as 波萊特
# JP: 「そうですね。\nわたしが、救われたことは本当」
1094 = "「是啊。我也真的是被你拯救了」" 

# 【双鉄】
# display as 雙鐵
# JP: 「そうなんだ。救われたから、勘違いでも、\n本物の大事な想い出となった。ああ――いや」
1042 = "「對啊。因為得到了救贖，所以即使是誤會，也仍然變成了珍貴的回憶。啊——不」" 

# monologue
# JP: むしろ……\nそうだ。言うなれば、むしろ――
1242 = "不如說……對了。不如說是——" 

# 【双鉄】
# display as 雙鐵
# JP: 「本当は、僕もポーレットも、“そうしたかった”。\nだからきっかけを、自分に都合よく、きっと捉えた」
955 = "「不如說當時的我和波萊特都“希望是這樣”。所以才會將這個契機曲解為對自己有利的解釋」" 

# 【ポーレット】
# display as 波萊特
# JP: 「あ――そっか」
1015 = "「啊——是這樣啊」" 

# monologue
# JP: あっさりした声。\nすっきりした声。
1464 = "短短的一句話，透露著她的釋然。" 

# monologue
# JP: ああ、やはり――僕らはともに、\nあの日、あの時。ただ気づいたのだ。
1307 = "啊，果然——我們兩人在那天，那個時候，只是突然醒悟了過來。" 

# 【ポーレット】
# display as 波萊特
# JP: 「わたしは、本当は最初から、\nママを憎みたくなんてなかった」
1067 = "「我其實從沒有想過要記恨媽媽」" 

# 【双鉄】
# display as 雙鐵
# JP: 「そうして僕も――\n憎しみなんて、抱き続けていたくはなかった」
1059 = "「我也一樣，不想一直心懷仇恨」" 

# 【ポーレット】
# display as 波萊特
# JP: 「だから、お互いにお互いを都合良く理解して……\nそうするきっかけにしちゃったんですね」
1078 = "「所以我們才把對方的話理解為自己想要的解釋……並創造了這個契機」" 

# monologue
# JP: そうなのかも、そうならいいな、と呟いて。\nポーレットは、力みの抜けきった顔で、微笑む。
817 = "“真希望是這樣呀”——波萊特這樣說著，露出一個放鬆的微笑。" 

# 【ポーレット】
# display as 波萊特
# JP: 「そういうの、きっと、相性ですよね」
1144 = "「這一定是因為我們倆很合得來」" 

# 【双鉄】
# display as 雙鐵
# JP: 「ああ。かもな。\nそれこそが、相性の善し悪しかもしれん」
1023 = "「嗯，也許是這樣吧。這種才叫合得來」" 

# monologue
# JP: 愛し合う者達を別れに追い込む行き違いも存在するし、\nお互いを救い合い、再会させる行き違いもある。
1248 = "世上既存在讓相愛之人別離的誤會，同時也存在讓人們互相拯救，再度相遇的誤會。" 

# monologue
# JP: 前者と後者にある隔たりは……運、でないなら、\n相性と呼ぶしかないものだろう。
1346 = "如果說這兩者之間的差異不在於運氣好壞……那就只能看兩人是否合得來了吧。" 

# 【ポーレット】
# display as 波萊特
# JP: 「出会った一番最初から――\nわたしたち、相性がすごく、よかったんですね」
1050 = "「從第一次見面開始——我們就很合得來」" 

# 【双鉄】
# display as 雙鐵
# JP: 「！」
# 1161 = "「！」" 

# monologue
# JP: 熱と鼓動が、\nポーレットの手から伝わってくる。
1241 = "一股熱流伴隨著心跳聲，透過波萊特的手傳遞給我。" 

# monologue
# JP: いや、それはもとから、\n僕の発したものかもしれない。
1246 = "不，或許這本來就來自於我。" 

# 【ポーレット】
# display as 波萊特
# JP: 「だから、居てくれて嬉しいんです。\nわたしのとなりに、双鉄くんが」
1084 = "「所以，雙鐵君願意陪在我身邊，我很高興」" 

# 【双鉄】
# display as 雙鐵
# JP: 「――っ」
822 = "「——」" 

# monologue
# JP: 何か、いいたいように思って、\nけれども言葉を出せはしないし、思いつけない。
1397 = "我想說些什麼，卻又說不出話，想不出詞語來形容我現在的心情。" 

# monologue
# JP: ただ、ポーレットの熱と鼓動と視線とに、\n僕の全てが埋められていく。
1389 = "我只是靜靜地感覺到波萊特的溫暖、心跳和視線逐漸將我淹沒。" 

# 【ポーレット】
# display as 波萊特
# JP: 「わたしのとなりに。\nわたしに恋を教えてくれた――双鉄くんが、居てくれて」
1086 = "「教會我愛情是什麼的雙鐵君——願意陪在我身邊」" 

# 【双鉄】
# display as 雙鐵
# JP: 「……ポーレット」
843 = "「……波萊特」" 

# monologue
# JP: 僕の全てが満たされて、喉から溢れだしていく。\nそれはただ――ひとつの大切な名前となって。
1406 = "我的全身心都被填滿，化作一個重要的名字從我的喉嚨口溢出。" 

# monologue
# JP: 僕の目の前にいる人の、\n僕と手を、つないでくれている人の。
1361 = "就是我眼前，與我牽手之人的名字。" 

# 【双鉄】
# display as 雙鐵
# JP: 「ポーレット」
1111 = "「波萊特」" 

# 【ポーレット】
# display as 波萊特
# JP: 「はい、双鉄くん」
1026 = "「嗯，雙鐵君」" 

# monologue
# JP: 憎しみで、自分を埋め尽くさなくて、よかった。
1367 = "幸好沒讓憎恨霸占我的全部。" 

# monologue
# JP: 代わりの何かを無理やり求め、\n自分を埋め尽くさなくて、よかった。
1365 = "幸好我沒有固執地尋找其它東西，來代替憎恨填滿自己。" 

# 【双鉄】
# display as 雙鐵
# JP: 「僕も――側にいてくれてうれしい。\nだから、側に居て欲しい」
1058 = "「我也一樣——很高興有你在我身邊。所以，我希望能繼續有你的陪伴」" 

# monologue
# JP: なくしたものは、決して再び戻らない。\n出来てしまった空白は、抱え続ける他にない。
1318 = "失去的人絕不會再回來。我只能懷抱著這片空白，繼續活下去。" 

# monologue
# JP: それでも、隣に、あたたかな人が居てくれる――\nそれだけで、僕はこんなにも満たされる。
1245 = "不過，我身邊還有著能夠溫暖我的人——只要她在我身邊，我的內心就會如此充盈。" 

# 【双鉄】
# display as 雙鐵
# JP: 「僕も……恋を教えてもらった」
973 = "「你也一樣……教會了我愛情是什麼」" 

# monologue
# JP: 資格が無いと思っていた。\n人を愛する、人の手を取る、資格を失くしたと思ってた。
1385 = "我原本以為自己沒有那個資格。沒有與相愛之人手牽手走下去的資格。" 

# monologue
# JP: だけれど、僕は失くしてなかった。\n路子は全てを守ってくれた――僕に、残してくれていた。
1268 = "但是，我並沒有失去那個資格。是路子保護了這一切——是她將這一切留給了我。" 

# 【双鉄】
# display as 雙鐵
# JP: 「君が、見えるようにしてくれた。\n僕は、こんなにも君を想って、あたたかになれる」
1090 = "「是你讓我明白了這些。原來我想著你的時候，能夠感受到這般的溫暖」" 

# monologue
# JP: 繋いでる手が熱くて熱くて、汗で濡れてて融け合うようで。
1286 = "兩人牽在一起的手是那麼炙熱，汗浸濕了雙手，彷彿融化在一起。" 

# monologue
# JP: その感触が、息苦しくて生々しくて――\nドキドキしすぎて、心地よくって。
1487 = "觸感是那麼真實，讓人有些難以呼吸——心跳得好快，卻又感覺很舒適。" 

# 【双鉄】
# display as 雙鐵
# JP: 「ポーレット。\n僕は、君に――恋をしている」
1110 = "「波萊特。我喜歡你」" 

# 【ポーレット】
# display as 波萊特
# JP: 「はい、双鉄くん。わたしもです」
1099 = "「是，雙鐵君。我也是」" 

# monologue
# JP: 手が、解かれる。
1327 = "她放開了我的手。" 

# monologue
# JP: 解かれた手は伸ばされて、\n僕の頬へとあてられる。
1514 = "隨後那雙手伸了過來，捧住我的臉頰。" 

# 【ポーレット】
# display as 波萊特
# JP: 「わたしも、あなたに。\n恋を――」
1063 = "「我也，喜歡上了你——」" 

# monologue
# JP: そこから先は、言葉にならない。
1323 = "她之後的話語被行動所淹沒。" 

# monologue
# JP: 僕らは、初めてのキスをする。
1383 = "我們第一次親吻在了一起。" 
