# ポーレット13_再評価.txt 
[info]

[characters]
1575 = "ポーレット"
1558 = "れいな"
1656 = "双鉄"
1889 = "議長"
1865 = "老議員"
1549 = "ふかみ"

[character_subs]
1791 = "波萊特"
1822 = "玲奈"
1925 = "雙鐵"

# 1889 = "議長"

# 1865 = "老議員"
1827 = "玲奈＆凪"
1800 = "深美"

[script]
# lines: 216 
# 【ポーレット】
# display as 波萊特
# JP: 「そうなんですか――はい！　ありがとうございます。\nはい――はい――わかりました。それでは、失礼します」
1401 = "「是這樣啊——好的！　謝謝您。好的好的，我知道了。那我先掛了」" 

# monologue
# JP: （プッ）
1952 = "（喀噠）" 

# 【ポーレット】
# display as 波萊特
# JP: 「ふぅ」
1293 = "「呼啊」" 

# monologue
# JP: “やんごとない”って、日ノ本語、\nニュアンスを、やっとつかめた気がする。
1737 = "我似乎終於明白了，什麼叫“與生俱來的高貴”。" 

# monologue
# JP: 電話越し、普通に、気さくにお話をしてもらってるのに、\nこっちの背筋を伸ばしてなくちゃいけないみたいで――
1768 = "明明只是一通普通的電話，對方的語氣也很平易近人，我卻忍不住要做到畢恭畢敬——" 

# 【れいな】
# display as 玲奈
# JP: 「むにゃあ」
# 1293 = "「呼啊」" 

# 【ポーレット】
# display as 波萊特
# JP: 「あ」
1305 = "「啊」" 

# monologue
# JP: 足音。ぽてぽて近づいてくる。\nまだ眠いのかな？　いつもよりもゆっくりしてる。
1826 = "玲奈發出啪嗒啪嗒的腳步聲向這邊走來。是還有些睏嗎？　她似乎走得比平時要慢。" 

# 【れいな】
# display as 玲奈
# JP: 「ふぁ……おはようございまぁす、ポーレット、\nこんな朝早くからお電話ですかぁ？」
1290 = "「呼啊……早安，波萊特。這麼一大早就在打電話嗎？」" 

# 【ポーレット】
# display as 波萊特
# JP: 「おはよう、れいな。\nごめんね？　電話で起こしちゃった？」
1390 = "「早安，玲奈。對不起哦。電話吵醒你了？」" 

# 【れいな】
# display as 玲奈
# JP: 「平気ですよぉ。\nお電話、だれからだったのですかぁ？」
1409 = "「沒有哦。是誰的電話呀？」" 

# 【ポーレット】
# display as 波萊特
# JP: 「うん、毛利の電車姫様から」
1312 = "「嗯，是毛利的電車公主」" 

# 【れいな】
# display as 玲奈
# JP: 「ふわ。\nお姫様は早起きさんなのですねぇ」
1292 = "「呼啊。公主殿下起得還真是早啊」" 

# monologue
# JP: 屈託の無いれいなの言葉に、\nくすくす笑いが湧いてくる。
1824 = "玲奈天真的話語逗笑了我。" 

# monologue
# JP: あのひとは、まさしく本物のお姫様。\n朝も夜中も、まるで気にしないっていう方でもあるから。
1915 = "那個人簡直就是真正的公主。而她打電話也完全不會顧忌是早上還是深夜。" 

# 【ポーレット】
# display as 波萊特
# JP: 「そうね、早起きさんね。\nでも、おかげでスッキリ起きられた」
1395 = "「是啊，起得好早。不過也多虧這一通電話，讓我完全清醒了」" 

# monologue
# JP: うん――本当に、目が覚めた。覚ましてもらえた。\nわたし、昨夜からずうっとふわふわしちゃってたんだ。
1688 = "嗯——真的是完全清醒了。被弄清醒了。從昨晚開始，我就一直感覺輕飄飄的。" 

# monologue
# JP: 双鉄くんに、やっと――恋を伝えることができたから。\n双鉄くんから――恋を、伝えてもらえたから。
1753 = "我終於向雙鐵君傳達出了自己的感情，而雙鐵君也回應了這份感情。" 

# 【れいな】
# display as 玲奈
# JP: 「ですねぇ、れいなもスッキリですよぉ！\nたぁくさん眠って、機関部駆動部絶好調――あ」
1391 = "「是呀，玲奈也完全清醒了！睡了好久，引擎和驅動部分都狀態良好——啊」" 

# 【ポーレット】
# display as 波萊特
# JP: 「えっ！？」
1301 = "「哎！？」" 

# monologue
# JP: やだ、もしかして、どこかに異常が――
1727 = "怎麼，難道說玲奈出什麼狀況了嗎——" 

# 【れいな】
# display as 玲奈
# JP: 「そうでしたぁ。あのですね、電車姫さまからのお電話、\nどんなお話だったんですかぁ？」
1330 = "「對了。那個呀，電車公主打電話來說什麼了？」" 

# 【ポーレット】
# display as 波萊特
# JP: 「ああ」
# 1305 = "「啊」" 

# monologue
# JP: ホっとする。\nっていうか、そうだ。
1755 = "我鬆了一口氣。啊，對了。" 

# monologue
# JP: この子の改修にも関わることだ。\nすぐに、伝えてあげなくちゃ。
1929 = "電話內容也與玲奈的改造有關，得趕快告訴她才行。" 

# 【ポーレット】
# display as 波萊特
# JP: 「あのね？　れいな……」
1436 = "「聽我說哦，玲奈……」" 

# 【双鉄】
# display as 雙鐵
# JP: 「ほう」
1313 = "「嚯」" 

# 【双鉄】
# display as 雙鐵
# JP: 「移送も全部、電車姫様がご手配くださったのか」
1482 = "「電車公主連運輸都包辦了嗎」" 

# 【ポーレット】
# display as 波萊特
# JP: 「はい。\x%lストーブ客車;#00ffc040;ストーブ客車%l;#;、明日にも御一夜に届くそうです。\nしかも、議案通過がならなくても、返却不要ってことで」
1397 = "「是的。\\x%lストーブ客車;#00ffc040;暖爐客車%l;#;明天就可以送到御一夜。而且她還說就算議會沒有通過議案，也不用把車廂送回來」" 

# 【双鉄】
# display as 雙鐵
# JP: 「――なんとも力強いご応援だな。\n議案がもしも通らなくても、諦めるなということだ」
1163 = "「——這可真是強力的支持啊。她是叫我們就算議案沒能通過也不要放棄呀」" 

# 【ポーレット】
# display as 波萊特
# JP: 「ですよね、やっぱり」
1370 = "「我想也是呢」" 

# monologue
# JP: 双鉄くんは、話が早い。\nいつもきっぱり、物事をすぐに定めてくれる。
1926 = "雙鐵君一直都理解得非常快。他總能抓住事物的重點。" 

# monologue
# JP: それが頼もしくて心強くて、\nだけれど今日は――ほんのちょっとだけ憎らしい。
1924 = "雖然非常可靠，但今天的他——卻讓我有點生氣。" 

# monologue
# JP: （この人ってば……\nなんでこんなに、いつもと同じなんだろう）
1961 = "（這個人……為什麼表現得跟平時一模一樣呀）" 

# monologue
# JP: わたしは、ふわふわまだしてるのに。
1770 = "明明我腦袋還有點輕飄飄的。" 

# monologue
# JP: 電車姫様に引き締められて、それでも顔を見た瞬間、\nもう全部、双鉄くんにふわふわ引き寄せられそうなのに。
1877 = "與電車公主打完電話，我好不容易變得嚴肅了些。但一看到雙鐵君的臉，就又變得輕飄飄的了。" 

# 【双鉄】
# display as 雙鐵
# JP: 「だが、ご無用な気遣いだ。\n議案は――必ず通過出来る」
1264 = "「不過，這份擔心是多餘的。議案一定會通過的」" 

# monologue
# JP: （ぎゅっ）
1955 = "（握住）" 

# 【ポーレット】
# display as 波萊特
# JP: 「っ！」
1483 = "「！」" 

# monologue
# JP: にぎってくれる手が熱い。\nあったかいじゃなく、すごく熱い。
1928 = "雙鐵君的手非常燙。都不能算是溫暖，而是燙手。" 

# monologue
# JP: 双鉄くんの体温ふだん、わたしより絶対低いのに。
1773 = "明明雙鐵君的體溫應該比我還低的。" 

# 【ポーレット】
# display as 波萊特
# JP: 「……うん」
1173 = "「……嗯」" 

# monologue
# JP: 双鉄くん、いつもと同じじゃ、全然ないんだ。
1650 = "原來雙鐵君也並不是和平時完全一樣啊。" 

# monologue
# JP: 緊張？　興奮？　熱くなってるだけじゃなく、\n手――ちょっとだけ震えてる。
1883 = "該說是緊張、還是興奮？　雙鐵君的手不光發燙，還在微微顫抖。" 

# 【ポーレット】
# display as 波萊特
# JP: 「大丈夫。わたしに任せてください」
1407 = "「沒事的，都交給我吧」" 

# monologue
# JP: そうわかったら、どん、って落ち着く。
1833 = "看到他這副樣子，卻讓我一下子冷靜了下來。" 

# monologue
# JP: お腹の下の深いところから、\nどんどん勇気が湧いてくる。
1750 = "我感到勇氣從內心深處不斷湧出。" 

# 【ポーレット】
# display as 波萊特
# JP: 「どれほど反対されたって、必ず、議案を通過させる。\nわたしたちには――わたしたちなら、それが出来ます」
1260 = "「不管受到怎麼樣多的反對，我們也一定要讓議案通過。只要——我們在一起就能做到」" 

# 【双鉄】
# display as 雙鐵
# JP: 「うむ」
1310 = "「嗯」" 

# monologue
# JP: わたし、じゃなくて。わたしたち。\n双鉄くんが、こんなに近くにいてくれるから。
1600 = "不是我，而是我們。因為雙鐵君就在我身邊。" 

# monologue
# JP: いつもと違う双鉄くんが、\nそれでもやっぱり――いつもと同じに、居てくれるから。
1682 = "和平時有些不同的雙鐵君，還是和平時一樣陪在我身邊。" 

# 【双鉄】
# display as 雙鐵
# JP: 「っと――時間になるな」
1299 = "「哎呀——時間到了」" 

# 【ポーレット】
# display as 波萊特
# JP: 「あ」
# 1305 = "「啊」" 

# monologue
# JP: 手がほどかれて、代わりに資料を渡される。\nこんなところまで双鉄くん。
1618 = "他鬆開手，將資料交給我。這些方面上算是雙鐵君的作風。" 

# monologue
# JP: 緊張してても、どんなときでも。\n秘書のお仕事、完璧にこなしてくれている。
1604 = "不管多緊張，不管在什麼情況下，他都會完美地完成秘書的工作。" 

# 【双鉄】
# display as 雙鐵
# JP: 「これでいいか？\n他に準備することがあったら、いってくれ」
1471 = "「這些就夠了嗎？還有什麼要準備的就告訴我」" 

# 【ポーレット】
# display as 波萊特
# JP: 「う、ん」
1303 = "「唔，嗯……」" 

# monologue
# JP: 準備は、十分。\nだけど、足りない。
1705 = "已經準備好了。但還差一樣東西。" 

# monologue
# JP: わたしたち、だってせっかく、\n恋人同士になったんだから……
1740 = "我們好不容易才成為了戀人……" 

# 【ポーレット】
# display as 波萊特
# JP: 「……………………」
1168 = "「……………………」" 

# monologue
# JP: 待ってみる。けど、なんにもない。\n双鉄くんは、黙ったままで、そのまんま。
1752 = "我決定等他一會，但他沒有任何行動。雙鐵君就這樣沉默著。" 

# 【双鉄】
# display as 雙鐵
# JP: 「……ん？」
1174 = "「……嗯？」" 

# monologue
# JP: ダメこれ。ぜんっぜんわかってない。\n困ったみたいな、戸惑ったみたいな顔になってる。
1605 = "不行，他完全沒懂要做什麼。滿臉困惑地看著我。" 

# monologue
# JP: 恋人になったわたしが、これから、議場に――\n議員の戦場に行くっていうのに。
1772 = "明明我這個女朋友即將前往議員的戰場。" 

# 【ポーレット】
# display as 波萊特
# JP: 「――忘れ物」
1161 = "「——有東西忘了」" 

# 【双鉄】
# display as 雙鐵
# JP: 「え？」
1302 = "「哎？」" 

# monologue
# JP: （ちゅっ！）
1951 = "（啾！）" 

# monologue
# JP: だったら、自分から求めればいい。\n双鉄くんが教えてくれた。わたしに、思い出させてくれた。
1917 = "那就只好由我發動攻勢了。這也是雙鐵君告訴我的，讓我回想起來的。" 

# monologue
# JP: わたしたちは――求めることを、許されてるって。
1741 = "我們是可以追求幸福的。" 

# 【双鉄】
# display as 雙鐵
# JP: 「ああ」
# 1305 = "「啊」" 

# 【ポーレット】
# display as 波萊特
# JP: 「っ！？」
1484 = "「！？」" 

# monologue
# JP: 一瞬だけのキスのつもりでほどいた瞬間、\n双鉄くんから、わたしにキスを届けてくれる。
1654 = "原本打算親一下就放開，但下一秒雙鐵君就親了過來。" 

# monologue
# JP: 熱い、キス。\n口紅……こっそり直さなくっちゃ。
1919 = "那是一個熱烈的吻。待會得悄悄補口紅了。" 

# 【双鉄】
# display as 雙鐵
# JP: 「……もう、忘れ物はないか？」
1178 = "「……還有其它忘記帶的東西嗎？」" 

# monologue
# JP: 照れてる。\n双鉄くん、ものすごく。
1927 = "雙鐵君十分害羞的樣子。" 

# monologue
# JP: なんだか嬉しい。\n自信、ふつふつわいてくる。
1908 = "這讓我感覺好開心，自信感噴湧而出。" 

# 【ポーレット】
# display as 波萊特
# JP: 「大丈夫です」
1408 = "「沒有了」" 

# monologue
# JP: だってわたしは、双鉄くんを動揺させられちゃうくらい、\n素敵な女の子になれたんだから。
1690 = "因為我可是已經成長為能讓雙鐵君都為之動搖的出色女孩了。" 

# monologue
# JP: 双鉄くんほど難攻不落のテゴワイ相手、\n市議会をどれほど探してみたって、いるわけないから！
1712 = "市議會裡怎麼可能會有比雙鐵君還要難對付的對手呢！" 

# 【ポーレット】
# display as 波萊特
# JP: 「行ってきます！」
1379 = "「我走了！」" 

# 【双鉄】
# display as 雙鐵
# JP: 「――うむ」
1159 = "「——嗯」" 

# monologue
# JP: ここまでの答弁は実にいい。\n落ち着き払って、わずかな動揺さえ見られない。
1647 = "到目前為止答辯都進展得很順利。波萊特十分冷靜，看不出有一絲一毫的動搖。" 

# monologue
# JP: （勇気を、もらえているのかもしれんな）
1956 = "（說不定是有人給了她勇氣吧）" 

# monologue
# JP: 傍聴席には、普段は見られない顔がある。
1765 = "旁聽席坐著平時沒來過的熟悉面孔。" 

# monologue
# JP: ハチロク、日々姫、れいな、ふかみと凪はもちろん、\n真闇姉に蓑笠老人――赤井宮司に、\x%l乗務鞄;#00ffc040;乗務鞄%l;#;の姿まである。
1641 = "八六、日日姬、玲奈、深美還有凪自不必說，甚至真闇姐和蓑笠爺爺、赤井宮司，還有他的\\x%l乗務鞄;#00ffc040;乘務包%l;#;也在。" 

# monologue
# JP: （なら、これでいい――赤井阿蘇神社の文化財申請議案の\nように、全会一致は、まず望むべくもなかろうが――）
1962 = "（這樣就好，雖然不能指望像赤井阿蘇神社的文化財產申請一樣得到全票通過——）" 

# monologue
# JP: 宝生元忠氏も、傍聴している。\n稀咲の姿は見当たらない。
1699 = "寶生元忠也在旁聽席。卻沒看到稀咲的身影。" 

# monologue
# JP: 元忠氏の存在は、\x%lエアクラ;#00ffc040;エアクラ%l;#;推進誘致派の議員たちへの、\nおそらくは、強烈な締め付けとして働くだろう。
1637 = "光是寶生元忠在場，就能給支持\\x%lエアクラ;#00ffc040;空凝機%l;#;落戶的議員們起到強烈的警示作用。" 

# monologue
# JP: （それでも、いける。今日のポーレットの答弁ならば、\n中立派の議員の票を、必ず、根こそぎ獲得できる）
1947 = "（但是，今天可以。今天波萊特的答辯一定能爭取到所有中立派議員的投票）" 

# 【議長】
# display as 議長
# JP: 「御一夜市民の会、篠原くーん」
1352 = "「御一夜市民會，篠原議員」" 

# 【老議員】
# display as 老議員
# JP: 「はい。市長、よろしくお願いします」
1274 = "「到。市長，請多多指教」" 

# 【ポーレット】
# display as 波萊特
# JP: 「お願いします」
1456 = "「請您多多指教」" 

# monologue
# JP: ……最後の質問者は篠原議員。\n御一夜市議会の生き字引とも言われる、長老議員だ。
1156 = "……最後提問的是篠原議員，他是被稱為御一夜市議會活字典的長老級議員。" 

# 【老議員】
# display as 老議員
# JP: 「マイントレジャー計画について、\nこれは、助成金を見込まれての事業となられますか？」
1455 = "「請問煤探樂園計劃是以獲得國家補助金為前提開展的事業嗎？」" 

# 【ポーレット】
# display as 波萊特
# JP: 「『技術継承炭鉱にかかる助成金』の申請を提出しようと\n現時点では予定しております」
1364 = "「我們是有打算申請“技術繼承煤礦補助金”」" 

# 【老議員】
# display as 老議員
# JP: 「旧術仙炭鉱も、助成金を頼りに運営されていたことを、\n知っておられますか」
1477 = "「那您知道舊術仙煤礦曾經也是依靠補助金運營的事吧」" 

# 【ポーレット】
# display as 波萊特
# JP: 「その点、勉強させていただきました。\n『国内炭保護のための助成金』を、二十二期連続で」
1403 = "「有關這點我了解過。術仙舊煤礦曾經連續２２期獲得了“國內煤礦保護補助金”」" 

# 【老議員】
# display as 老議員
# JP: 「石炭需要がのうなったと、そいば打ち切られたとき。\n術仙炭鉱の命脈もまた、尽きたとです」
1422 = "「當不需要煤礦的時候，國家馬上就收回了援助。術仙煤礦的命運也止步於此」" 

# 【ポーレット】
# display as 波萊特
# JP: 「承知しております」
1378 = "「我知道這件事」" 

# monologue
# JP: 老議員の皺が深くなる。\n真っ白な眉の下の目が、じっとポーレットのことを見る。
1872 = "老議員皺起眉頭。雪白眉毛下的眼睛熠熠發光，眼睛緊盯著波萊特。" 

# 【老議員】
# display as 老議員
# JP: 「助成金に頼っての経済復興は、過去の過ちば\n繰り返すだけと――市長は、思われませんとですか？」
1269 = "「依賴國家補助進行經濟復興只會重蹈過去的覆轍——市長難道沒考慮過這點嗎？」" 

# 【ポーレット】
# display as 波萊特
# JP: 「ご懸念、ごもっともと存じます。が、助成金が無くとも、\nマイントレジャーは採算を取れる計画となっております」
1356 = "「您的擔心是非常正確的。不過，煤探樂園的資金預算原本就是建立在如果沒能獲得補助的前提下的」" 

# monologue
# JP: ポーレットがフリップを前面に出す。
1795 = "波萊特展示預算表格。" 

# 【ポーレット】
# display as 波萊特
# JP: 「初年度の来場者数を２０万人確保でき、年１０％の増加を\n三年継続できれば、四年目からは単体黒字に到達します」
1285 = "「只要第一年客人能有２０萬人次，接著連續３年保持１０％增加，第四年就可以單獨盈利」" 

# monologue
# JP: 昨年度の御一夜市の宿泊観光客数は４０万人。\n宿泊せず、観光施設を利用した客数がその他に３０万人だ。
1593 = "上一年在御一夜市住宿的觀光訪客約有４０萬人次。而不住宿僅是觀光的人次還有３０萬。" 

# monologue
# JP: ２０万人という利用者予測は、\n決して、過大なものではない。
1966 = "２０萬人次的預計訪客並不算誇張。" 

# 【老議員】
# display as 老議員
# JP: 「廃炭鉱に、２０万人もの人が訪れるとは思えませんが」
1368 = "「我倒是不覺得會有２０萬遊客去廢煤礦玩」" 

# 【ポーレット】
# display as 波萊特
# JP: 「単なる廃炭鉱なら、そうでしょう。しかし、\nそれを魅力的なものとするための、テーマパーク化です」
1327 = "「如果只是廢煤礦的話，的確會是如此。但是，我們要建的是讓廢煤礦變得更有魅力的主題公園」" 

# monologue
# JP: またフリップ。\n今度は、図表ではなく、写真が中心となるものだ。
1794 = "波萊特切換了說明圖。這次不是數字圖表而是照片。" 

# 【ポーレット】
# display as 波萊特
# JP: 「これは、[しが,1]歯牙県[ながはま,2]那賀浜市の『[しらかべ,1]白壁スクエア』の写真です。\n町並みそのものをテーマパーク化した成功例です」
1472 = "「這是滋賀縣長濱市的黑壁廣場的照片。是一個連同整個城市風景都主題樂園化的成功範例」" 

# monologue
# JP: 知る人ぞ知る存在に留まっていた白壁づくりの町並みを、\n『歴史とアート』というキーワードによって切り出した。
1651 = "原本名不見經傳的黑壁廣場，憑藉打出“歷史與藝術”的旗號，如今已經小有名氣。" 

# monologue
# JP: その工夫により観光客数は跳ね上がり、\n昨年度には１８０万人にまで到達した。
1648 = "前來觀光的遊客數也急劇增長，上一年度達到了１８０萬人次。" 

# 【ポーレット】
# display as 波萊特
# JP: 「地元の人間にとってはありふれた光景であっても、\n観光客には見たことのない景色です」
1331 = "「對當地人來說見慣了的東西，對遊客而言卻是未曾見過的美景」" 

# 【老議員】
# display as 老議員
# JP: 「ありふれた、では無か。\n“目にしたくない”光景ばい」
1380 = "「才不是見慣了。是我們“不想見”的光景咧」" 

# 【双鉄】
# display as 雙鐵
# JP: 「っ！」
# 1483 = "「！」" 

# monologue
# JP: しわがれた――とは、このことか。
1746 = "我到此刻才明白，什麼才叫嘶啞的聲音。" 

# monologue
# JP: 篠原議員の声は枯れ切り、\nなのに、悲しみに溢れている。
1853 = "篠原議員的聲音十分乾啞，卻充滿悲傷。" 

# monologue
# JP: 絞りだすような一声に、\n多くの議員が大きく頷く。
1876 = "聽到他這句牙縫裡擠出來的話語，多名議員點頭表示同意。" 

# monologue
# JP: ああ、これは……稀咲が警告してくれたとおり――\n御一夜市そのものの持つ、傷跡なのだ。
1683 = "啊，原來這就是稀咲曾經警告過我們的——御一夜市的傷疤嗎。" 

# 【老議員】
# display as 老議員
# JP: 「御一夜が術仙炭鉱にどれほど多くを注ぎ込んだか……\nその誤った判断の、あれは、醜か残りカスたい」
1353 = "「御一夜曾經在術仙煤礦上幾乎投入了一切……那個廢煤礦，正是當初的錯誤判斷所留下的醜陋傷疤」" 

# 【ポーレット】
# display as 波萊特
# JP: 「いいえ――いいえ、篠原議員」
1256 = "「不——不是這樣的，篠原議員」" 

# monologue
# JP: けれど、ポーレットは動じない。
1629 = "但波萊特絲毫不為所動。" 

# monologue
# JP: 悲しみにも、後悔にも、\n声は、言葉は、いささかたりとも揺れ動かない。
1886 = "議員們的悲傷和悔恨絲毫不能讓她的語氣有所動搖。" 

# 【ポーレット】
# display as 波萊特
# JP: 「誤った判断だったと――\nそう結論づけるには、まだ早すぎます」
1267 = "「你說那是錯誤的判斷，現在下這個結論還為時尚早」" 

# 【老議員】
# display as 老議員
# JP: 「なっ！？」
1266 = "「什麼！？」" 

# monologue
# JP: 何十年も、塩漬けにしてきたのであろう傷跡を。
1721 = "御一夜經歷數十年風吹日曬的傷疤——" 

# monologue
# JP: ポーレットは真正面から、\n“古傷ではない”と否定する。
1793 = "波萊特公然否定了其“舊傷疤”的定義。" 

# 【ポーレット】
# display as 波萊特
# JP: 「技術継承炭鉱としての助成をほぼ確実に受けられると\n――これは、水面下でのお墨付きをいただいてます」
1363 = "「我們已經得到政府非公開的保證，幾乎能百分之百拿到這筆補助金」" 

# 【老議員】
# display as 老議員
# JP: 「じゃけん、助成金に頼るようでは」
1286 = "「可是，如果只依賴於補助金——」" 

# 【ポーレット】
# display as 波萊特
# JP: 「考えてみてください、篠原議員。\n技術継承炭鉱に、どのような炭鉱が選ばれるかを」
1457 = "「請您思考一下，篠原議員。什麼樣的煤礦會當選技術繼承煤礦呢」" 

# 【老議員】
# display as 老議員
# JP: 「っ！」
# 1483 = "「！」" 

# monologue
# JP: そう。全国に数多くある廃炭鉱の中から、\n技術継承炭鉱として選ばれるのは、容易ではない。
1784 = "沒錯。全國有著無數的廢煤礦，要想從中脫穎而出獲得技術繼承煤礦的認定絕非易事。" 

# 【ポーレット】
# display as 波萊特
# JP: 「術仙炭鉱は、廃坑のぎりぎりまで設備投資と\n技術練磨とを惜しまなかった」
1447 = "「術仙煤礦直到被廢棄的前一刻也在不惜成本進行設備投資和技術培訓」" 

# monologue
# JP: 篠原議員が、誤った判断だったと思い込んでる、\n“見切りの悪さ”。
1851 = "篠原議員一直以為這是錯誤的判斷，認為這是“不懂得放棄”。" 

# monologue
# JP: しかしそれは、見方を変えれば、\n“最後まで緩まなかった”ということでもあるのだ。
1622 = "但只要切換一個視角，也可以解釋為術仙煤礦“直到最後一刻也沒有鬆懈”。" 

# 【ポーレット】
# display as 波萊特
# JP: 「その設備は放棄されず、再稼働を信じて保存された。\n再開発の手は及ばず、一帯全て欠けるものなく残された」
1335 = "「工人們留下了那些設備，相信有一天會重新派上用場。那片地區也沒有進行再開發，完好無缺地留了下來」" 

# monologue
# JP: だからこそ、生々しすぎる傷跡と、\nきっと、目を背けられ続けてきたのだろう。
1757 = "所以人們才認為那是一道過於慘痛的傷痕，不得不移開目光。" 

# monologue
# JP: が――それがどれほど希少な価値を持つものか。\n外部からきた僕らの目には、はっきりわかる。
1619 = "但——要問這些東西有多珍貴，身為外部人士的我們反而更加清楚。" 

# 【ポーレット】
# display as 波萊特
# JP: 「技術継承炭鉱としての再稼働には、\n炭鉱労働者だった方々の再雇用が必須となります」
1434 = "「而且要讓廢煤礦作為技術繼承煤礦重新啟動，還需要再次僱傭各位曾經在煤礦工作過的人」" 

# 【老議員】
# display as 老議員
# JP: 「う、む」
1307 = "「嗯……」" 

# 【ポーレット】
# display as 波萊特
# JP: 「その方々と、テーマパークの従業員となる若者たちとの\n交流は、御一夜に新たな活気を呼ぶはずです」
1376 = "「我相信，通過那些人和主題公園所僱傭的年輕工作人員之間所進行的交流，一定能為御一夜的發展注入新的動力」" 

# monologue
# JP: \x%lエアクラ;#00ffc040;エアクラ%l;#;工場誘致賛成派と反対派と――\nそれだけでなく、無力感が生んでしまった、世代間の――
1596 = "不光是\\x%lエアクラ;#00ffc040;空凝機%l;#;工廠落戶支持派和反對派之間，年輕人和老年人之間也存在著代溝——" 

# monologue
# JP: 御一夜の長い停滞のその一因は、\n確実に、そうした断絶にもあるだろう。
1724 = "御一夜長期發展停滯也有著代溝這方面的原因吧。" 

# 【ポーレット】
# display as 波萊特
# JP: 「術仙炭鉱にはまだ多くの石炭が眠り。\nそれだけにとどまらぬ、無数の価値が眠っているのです」
1446 = "「術仙煤礦現在煤礦儲量還很豐富。不僅如此，還有著很多可供開發的地方」" 

# monologue
# JP: それを、僕らは掘り返す。\n御一夜に淀んでいた力を呼び覚まし、観光客の力も借りて。
1701 = "就由我們來將這些東西開發出來。與遊客一同，發掘御一夜沉睡的活力。" 

# 【ポーレット】
# display as 波萊特
# JP: 「術仙炭鉱の再評価は、第三者によって行われるべきです。\n国により、観光客により、若者により」
1448 = "「術仙煤礦需要由第三者來重新評價。由國家、遊客、還有年輕人們」" 

# monologue
# JP: マイントレジャーというスポットを当て、\nそこに、多くの目を注がせる。
1910 = "通過煤探樂園項目，吸引更多人的關注。" 

# 【ポーレット】
# display as 波萊特
# JP: 「御一夜のかつての判断が、決して過ちではなかったと\n――それが証明されることを、わたしは確信しています」
1372 = "「我相信一定能夠證明，御一夜曾經的判斷絕不是個錯誤」" 

# 【老議員】
# display as 老議員
# JP: 「見てみんふりば――\nわしらぁ、してきよったと言うことか」
1332 = "「就是說——我們至今為止一直在自欺欺人嗎」" 

# monologue
# JP: それは同じだ。\n昨日までの僕も、ポーレットも。
1692 = "在昨天之前，我和波萊特也是一樣的。" 

# monologue
# JP: あまりに深い[くらがり]傷だから、\n再評価など、できるとさえも思えなかった。
1742 = "我們根本不相信，能夠對如此之深的傷口重新進行評價。" 

# 【老議員】
# display as 老議員
# JP: 「いけんの。\nそがいなことでは、いけん」
1262 = "「不行啊。這樣可不行」" 

# monologue
# JP: 質疑ではなく、それは嘆息。
1871 = "老議員發出了嘆息而並非質疑的聲音。" 

# 【老議員】
# display as 老議員
# JP: 「術仙炭鉱の再検証なしに\x%lエアクラ;#00ffc040;エアクラ%l;#;工場を誘致して――\n目ぇ瞑ったまま、手ば引いてもらおうとしておったのか」
1366 = "「我們竟沒有重新審查術仙煤礦的可能性，就決定支持\\x%lエアクラ;#00ffc040;空凝機%l;#;工廠落戶——簡直就是閉著眼睛，讓人牽著走啊」" 

# monologue
# JP: ざわ、と動揺の響きが起こる。\nしかし、熱心な誘致賛成派さえ、抗議のヤジを飛ばせない。
1763 = "整個議會廳都動搖起來。然而就連狂熱的工廠落戶支持派，都沒有抗議和起鬨。" 

# monologue
# JP: 老議員のはらわたからにじみでる――\nそれはあまりに、長く、深く、重苦しいほどの嘆息だから。
1907 = "這一切都是因為年長的議員發出了如此深切的肺腑之言。" 

# 【ポーレット】
# display as 波萊特
# JP: 「御一夜がもとから持っているもの――\nその再評価を、マイントレジャー計画は望むだけです」
1365 = "「我們煤探樂園計劃的初衷，就只是希望對御一夜原本擁有的資源重新進行評價」" 

# monologue
# JP: 積み重ねてきた全てを、再び一から見直す。
1743 = "我們決定回首望去，重新審視御一夜至今積累的一切。" 

# monologue
# JP: 本当に傷で過ちと、誰もが思っているのなら――\nポーレットのこの答弁は、むしろ逆効果に働こう。
1694 = "如果有人真心認為廢煤礦是御一夜的舊傷，那麼波萊特這番答辯恐怕只會適得其反吧。" 

# 【ポーレット】
# display as 波萊特
# JP: 「父の愛した御一夜を、その歴史をわたしは信じています。\n議員の皆さまに於かれましても、それは同様と信じます」
1374 = "「我相信父親所熱愛的御一夜，相信其一路走來的歷史。我相信各位議員也與我一樣」" 

# monologue
# JP: が――
1625 = "但是——" 

# 【老議員】
# display as 老議員
# JP: 「……よかご答弁を、ありがとうございます」
1175 = "「……感謝您精彩的答辯」" 

# monologue
# JP: 深々と。\nポーレットに向け、篠原議員が頭を下げる。
1852 = "篠原議員向波萊特深深低頭行禮。" 

# monologue
# JP: 深々と。\nポーレットもまた、篠原議員に答礼する。
1792 = "波萊特也向篠原議員深深地回禮。" 

# 【老議員】
# display as 老議員
# JP: 「市長。わしの質問ば、これで十分とです」
1337 = "「市長，我沒有其它問題了」" 

# 【議長】
# display as 議長
# JP: 「篠原議員の質問を終わります。\n他に、質疑のある方はございませんか」
1430 = "「篠原議員的提問時間到此結束。還有人要提問嗎」" 

# monologue
# JP: 篠原議員は、質問時間を残して終わった。\n慣例上、議長が他の質疑の有無を問いかける。
1854 = "篠原議員還沒到規定時間就結束了提問。按照慣例，議長需要詢問還有沒有其他問題。" 

# monologue
# JP: が、それに応じてあがる手は無い。\n今の質疑で十分と、議場の誰もが感じている。
1626 = "但是沒有一個人舉手。恐怕在場的所有人都覺得，只憑剛才那一番論戰就已經足夠了吧。" 

# 【議長】
# display as 議長
# JP: 「なければ、議決に入ります。\nまず、『赤井阿蘇神社の文化財申請に関する議案』」
1410 = "「沒有的話，就進入表決階段。首先是“赤井阿蘇神社文化財產申請議案”」" 

# monologue
# JP: 議長が挙手を求める前から、\nいくつもの手があげられる。
1913 = "還沒等議長說出“贊成的議員請舉手”，就有人開始舉手了。" 

# monologue
# JP: 遅れて議長が賛成議員の挙手を願えば、\n議員席、全てに手のひらの花が咲く。
1830 = "當議長說完這一句話，所有議員都舉起了手。" 

# 【議長】
# display as 議長
# JP: 「賛成多数と認め、本案を可決いたします。続いて、\n『旧術仙炭鉱の技術継承炭鉱としての助成申請案』」
1319 = "「多數人贊成，本議案通過。接著是“原術仙煤礦申請技術繼承煤礦補助金草案”」" 

# monologue
# JP: 議長の求めた挙手に応じて、\nこれもすぐさま、大多数の手があげられる。
1839 = "等議長表示可以舉手表示贊成後，大部分議員也都舉起了手。" 

# 【議長】
# display as 議長
# JP: 「賛成多数と認め、本案を可決いたします。続いて、\n『マイントレジャーによる術仙炭鉱地域再開発』案」
1320 = "「多數人贊成，本議案通過。接著是“通過煤探樂園進行術仙煤礦再開發草案”」" 

# monologue
# JP: ばっと――、一本の手が伸びる。
1686 = "啪地，有一隻手馬上舉了起來。" 

# 【ポーレット】
# display as 波萊特
# JP: 「あ」
# 1305 = "「啊」" 

# monologue
# JP: 篠原議員の手が、まっすぐに。\nそしてぽつぽつ――長老議員たちの挙手が続く。
1678 = "只見篠原議員直直舉起了手。接著稀稀落落地——其餘年長議員們也舉起了手。" 

# 【議長】
# display as 議長
# JP: 「賛成の議員の方は、挙手を願います」
1449 = "「表示贊成的議員請舉手」" 

# monologue
# JP: ……全会一致、とはとてもいかない。
1157 = "……沒能得到全場一致的認可。" 

# monologue
# JP: 苦虫を噛み潰したような顔をして、\n腕組みしてる議員も決して、少なくはない。が――
1760 = "抱起手臂來擺著一張苦臉的議員也不在少數。但——" 

# 【議長】
# display as 議長
# JP: 「賛成多数と認め、本案を可決いたします」
1321 = "「多數人贊成，本議案通過」" 

# 【れいな】
# display as 玲奈＆凪
# JP: 「わぁい！」\n「やったばいっ！！」
1295 = "「哇！」\\n「咱們做到咧！！」" 

# 【ふかみ】
# display as 深美
# JP: 「ちょっ！？　凪ちゃん」
1306 = "「喂！？　小凪」" 

# 【議長】
# display as 議長
# JP: 「傍聴席は静粛に願います」
1458 = "「請旁聽席肅靜」" 

# monologue
# JP: ――ふかみの仕事を、\n今日は議長が代わってくれる。
1146 = "——今天由議長代替了深美平時的工作。" 

# monologue
# JP: しまったばい！　と言わんばかりに、\n凪は大きく両手でくちを覆って――っ！？
1831 = "發現自己壞了事，凪連忙捂住自己的嘴——等等！？" 

# monologue
# JP: （退席している――宝生元忠が）
1954 = "（寶生元忠離席了）" 

# monologue
# JP: いつから退席していたのか、\n全く、僕には気づけなかった。
1616 = "他是什麼時候離席的，我完全沒有注意到。" 

# monologue
# JP: 質疑応答を聞き届け、\n勝負あったと――あるいは、あきらめてくれたのか。
1777 = "是他聽完答辯之後，覺得勝負已分——或者是終於放棄了嗎。" 

# monologue
# JP: （いや……あきらめていなくとも、変わらんはずだ）
1946 = "（不……就算他不放棄，結果也不會改變）" 

# monologue
# JP: 議案成立で河川敷利用の専有許可は確保でき、\n\x%lエアクラ;#00ffc040;エアクラ%l;#;工場誘致の余地などなくなった。
1674 = "只要議案通過，我們就能拿到河邊土地的使用權，\\x%lエアクラ;#00ffc040;空凝機%l;#;工廠落戶計劃已成死局。" 

# monologue
# JP: こうなった以上マイントレジャーに賛同し成功させるのが、\n御一夜市にも隈銀にも、最善の選択となるのだから。
1608 = "事已至此，支持並推進煤探樂園計劃，也就成了御一夜市和隈元銀行最好的選擇。" 

# 【ポーレット】
# display as 波萊特
# JP: 「双鉄くんっ！」
1481 = "「雙鐵君！」" 

# 【双鉄】
# display as 雙鐵
# JP: 「っ！」
# 1483 = "「！」" 

# monologue
# JP: とても柔らかな衝撃と熱。\n議場を抜け出し、ポーレットが僕に抱きついてくる。
1748 = "我感到了一陣溫暖柔軟的衝擊。原來是跑出會場的波萊特抱住了我。" 

# 【ポーレット】
# display as 波萊特
# JP: 「わたし――わたし、やりました！」
1357 = "「我——我做到了！」" 

# 【双鉄】
# display as 雙鐵
# JP: 「うん。見ていた。\nとても、見事だった」
1309 = "「嗯。我看著呢。你做得非常漂亮」" 

# 【ポーレット】
# display as 波萊特
# JP: 「えへへへへ」
1300 = "「哎嘿嘿」" 

# monologue
# JP: 笑顔は、まっすぐ誇らしそうだ。
1693 = "她露出了得意的笑容。" 

# monologue
# JP: 野次られるたびにおろおろしていた、\nあのポーレットとはまるで見違えた。
1828 = "現在的她與過去那個反對派一起鬨就不知所措的波萊特相比簡直判若兩人。" 

# 【双鉄】
# display as 雙鐵
# JP: 「強くなったな。ポーレットは」
1418 = "「波萊特，你變堅強了啊」" 

# 【ポーレット】
# display as 波萊特
# JP: 「違いますよ？　双鉄くん。\nふたりで、強くなったんです」
1258 = "「不是的，雙鐵君。是我們兩個人一起變堅強了」" 

# 【双鉄】
# display as 雙鐵
# JP: 「ああ――」
1393 = "「是啊——」" 

# monologue
# JP: ただの偶然で、相性で。
1590 = "一切都是偶然，還有我們性情相合。" 

# monologue
# JP: だけれど僕等は、見事にお互いを支え合えた。\n傷を見せ合いのりこえて――だから、一緒に強くなれた。
1624 = "但我們卻做到了相互扶持。向對方揭示自己的傷口，然後一起克服——一起變強了。" 

# 【双鉄】
# display as 雙鐵
# JP: 「ならば、ご褒美をもらえるか？」
1479 = "「那，我有獎勵嗎？」" 

# 【ポーレット】
# display as 波萊特
# JP: 「あ……」
1304 = "「啊……」" 

# monologue
# JP: ふと、気にかかる。\n舞台袖から、僕は覗いて議場の様子を見て取ってたが――
1884 = "說到這，我突然有些擔心。因為我剛才是從講台側面觀察會場的——" 

# monologue
# JP: あちらから、こちらの様子は果たして\n覗けるものなのだろうか？
1602 = "不知從那裡是不是也能看到我們這邊呀？" 

# 【ポーレット】
# display as 波萊特
# JP: 「奇遇ですね。わたしも、ご褒美。\n双鉄くんからもらいたいなって、思ってました」
1424 = "「真巧啊。我也想跟雙鐵君要獎勵呢」" 

# 【双鉄】
# display as 雙鐵
# JP: 「なら」
1475 = "「那——」" 

# monologue
# JP: まぁ、見ていようが見えていまいが、構わない。\nなにひとつ、誰に隠そうとも思わない。
1841 = "算了，管他有沒有人看到。我原本也沒想要隱瞞。" 

# 【双鉄】
# display as 雙鐵
# JP: 「ポーレット」
1417 = "「波萊特」" 

# 【ポーレット】
# display as 波萊特
# JP: 「双鉄くん」
1480 = "「雙鐵君」" 

# monologue
# JP: そのまま、軽く抱きしめあって。
1739 = "我們倆輕輕抱在一起。" 

# monologue
# JP: 僕たちは、お互いにご褒美を与え合う。
1816 = "然後親吻著對方的嘴唇，獎勵著對方。" 
