# ポーレット13_再評価.txt

[info]

[characters]
1549 = "Fukami"
1558 = "Reina"
1575 = "Paulette"
1656 = "Soutetsu"
1865 = "Nghị viên lão thành"
1889 = "Chủ tịch"

[character_subs]
1791 = "Paulette"
1800 = "Fukami"
1822 = "Reina"
1827 = "Reina & Nagi"
1925 = "Soutetsu"

[script]
1146 = "——Công việc của Fukami,\\nhôm nay đã có chủ tọa làm thay."
1156 = "……Người đặt câu hỏi cuối cùng là nghị sĩ Shinohara.\\nÔng là một nghị sĩ lão làng, được mệnh danh là từ điển sống của Hội đồng thành phố Ohimitera."
1157 = "……Không thể nói là nhất trí toàn thể được."
1159 = "「――Ừm.」"
1161 = "「――Anh quên đồ kìa.」"
1163 = "「――Quả là một sự ủng hộ vô cùng mạnh mẽ.\\nÝ cô ấy là dù nghị án không được thông qua, thì cũng đừng bỏ cuộc.」"
1168 = "「……………………」"
1173 = "「……Vâng.」"
1174 = "「……Hửm?」"
1175 = "「……Cảm ơn cô, vì một phần biện luận tuyệt vời.」"
1178 = "「……Đã hết, quên đồ chưa?」"
1256 = "「Không――Không phải vậy đâu, thưa nghị sĩ Shinohara.」"
1258 = "「Không phải đâu nhé? Anh Soutetsu.\\nLà cả hai chúng ta, cùng trở nên mạnh mẽ hơn.」"
1260 = "「Dù có bị phản đối đến mức nào, tôi cũng nhất định sẽ cho thông qua nghị án.\\nChúng ta――nếu là chúng ta, chắc chắn sẽ làm được.」"
1262 = "「Không được rồi.\\nNhư thế thì, không được rồi.」"
1264 = "「Nhưng, sự lo lắng đó là thừa thãi rồi.\\nNghị án――chắc chắn sẽ được thông qua.」"
1266 = "「Cái gì!?」"
1267 = "「Đó là một quyết định sai lầm――\\nĐể đưa ra kết luận như vậy, thì vẫn còn quá sớm ạ.」"
1269 = "「Chấn hưng kinh tế dựa vào tiền trợ cấp, chẳng khác nào\\nlặp lại sai lầm trong quá khứ――Thị trưởng không nghĩ vậy sao?」"
1274 = "「Vâng. Thị trưởng, xin được chỉ giáo.」"
1285 = "「Nếu đảm bảo được 200 nghìn lượt khách trong năm đầu tiên, và duy trì mức tăng trưởng 10% mỗi năm\\ntrong vòng 3 năm, thì từ năm thứ 4 trở đi dự án sẽ bắt đầu có lãi độc lập ạ.」"
1286 = "「Vậy thì, nếu cứ dựa dẫm vào tiền trợ cấp thì」"
1290 = "「Oa……chào buổi sáng ạ~, chị Paulette,\\nmới sáng sớm mà chị đã gọi điện thoại rồi ạ~?」"
1292 = "「Oa.\\nCông chúa dậy sớm thật đấy nhỉ~」"
1293 = "「Phù.」"
1295 = "「Oa!」\\n「Làm được rồi nè!!」"
1299 = "「A――Đến giờ rồi.」"
1300 = "「Ehehehehe.」"
1301 = "「Hả!?」"
1302 = "「Hả?」"
1303 = "「Ư, m.」"
1304 = "「A……」"
1305 = "「A.」"
1306 = "「Khoan đã!? Bé Nagi.」"
1307 = "「Ư, m.」"
1309 = "「Ừ. Anh có xem mà.\\nEm làm rất xuất sắc.」"
1310 = "「Ừm.」"
1312 = "「Ừm, từ Densha Hime của nhà Mouri.」"
1313 = "「Hô.」"
1319 = "「Đa số tán thành, nghị án này được thông qua. Tiếp theo là,\\n『Nghị án xin trợ cấp cho mỏ than cũ Jutsusen với tư cách là mỏ than kế thừa kỹ thuật』.」"
1320 = "「Đa số tán thành, nghị án này được thông qua. Tiếp theo là,\\nNghị án 『Tái phát triển khu vực mỏ than Jutsusen thông qua Mine Treasure』.」"
1321 = "「Đa số tán thành, nghị án này được thông qua.」"
1327 = "「Nếu chỉ là một mỏ than bỏ hoang đơn thuần thì đúng là vậy. Tuy nhiên,\\nviệc biến nó thành công viên chủ đề chính là để làm cho nó trở nên hấp dẫn hơn ạ.」"
1330 = "「À đúng rồi ạ~. Chuyện là, điện thoại từ Densha Hime,\\nđã nói về chuyện gì vậy ạ~?」"
1331 = "「Dù đối với người dân địa phương, đó chỉ là những cảnh tượng bình thường,\\nnhưng đối với khách du lịch, đó lại là những khung cảnh chưa từng thấy ạ.」"
1332 = "「Ý cô là――\\nchúng ta, đã luôn nhắm mắt làm ngơ sao.」"
1335 = "「Những thiết bị đó không bị vứt bỏ, mà được bảo tồn với niềm tin sẽ được tái khởi động.\\nBàn tay tái thiết không chạm tới, toàn bộ khu vực được giữ lại nguyên vẹn không thiếu thứ gì.」"
1337 = "「Thị trưởng. Câu hỏi của tôi, đến đây là đủ rồi.」"
1352 = "「Hội công dân Ohimitera, nghị sĩ Shinohara.」"
1353 = "「Ohimitera đã đổ bao nhiêu công sức và của cải vào Mỏ than Jussen……\\nĐó là, tàn dư xấu xí của một quyết định sai lầm.」"
1356 = "「Sự lo ngại của ngài là hoàn toàn có cơ sở. Nhưng, dù không có tiền trợ cấp,\\nMine Treasure vẫn là một kế hoạch có thể sinh lời ạ.」"
1357 = "「Em——em, làm được rồi!」"
1363 = "「Việc gần như chắc chắn nhận được tiền trợ cấp với tư cách Mỏ than kế thừa kỹ thuật\\n――điều này, chúng tôi đã nhận được sự đảm bảo ngầm rồi ạ.」"
1364 = "「Hiện tại, chúng tôi đang dự định nộp đơn xin\\n『Tiền trợ cấp dành cho Mỏ than kế thừa kỹ thuật』 ạ.」"
1365 = "「Những gì Ohimitera vốn dĩ đã có――\\nKế hoạch Mine Treasure chỉ mong muốn được đánh giá lại những thứ đó thôi ạ.」"
1366 = "「Mời gọi nhà máy \\x%lエアクラ;#00ffc040;Aircra%l;# mà không hề kiểm chứng lại Mỏ than Jussen――\\nChẳng khác nào nhắm mắt đưa chân để người ta dắt đi sao.」"
1368 = "「Tôi không nghĩ sẽ có tới 200 nghìn người đến thăm một mỏ than bỏ hoang đâu.」"
1370 = "「Quả nhiên là vậy, anh nhỉ.」"
1372 = "「Quyết định trong quá khứ của Ohimitera tuyệt đối không phải là một sai lầm\\n――Tôi tin chắc rằng điều đó sẽ được chứng minh ạ.」"
1374 = "「Tôi tin vào Ohimitera mà cha tôi đã yêu thương, tin vào lịch sử của nó.\\nTôi tin rằng các vị nghị sĩ ở đây cũng có cùng suy nghĩ đó ạ.」"
1376 = "「Sự giao lưu giữa những người đó và những người trẻ tuổi sẽ trở thành nhân viên của công viên chủ đề\\nchắc chắn sẽ mang lại sức sống mới cho Ohimitera ạ.」"
1378 = "「Tôi biết điều đó ạ.」"
1379 = "「Tôi đi đây!」"
1380 = "「Bình thường, thì không nói làm gì.\\nĐó là khung cảnh “không muốn nhìn thấy” đấy.」"
1390 = "「Chào buổi sáng, Reina.\\nChị xin lỗi nhé? Tiếng điện thoại làm em thức giấc à?」"
1391 = "「Đúng vậy nhỉ~, Reina cũng tỉnh táo hẳn rồi ạ~!\\nNgủ một giấc thật đã, động cơ và bộ phận truyền động đều đang ở trạng thái tốt nhất――a.」"
1393 = "「Ừ——」"
1395 = "「Đúng vậy nhỉ, dậy sớm thật đấy.\\nNhưng nhờ vậy mà chị đã tỉnh ngủ hẳn rồi.」"
1397 = "「Vâng. \\x%lストーブ客車;#00ffc040;Toa xe sưởi ấm%l;#, nghe nói ngày mai sẽ đến Ohimitera.\\nHơn nữa, cô ấy còn bảo dù nghị án không được thông qua, thì cũng không cần trả lại.」"
1401 = "「Vậy sao ạ――Vâng! Cháu cảm ơn cô.\\nVâng――vâng――cháu hiểu rồi ạ. Vậy, cháu xin phép cúp máy ạ.」"
1403 = "「Về điểm đó, tôi đã tìm hiểu qua rồi ạ.\\n『Tiền trợ cấp bảo hộ than trong nước』, liên tiếp trong 22 kỳ.」"
1407 = "「Không sao đâu. Cứ giao cho tôi.」"
1408 = "「Không sao đâu.」"
1409 = "「Không sao đâu ạ~.\\nĐiện thoại, từ ai gọi đến vậy ạ~?」"
1410 = "「Nếu không có ai, chúng ta sẽ bước vào phần biểu quyết.\\nTrước tiên là 『Nghị án về việc xin cấp phép tài sản văn hóa cho đền Akai Aso』.」"
1417 = "「Paulette.」"
1418 = "「Em đã trở nên mạnh mẽ hơn rồi đấy. Paulette à.」"
1422 = "「Khi nhu cầu than đá không còn, nguồn trợ cấp đó bị cắt đứt.\\nMệnh mạch của Mỏ than Jussen cũng theo đó mà cạn kiệt.」"
1424 = "「Thật trùng hợp. Em cũng,\\nđang nghĩ muốn nhận phần thưởng từ anh Soutetsu đây.」"
1430 = "「Phần đặt câu hỏi của nghị sĩ Shinohara xin được kết thúc.\\nCòn vị nào có câu hỏi nữa không ạ?」"
1434 = "「Để tái khởi động với tư cách Mỏ than kế thừa kỹ thuật,\\nviệc tái tuyển dụng những người từng là công nhân mỏ than là điều bắt buộc ạ.」"
1436 = "「Chuyện là thế này nhé? Reina……」"
1446 = "「Mỏ than Jussen vẫn còn rất nhiều than đá đang ngủ yên.\\nKhông chỉ dừng lại ở đó, còn vô số giá trị khác đang ngủ yên ở đó ạ.」"
1447 = "「Mỏ than Jussen, cho đến tận lúc sắp đóng cửa, vẫn không tiếc công đầu tư thiết bị\\nvà mài giũa kỹ thuật.」"
1448 = "「Việc đánh giá lại Mỏ than Jussen nên được thực hiện bởi bên thứ ba.\\nBởi quốc gia, bởi khách du lịch, bởi những người trẻ tuổi.」"
1449 = "「Xin mời các nghị viên tán thành giơ tay.」"
1455 = "「Về Kế hoạch Mine Treasure,\\nđây có phải là dự án được kỳ vọng sẽ nhận được tiền trợ cấp không?」"
1456 = "「Xin được chỉ giáo.」"
1457 = "「Xin ngài hãy suy nghĩ thử xem, thưa nghị sĩ Shinohara.\\nNhững mỏ than như thế nào mới được chọn làm Mỏ than kế thừa kỹ thuật.」"
1458 = "「Xin khán đài giữ trật tự.」"
1471 = "「Thế này đã đủ chưa?\\nNếu cần chuẩn bị gì thêm thì cứ nói với tôi.」"
1472 = "「Đây là hình ảnh của 『Quảng trường Shirakabe』 ở thành phố Nagahama, tỉnh Shiga.\\nĐây là một ví dụ thành công về việc biến chính cảnh quan đường phố thành công viên chủ đề ạ.」"
1475 = "「Vậy thì.」"
1477 = "「Thị trưởng có biết rằng Mỏ than Jussen cũ\\ncũng từng được vận hành dựa vào tiền trợ cấp không?」"
1479 = "「Vậy thì, anh có được nhận phần thưởng không?」"
1480 = "「Anh Soutetsu.」"
1481 = "「Anh Soutetsu!」"
1482 = "「Ngay cả việc vận chuyển, Densha Hime cũng sắp xếp toàn bộ sao.」"
1483 = "「!」"
1484 = "「!?」"
1590 = "Chỉ là sự tình cờ, vì sự đồng điệu."
1593 = "Số lượng khách du lịch lưu trú tại thành phố Ohimitera năm ngoái là 400 nghìn người.\\nSố lượng khách không lưu trú mà chỉ sử dụng các cơ sở du lịch là 300 nghìn người."
1596 = "Phe ủng hộ và phe phản đối mời gọi nhà máy \\x%lエアクラ;#00ffc040;Aircra%l;#――\\nKhông chỉ vậy, còn là sự đứt gãy giữa các thế hệ do cảm giác bất lực sinh ra――"
1600 = "Không phải là tôi, mà là chúng ta.\\nBởi vì có anh Soutetsu ở gần bên tôi thế này."
1602 = "Liệu từ bên đó, mọi người có thể\\nnhìn lén được tình hình bên này không nhỉ?"
1604 = "Dù có căng thẳng, dù trong bất kỳ hoàn cảnh nào.\\nAnh ấy vẫn hoàn thành xuất sắc công việc của một người thư ký."
1605 = "Thế này thì hỏng rồi. Anh ấy hoàn toàn không hiểu gì cả.\\nKhuôn mặt anh ấy lộ rõ vẻ bối rối, lúng túng."
1608 = "Một khi đã thế này, việc tán thành và giúp Mine Treasure thành công,\\nchính là lựa chọn tốt nhất cho cả thành phố Ohimitera lẫn ngân hàng Kumagin."
1616 = "Ông ta đã rời đi từ lúc nào,\\ntôi hoàn toàn không hề nhận ra."
1618 = "Bàn tay buông ra, thay vào đó tôi được nhận lấy tập tài liệu.\\nĐến cả những lúc thế này anh ấy vẫn mang đậm chất Soutetsu."
1619 = "Nhưng――nó lại mang một giá trị vô cùng quý hiếm.\\nTrong mắt những người từ bên ngoài đến như chúng tôi, điều đó rất rõ ràng."
1622 = "Tuy nhiên, nếu thay đổi góc nhìn,\\nđiều đó cũng có nghĩa là “không hề lơi lỏng cho đến phút cuối cùng”."
1624 = "Nhưng chúng tôi, đã hỗ trợ lẫn nhau một cách tuyệt vời.\\nCùng phơi bày vết thương và vượt qua nó——nên mới có thể cùng nhau trở nên mạnh mẽ."
1625 = "Nhưng――"
1626 = "Nhưng, không có cánh tay nào giơ lên đáp lại.\\nTất cả mọi người trong hội trường đều cảm thấy phần chất vấn vừa rồi là quá đủ."
1629 = "Nhưng, Paulette không hề nao núng."
1637 = "Sự hiện diện của ông Mototada,\\ncó lẽ sẽ đóng vai trò như một sự răn đe mạnh mẽ đối với các nghị sĩ thuộc phe ủng hộ mời gọi \\x%lエアクラ;#00ffc040;Aircra%l;#."
1641 = "Hachiroku, Hibiki, Reina, Fukami và Nagi thì khỏi phải nói,\\ncả chị Mayami, ông lão Minokasa――Đại tư tế Akai, và cả chiếc \\x%l乗務鞄;#00ffc040;cặp lái tàu%l;# cũng có mặt."
1647 = "Phần biện luận cho đến lúc này thực sự rất tốt.\\nCô ấy vô cùng bình tĩnh, không hề để lộ một chút dao động nào."
1648 = "Nhờ sự đổi mới đó, lượng khách du lịch đã tăng vọt,\\nvà đạt tới 1,8 triệu người vào năm ngoái."
1650 = "Anh Soutetsu, hoàn toàn không hề giống như mọi khi."
1651 = "Khu phố với những bức tường trắng vốn chỉ được biết đến bởi một số ít người,\\nnay đã được tái hiện thông qua từ khóa 『Lịch sử và Nghệ thuật』."
1654 = "Định bụng chỉ là một nụ hôn chớp nhoáng rồi buông ra, nhưng ngay khoảnh khắc đó,\\nanh Soutetsu lại chủ động trao cho tôi một nụ hôn."
1674 = "Với việc nghị án được thông qua, chúng ta đã nắm chắc giấy phép sử dụng độc quyền bãi bồi ven sông,\\nkhông còn chỗ trống nào để thu hút nhà máy \\x%lエアクラ;#00ffc040;Aircra%l;#; nữa."
1678 = "Cánh tay của nghị viên Shinohara giơ thẳng tắp.\\nVà rồi lác đác——các nghị viên lão làng cũng lần lượt giơ tay."
1682 = "Dù anh Soutetsu có khác với mọi khi,\\nnhưng quả nhiên――anh ấy vẫn luôn ở đó, giống như mọi khi."
1683 = "A, đây là……đúng như lời Kisaki đã cảnh báo――\\nlà vết sẹo của chính thành phố Ohimitera."
1686 = "Vút——, một cánh tay giơ lên."
1688 = "Ừm――thực sự là, tôi đã tỉnh giấc. Được đánh thức.\\nTôi đã cứ lơ lửng trên mây suốt từ đêm qua đến giờ."
1690 = "Bởi vì tôi, đã trở thành một cô gái tuyệt vời\\nđến mức có thể làm anh Soutetsu phải bối rối cơ mà."
1692 = "Điều đó thì ai cũng giống nhau thôi.\\nCả tôi của ngày hôm qua, và cả Paulette cũng vậy."
1693 = "Nụ cười của cô ấy, ánh lên vẻ đầy tự hào."
1694 = "Nếu tất cả mọi người đều thực sự nghĩ đó là một vết thương, một sai lầm――\\nthì phần biện luận này của Paulette, có lẽ sẽ mang lại tác dụng ngược."
1699 = "Ông Houshou Mototada cũng đang ngồi dự thính.\\nKhông thấy bóng dáng của Kisaki đâu."
1701 = "Chúng tôi sẽ đào xới những thứ đó lên.\\nĐánh thức sức mạnh đang đọng lại ở Ohimitera, mượn cả sức mạnh của khách du lịch."
1705 = "Chuẩn bị, thế là đủ rồi.\\nNhưng, vẫn còn thiếu."
1712 = "Một đối thủ khó nhằn, bất khả xâm phạm như anh Soutetsu,\\ndù có lục tung cả hội đồng thành phố lên cũng chẳng thể nào tìm thấy đâu!"
1721 = "Một vết sẹo đã bị ướp muối suốt mấy chục năm qua."
1724 = "Một trong những nguyên nhân khiến Ohimitera trì trệ trong một thời gian dài,\\nchắc chắn cũng là do sự đứt gãy đó."
1727 = "Thôi chết, không lẽ, có chỗ nào bất thường――"
1737 = "“Cao quý”, một từ trong tiếng Hinomoto,\\ncó lẽ cuối cùng tôi cũng đã nắm bắt được sắc thái của nó."
1739 = "Cứ thế, chúng tôi nhẹ nhàng ôm lấy nhau."
1740 = "Chúng tôi, khó khăn lắm mới,\\ntrở thành người yêu của nhau mà……"
1741 = "Chúng ta――được phép đòi hỏi."
1742 = "Bởi vì đó là một vết thương quá sâu,\\nnên chúng tôi thậm chí còn không nghĩ rằng mình có thể đánh giá lại nó."
1743 = "Nhìn nhận lại toàn bộ những gì đã tích lũy được từ đầu."
1746 = "Khàn đặc――là để chỉ điều này sao."
1748 = "Một cú va chạm và hơi ấm vô cùng mềm mại.\\nPaulette lao ra khỏi hội trường, ôm chầm lấy tôi."
1750 = "Từ sâu thẳm dưới bụng,\\ndũng khí không ngừng tuôn trào."
1752 = "Tôi thử chờ đợi. Nhưng, chẳng có chuyện gì xảy ra.\\nAnh Soutetsu vẫn cứ im lặng, cứ đứng yên như vậy."
1753 = "Bởi vì cuối cùng――tôi cũng đã có thể truyền đạt tình cảm của mình đến anh Soutetsu.\\nBởi vì――anh Soutetsu cũng đã truyền đạt tình cảm của anh ấy đến tôi."
1755 = "Tôi thở phào nhẹ nhõm.\\nÀ mà, đúng rồi."
1757 = "Chính vì vậy, nó mới trở thành một vết sẹo quá đỗi chân thực,\\nvà chắc chắn, đã luôn bị mọi người ngoảnh mặt làm ngơ."
1760 = "Những nghị viên khoanh tay với vẻ mặt như nhai phải sâu đắng,\\ncũng tuyệt đối không hề ít. Nhưng——"
1763 = "Cả hội trường xôn xao, vang lên những tiếng động dao động.\\nTuy nhiên, ngay cả những người thuộc phe ủng hộ nhiệt tình cũng không thể buông lời phản đối."
1765 = "Trên hàng ghế dự thính, xuất hiện những gương mặt hiếm khi được nhìn thấy."
1768 = "Dù đang nói chuyện qua điện thoại một cách rất đỗi bình thường, cởi mở,\\nnhưng tôi lại có cảm giác như mình phải ngồi thẳng lưng lên vậy――"
1770 = "Trong khi tôi vẫn còn đang lơ lửng trên mây."
1772 = "Người yêu của anh ấy là tôi, chuẩn bị bước vào hội trường――\\nbước vào chiến trường của các nghị sĩ cơ mà."
1773 = "Thân nhiệt bình thường của anh Soutetsu, chắc chắn là thấp hơn tôi mà."
1777 = "Nghe xong phần hỏi đáp,\\nông ta cho rằng thắng bại đã rõ——hay là, đã chịu bỏ cuộc rồi."
1784 = "Đúng vậy. Trong số vô vàn mỏ than bỏ hoang trên toàn quốc,\\nviệc được chọn làm Mỏ than kế thừa kỹ thuật không phải là điều dễ dàng."
1792 = "Thật sâu.\\nPaulette cũng cúi đầu đáp lễ nghị sĩ Shinohara."
1793 = "Paulette đã thẳng thừng phủ nhận,\\nrằng đó “không phải là vết thương cũ”."
1794 = "Lại là bảng lật.\\nLần này không phải là biểu đồ, mà là những bức ảnh."
1795 = "Paulette đưa bảng lật ra phía trước."
1816 = "Chúng tôi, cùng trao cho nhau phần thưởng."
1824 = "Những lời nói vô tư lự của Reina,\\nkhiến tôi bật cười khúc khích."
1826 = "Tiếng bước chân. Lạch bạch tiến lại gần.\\nVẫn còn buồn ngủ sao? Bước chân chậm hơn mọi khi."
1828 = "Trông khác hẳn với một Paulette\\nluôn luống cuống mỗi khi bị la ó."
1830 = "Khi chủ tọa yêu cầu các nghị viên tán thành giơ tay sau đó,\\nkhắp hàng ghế nghị viên, những bàn tay nở rộ như hoa."
1831 = "Như muốn nói 'Chết dở rồi nè!',\\nNagi lấy hai tay bịt chặt miệng lại——っ!?"
1833 = "Nhận ra điều đó, tôi đột nhiên bình tĩnh lại."
1839 = "Đáp lại yêu cầu giơ tay của chủ tọa,\\nngay lập tức, đại đa số cánh tay lại được giơ lên."
1841 = "Mà, ai nhìn hay không nhìn cũng chẳng sao.\\nTôi không định giấu giếm ai bất cứ điều gì cả."
1851 = "Sự “thiếu quyết đoán”,\\nmà nghị sĩ Shinohara vẫn luôn đinh ninh là một quyết định sai lầm."
1852 = "Thật sâu.\\nNghị sĩ Shinohara cúi gập đầu trước Paulette."
1853 = "Giọng nói của nghị sĩ Shinohara khàn đặc,\\nnhưng lại tràn ngập sự bi thương."
1854 = "Nghị sĩ Shinohara đã kết thúc dù vẫn còn thời gian đặt câu hỏi.\\nTheo thông lệ, chủ tọa sẽ hỏi xem còn ai có câu hỏi nào khác không."
1871 = "Đó không phải là chất vấn, mà là một tiếng thở dài."
1872 = "Những nếp nhăn của vị nghị sĩ lão làng hằn sâu hơn.\\nĐôi mắt dưới hàng lông mày trắng muốt nhìn chằm chằm vào Paulette."
1876 = "Trước tiếng nói như bị vắt kiệt đó,\\nrất nhiều nghị sĩ đã gật đầu đồng tình."
1877 = "Dù đã được Densha Hime chấn chỉnh tinh thần, nhưng ngay khoảnh khắc nhìn thấy khuôn mặt anh ấy,\\ntôi lại có cảm giác như mọi thứ lại bị hút về phía anh Soutetsu một cách lâng lâng."
1883 = "Căng thẳng? Phấn khích? Không chỉ nóng lên,\\nmà tay anh ấy――còn hơi run rẩy."
1884 = "Chợt, tôi có chút bận tâm.\\nTôi đã đứng từ cánh gà nhìn lén tình hình trong hội trường, nhưng——"
1886 = "Trước sự bi thương, hay sự hối hận,\\ngiọng nói, ngôn từ của cô ấy không hề dao động dù chỉ một chút."
1907 = "Nó rỉ ra từ tận đáy lòng của vị nghị sĩ lão làng――\\nBởi vì đó là một tiếng thở dài quá đỗi dài, quá đỗi sâu, và quá đỗi nặng nề."
1908 = "Tự dưng tôi thấy thật vui.\\nSự tự tin, đang tuôn trào mãnh liệt."
1910 = "Tập trung sự chú ý vào Mine Treasure,\\nvà thu hút ánh nhìn của nhiều người về nơi đó."
1913 = "Ngay cả trước khi chủ tọa yêu cầu giơ tay,\\nđã có vô số cánh tay giơ lên."
1915 = "Người đó, quả thực là một nàng công chúa đích thực.\\nBởi cô ấy là người chẳng hề bận tâm đến việc lúc này là sáng hay đêm."
1917 = "Nếu vậy, thì tôi tự mình đòi hỏi là được.\\nAnh Soutetsu đã dạy tôi. Đã giúp tôi nhớ lại."
1919 = "Một nụ hôn, nồng nhiệt.\\nSon môi……chắc phải lén tô lại mất thôi."
1924 = "Điều đó thật đáng tin cậy và vững tâm,\\nnhưng hôm nay――tôi lại thấy hơi đáng ghét một chút."
1926 = "Anh Soutetsu hiểu chuyện rất nhanh.\\nLúc nào anh ấy cũng dứt khoát, nhanh chóng định đoạt mọi việc."
1927 = "Anh ấy đang xấu hổ.\\nAnh Soutetsu, đang vô cùng xấu hổ."
1928 = "Bàn tay đang nắm lấy tay tôi nóng rực.\\nKhông phải là ấm áp, mà là rất nóng."
1929 = "Chuyện này cũng liên quan đến việc cải tạo của con bé.\\nPhải báo cho con bé biết ngay mới được."
1946 = "（Không……dù ông ta chưa bỏ cuộc, kết quả cũng sẽ không đổi.）"
1947 = "（Dù vậy, vẫn có thể thắng. Với phần biện luận của Paulette hôm nay,\\nchắc chắn sẽ giành trọn được phiếu bầu của các nghị sĩ phe trung lập.）"
1951 = "（Chụt!）"
1952 = "（Tít）"
1954 = "（Ông ta đã rời ghế——Houshou Mototada.）"
1955 = "（Siết chặt）"
1956 = "（Có lẽ, cô ấy đã nhận được dũng khí.）"
1961 = "（Cái người này thật là……\\ntại sao lúc nào cũng tỏ ra bình thường như vậy chứ.）"
1962 = "（Vậy thì, thế này là được rồi――dù cho việc nhất trí toàn hội đồng như nghị án xin cấp chứng nhận tài sản văn hóa\\ncho Đền Akai Aso là điều không thể mong đợi――）"
1966 = "Dự báo 200 nghìn lượt khách,\\ntuyệt đối không phải là một con số quá phóng đại."

[selections]
