# 日々姫15_終着駅.txt 
[info]

[characters]
599 = "路子"
550 = "双鉄"

[character_subs]
629 = "？？？"
620 = "雙鐵"
# 599 = "路子"

[script]
# lines: 58 
# monologue
# JP: （カトン、トトン、\nタタン、タタン――）
628 = "（Cọc cạch, cọc cạch,\nxình xịch, xình xịch――）"
# monologue
# JP: \x%l列車;#00ffc040;列車%l;#;の音だ。\nいつもと同じ、あの音だ。
581 = "Tiếng \x%l列車;#00ffc040;đoàn tàu%l;#;.\nVẫn là âm thanh quen thuộc đó."
# monologue
# JP: 夢を見ている。\nそう自覚して、けれども目覚めるわけでもない。
567 = "Tôi đang mơ.\nTôi ý thức được điều đó, nhưng cũng không tỉnh dậy."
# 【路子】
# display as ？？？
# JP: 「あの、次の駅で下りたいんですけど」
507 = "「Dạ, em muốn xuống ở ga tiếp theo.」"
# 【双鉄】
# display as 雙鐵
# JP: 「ああ――」
471 = "「À――」"
# monologue
# JP: ……\x%l客車;#00ffc040;客車%l;#;だ。セピアの。\nいつもと同じ景色の中で、けれど、佇む姿は違う。
426 = "……Là \x%l客車;#00ffc040;toa hành khách%l;#;. Màu nâu đỏ.\nGiữa khung cảnh quen thuộc, nhưng bóng dáng đứng đó lại khác biệt."
# 【双鉄】
# display as 雙鐵
# JP: 「路子」
503 = "「Michiko.」"
# 【路子】
# display as 路子
# JP: 「残念、すぐにわかっちゃうねー。\nびっくりさせようって思ったのに」
491 = "「Tiếc thật, anh nhận ra ngay nhỉ.\nEm cứ định làm anh giật mình cơ đấy.」"
# 【双鉄】
# display as 雙鐵
# JP: 「わからんわけがない。僕らは――双子なんだから」
477 = "「Làm sao mà anh không biết được. Chúng ta――là anh em sinh đôi mà.」"
# monologue
# JP: （カトン、トトン、\nタタン、タタン――）
# 628 = "（哐當、哐當、哐當、哐當——）" 
# monologue
# JP: 何年も、鼓膜の奥に張り付き続けてきた音は、\n今日も全く同じ響きで――
560 = "Âm thanh đã bám riết lấy sâu trong màng nhĩ suốt bao nhiêu năm qua,\nhôm nay vẫn vang lên với cùng một âm sắc――"
# monologue
# JP: だから、変化が。\nその意味が際立ってくるようで。
586 = "Chính vì vậy, sự thay đổi.\nÝ nghĩa của nó dường như càng trở nên nổi bật."
# 【双鉄】
# display as 雙鐵
# JP: 「路子……大人になったのか」
500 = "「Michiko…… em đã lớn rồi sao.」"
# monologue
# JP: 僕の双子の妹は、とっくのとうに死んでしまった。\n大人になんて、なれないうちに。
570 = "Đứa em gái sinh đôi của tôi, đã chết từ lâu lắm rồi.\nKhi còn chưa kịp lớn lên."
# monologue
# JP: けれど今、\n僕の目の前にいるのは確かに、大人の路子だ。
527 = "Nhưng bây giờ,\nđứng trước mặt tôi chắc chắn là một Michiko đã trưởng thành."
# 【路子】
# display as 路子
# JP: 「なれたんだよ？　大人に。\nそーちゃんが、大人になってくれたから」
484 = "「Em đã lớn rồi đấy? Trở thành người lớn rồi.\nBởi vì Sou-chan, đã lớn lên mà.」"
# 【双鉄】
# display as 雙鐵
# JP: 「ああ――」
# 471 = "「啊——」" 
# monologue
# JP: その一言で、理解する。双子であるから、理解している。\n路子と僕とは、同じであって違うものだと。
558 = "Chỉ một câu nói đó, tôi đã hiểu. Vì là anh em sinh đôi, nên tôi hiểu.\nMichiko và tôi, tuy là một nhưng lại khác biệt."
# monologue
# JP: 僕らは――\n鏡写しなのだと。
564 = "Chúng tôi――\nchính là hình ảnh phản chiếu của nhau trong gương."
# 【双鉄】
# display as 雙鐵
# JP: 「僕は、子供だったのか」
479 = "「Anh, đã từng là một đứa trẻ sao.」"
# 【路子】
# display as 路子
# JP: 「うん」
473 = "「Vâng.」"
# monologue
# JP: あの事故の傷を抱えたままで、\nずっと、心は子供のままで――
611 = "Mang theo vết thương của vụ tai nạn đó,\ntrái tim tôi, vẫn luôn là một đứa trẻ――"
# 【双鉄】
# display as 雙鐵
# JP: 「僕は、大人になれたのか」
483 = "「Bây giờ, anh đã trưởng thành rồi sao.」"
# 【路子】
# display as 路子
# JP: 「うん」
# 473 = "「嗯」" 
# monologue
# JP: ――けれど日々姫が、僕を包んでくれたから。\n無数の笑顔の繭の中、僕を癒してくれたから。
418 = "――Nhưng vì Hibiki, đã bao bọc lấy tôi.\nTrong kén tằm của vô số nụ cười, con bé đã chữa lành cho tôi."
# 【双鉄】
# display as 雙鐵
# JP: 「それで……路子も」
486 = "「Vậy nên…… Michiko cũng」"
# 【路子】
# display as 路子
# JP: 「違うよ？　そーちゃん」
453 = "「Không phải đâu? Sou-chan.」"
# monologue
# JP: 言わずに、伝わる。\nそれでも路子は、言葉で僕に伝えてくれる。
540 = "Dù không nói ra, vẫn có thể truyền đạt được.\nNhưng Michiko, vẫn dùng lời nói để truyền đạt cho tôi."
# 【路子】
# display as 路子
# JP: 「わたしじゃなくて。世界だよ。\n世界の全部が、そーちゃんを映す鏡なの」
455 = "「Không phải là em. Mà là thế giới cơ.\nToàn bộ thế giới này, chính là tấm gương phản chiếu Sou-chan đấy.」"
# 【双鉄】
# display as 雙鐵
# JP: 「ああ……そうなんだな」
472 = "「A…… ra là vậy.」"
# monologue
# JP: 僕は、そのことを知っている。\n日々姫が、それを教えてくれた。
572 = "Tôi, biết điều đó.\nHibiki, đã dạy cho tôi điều đó."
# monologue
# JP: 僕が生きながら死んでいたころ、世界の全ては死んでいた。\n日々姫が僕の目を開き、僕の世界は色を得た。
565 = "Khi tôi sống mà như đã chết, thì mọi thứ trên thế giới này cũng đã chết.\nHibiki đã mở mắt cho tôi, và thế giới của tôi đã có lại sắc màu."
# 【双鉄】
# display as 雙鐵
# JP: 「世界の姿を決めているのは、\n世界を映す、僕の目だ」
489 = "「Thứ quyết định hình dáng của thế giới,\nchính là đôi mắt của anh, thứ phản chiếu lại thế giới.」"
# 【路子】
# display as 路子
# JP: 「わ！」
470 = "「Oa!」"
# monologue
# JP: セピアが褪せる。\nこの世界さえ、鮮やかな色に塗り替えられる。
592 = "Màu nâu đỏ nhạt dần.\nNgay cả thế giới này, cũng được tô điểm lại bằng những màu sắc rực rỡ."
# monologue
# JP: 僕の心が、知ったから。\n世界は、こんなにも綺麗だと。
554 = "Bởi vì trái tim tôi, đã biết được rằng.\nThế giới này, lại tươi đẹp đến thế."
# 【路子】
# display as 路子
# JP: 「うふふ、綺麗ね。この\x%l客車;#00ffc040;客車%l;#;。ずうっと怖かったけど\n本当はこんなに綺麗だったんだね」
468 = "「Ufufu, đẹp thật đấy. \x%l客車;#00ffc040;Toa hành khách%l;#; này. Lúc nào em cũng thấy sợ\nnhưng hóa ra nó lại đẹp đến thế này nhỉ.」"
# 【双鉄】
# display as 雙鐵
# JP: 「ああ」
# 473 = "「嗯」" 
# monologue
# JP: 怖かったのかと、確認をする必要もない。\n僕もずうっと――ずっと、ずうっと怖かったから。
587 = "Không cần phải xác nhận xem con bé có sợ hay không.\nBởi vì tôi cũng đã luôn――luôn luôn, luôn luôn sợ hãi."
# monologue
# JP: （カタン――コトン――\nタタン――タタン――）
627 = "（Cạch――cạch――\nxình xịch――xình xịch――）"
# monologue
# JP: ……ブレーキショックは感じなかった。\nけれど、線路を叩くリズムが変わり始めている。
430 = "……Không hề cảm thấy chấn động do phanh.\nNhưng, nhịp điệu gõ lên đường ray đang bắt đầu thay đổi."
# monologue
# JP: \x%l列車;#00ffc040;列車%l;#;は、ゆるやかに減速している。\n終着駅は、もう、すぐなのだ。
56 = "\x%l列車;#00ffc040;Đoàn tàu%l;#; đang từ từ giảm tốc.\nGa cuối, đã đến rất gần rồi."
# 【双鉄】
# display as 雙鐵
# JP: 「さよならか」
493 = "「Phải nói lời tạm biệt sao.」"
# 【路子】
# display as 路子
# JP: 「さよならだねぇ」
492 = "「Phải nói lời tạm biệt rồi nhỉ.」"
# monologue
# JP: 路子が、僕に手を伸ばす。\nあのとき僕を突き放し――僕を生かしてくれた手を。
605 = "Michiko, vươn tay về phía tôi.\nBàn tay đã đẩy tôi ra lúc đó――bàn tay đã cứu sống tôi."
# 【双鉄】
# display as 雙鐵
# JP: 「ありがとう、路子。今まで、ずっと」
497 = "「Cảm ơn em, Michiko. Vì tất cả những gì từ trước đến nay.」"
# monologue
# JP: だから、その手を握りしめ。\n今度は僕から――そうっと離す。
574 = "Vì vậy, tôi nắm chặt lấy bàn tay ấy.\nLần này, chính tôi――sẽ nhẹ nhàng buông ra."
# 【路子】
# display as 路子
# JP: 「これからだって、双子だよ？」
481 = "「Từ nay về sau, chúng ta vẫn là anh em sinh đôi mà?」"
# monologue
# JP: 路子が笑う。\n小さな路子そのままの、いたずらっぽい笑顔を浮かべる。
609 = "Michiko mỉm cười.\nNở một nụ cười tinh nghịch, y hệt như Michiko hồi còn nhỏ."
# monologue
# JP: そうだ、路子はこういう顔で笑うんだった――\n思い出したら、泣きたいような気持ちになる。
588 = "Đúng rồi, Michiko thường cười với vẻ mặt như thế này――\nNhớ lại điều đó, tôi có cảm giác như muốn khóc."
# 【路子】
# display as 路子
# JP: 「じゃ、さ。いくから。\nまた会うときは、ずうっと先でいいけど」
462 = "「Vậy, nhé. Em đi đây.\nLần tới gặp lại, hy vọng sẽ là một khoảng thời gian rất dài sau này.」"
# monologue
# JP: \x%l列車;#00ffc040;列車%l;#;が、止まる。\n扉が開く。
55 = "\x%l列車;#00ffc040;Đoàn tàu%l;#; dừng lại.\nCửa mở ra."
# monologue
# JP: その向こうへと、路子の姿が消えていく。\n僕は、一歩も動けない。
606 = "Về phía bên kia, bóng dáng Michiko dần tan biến.\nTôi, không thể nhúc nhích dù chỉ một bước."
# 【路子】
# display as 路子
# JP: 「声だけでもさ、届けに来てね？\n私、おねえちゃんにもあってみたいし」
496 = "「Dù chỉ là giọng nói, anh cũng nhớ gửi đến cho em nhé?\nEm cũng muốn gặp chị gái nữa.」"
# 【双鉄】
# display as 雙鐵
# JP: 「路子！」
504 = "「Michiko!」"
# 【路子】
# display as 路子
# JP: 「ばいばい、そーちゃん」
461 = "「Bái bai, Sou-chan.」"
# monologue
# JP: 扉が閉まる。\n\x%l列車;#00ffc040;列車%l;#;は、再び走りだす――
616 = "Cửa đóng lại.\n\x%l列車;#00ffc040;Đoàn tàu%l;#;, lại tiếp tục chạy――"
# monologue
# JP: なら、僕の居場所は、この\x%l客車;#00ffc040;客車%l;#;じゃない。\n\x%l運転台;#00ffc040;運転台%l;#;へ――僕は、目覚めて。向かうのだ。
614 = "Vậy thì, nơi tôi thuộc về, không phải là \x%l客車;#00ffc040;toa hành khách%l;#; này.\nĐến \x%l運転台;#00ffc040;buồng lái%l;#;――Tôi phải tỉnh dậy. Và đi tới đó."
