# 日々姫15_終着駅.txt 
[info]

[characters]
599 = "路子"
550 = "双鉄"

[character_subs]
629 = "？？？"
620 = "雙鐵"

# 599 = "路子"

[script]
# lines: 58 
# monologue
# JP: （カトン、トトン、\nタタン、タタン――）
628 = "（哐當、哐當、哐當、哐當——）" 

# monologue
# JP: \x%l列車;#00ffc040;列車%l;#;の音だ。\nいつもと同じ、あの音だ。
581 = "是\\x%l列車;#00ffc040;列車%l;#;的聲音。和往常一樣的聲音。" 

# monologue
# JP: 夢を見ている。\nそう自覚して、けれども目覚めるわけでもない。
567 = "我正在做夢。我很清楚這一點，可卻又算不上是清醒的狀態。" 

# 【路子】
# display as ？？？
# JP: 「あの、次の駅で下りたいんですけど」
507 = "「那個，我想在下一站下車」" 

# 【双鉄】
# display as 雙鐵
# JP: 「ああ――」
471 = "「啊——」" 

# monologue
# JP: ……\x%l客車;#00ffc040;客車%l;#;だ。セピアの。\nいつもと同じ景色の中で、けれど、佇む姿は違う。
426 = "……是\\x%l客車;#00ffc040;客運車廂%l;#;。深棕色的。她還是站在和平時一樣的景色當中，但她的模樣卻有所不同。" 

# 【双鉄】
# display as 雙鐵
# JP: 「路子」
503 = "「路子」" 

# 【路子】
# display as 路子
# JP: 「残念、すぐにわかっちゃうねー。\nびっくりさせようって思ったのに」
491 = "「真是遺憾呢，馬上就被你猜出來了。我還想嚇你一跳呢」" 

# 【双鉄】
# display as 雙鐵
# JP: 「わからんわけがない。僕らは――双子なんだから」
477 = "「怎麼可能不知道嘛。我們——可是雙胞胎啊」" 

# monologue
# JP: （カトン、トトン、\nタタン、タタン――）
# 628 = "（哐當、哐當、哐當、哐當——）" 

# monologue
# JP: 何年も、鼓膜の奥に張り付き続けてきた音は、\n今日も全く同じ響きで――
560 = "幾年以來一直震動著鼓膜的聲音。今天也仍舊然響著一樣的節奏——" 

# monologue
# JP: だから、変化が。\nその意味が際立ってくるようで。
586 = "某個變化的意義似乎因此而凸顯出來了。" 

# 【双鉄】
# display as 雙鐵
# JP: 「路子……大人になったのか」
500 = "「路子……你長大了啊」" 

# monologue
# JP: 僕の双子の妹は、とっくのとうに死んでしまった。\n大人になんて、なれないうちに。
570 = "我的雙胞胎妹妹很早以前，在還沒長大的時候就去世了。" 

# monologue
# JP: けれど今、\n僕の目の前にいるのは確かに、大人の路子だ。
527 = "但是，確切無疑，現在在我眼前的是長大了的路子。" 

# 【路子】
# display as 路子
# JP: 「なれたんだよ？　大人に。\nそーちゃんが、大人になってくれたから」
484 = "「我長大了。因為小雙也長大了」" 

# 【双鉄】
# display as 雙鐵
# JP: 「ああ――」
# 471 = "「啊——」" 

# monologue
# JP: その一言で、理解する。双子であるから、理解している。\n路子と僕とは、同じであって違うものだと。
558 = "她的這句話讓我理解了。因為我們是雙胞胎，所以我能理解。路子和我既是統一又是分離的。" 

# monologue
# JP: 僕らは――\n鏡写しなのだと。
564 = "我們——就像互為鏡子裡的倒影一樣。" 

# 【双鉄】
# display as 雙鐵
# JP: 「僕は、子供だったのか」
479 = "「我之前是個孩子嗎」" 

# 【路子】
# display as 路子
# JP: 「うん」
473 = "「嗯」" 

# monologue
# JP: あの事故の傷を抱えたままで、\nずっと、心は子供のままで――
611 = "那場事故的傷痕一直殘留在心裡，內心一直都未曾成長——" 

# 【双鉄】
# display as 雙鐵
# JP: 「僕は、大人になれたのか」
483 = "「我現在長大了嗎」" 

# 【路子】
# display as 路子
# JP: 「うん」
# 473 = "「嗯」" 

# monologue
# JP: ――けれど日々姫が、僕を包んでくれたから。\n無数の笑顔の繭の中、僕を癒してくれたから。
418 = "——但是日日姬卻包容了我。在無數笑臉的蠶繭中，她治癒了我。" 

# 【双鉄】
# display as 雙鐵
# JP: 「それで……路子も」
486 = "「於是，路子你也……」" 

# 【路子】
# display as 路子
# JP: 「違うよ？　そーちゃん」
453 = "「不對。小雙」" 

# monologue
# JP: 言わずに、伝わる。\nそれでも路子は、言葉で僕に伝えてくれる。
540 = "儘管她的想法不用說出口就能傳達給我。可路子她還是選擇用言語來傳達。" 

# 【路子】
# display as 路子
# JP: 「わたしじゃなくて。世界だよ。\n世界の全部が、そーちゃんを映す鏡なの」
455 = "「不是我，是世界。整個世界都是照映小雙的鏡子」" 

# 【双鉄】
# display as 雙鐵
# JP: 「ああ……そうなんだな」
472 = "「啊……是啊」" 

# monologue
# JP: 僕は、そのことを知っている。\n日々姫が、それを教えてくれた。
572 = "我知道這一點。這是日日姬告訴我的。" 

# monologue
# JP: 僕が生きながら死んでいたころ、世界の全ては死んでいた。\n日々姫が僕の目を開き、僕の世界は色を得た。
565 = "我曾經只是一具行屍走肉，那時整個世界全部都死去了。是日日姬讓我的眼睛再次睜開，並且給我的世界塗上了顏色。" 

# 【双鉄】
# display as 雙鐵
# JP: 「世界の姿を決めているのは、\n世界を映す、僕の目だ」
489 = "「決定這個世界的樣子的，是照映這個世界的我的眼睛」" 

# 【路子】
# display as 路子
# JP: 「わ！」
470 = "「哇！」" 

# monologue
# JP: セピアが褪せる。\nこの世界さえ、鮮やかな色に塗り替えられる。
592 = "深棕色漸漸開始褪色了。連這個世界也都開始被塗上鮮艷的色彩。" 

# monologue
# JP: 僕の心が、知ったから。\n世界は、こんなにも綺麗だと。
554 = "因為我的心終於懂得了，世界原來是這麼的美麗。" 

# 【路子】
# display as 路子
# JP: 「うふふ、綺麗ね。この\x%l客車;#00ffc040;客車%l;#;。ずうっと怖かったけど\n本当はこんなに綺麗だったんだね」
468 = "「呵呵呵，這節\\x%l客車;#00ffc040;客運車廂%l;#;可真漂亮。之前一直都很害怕，沒想到它是這麼地漂亮呢」" 

# 【双鉄】
# display as 雙鐵
# JP: 「ああ」
# 473 = "「嗯」" 

# monologue
# JP: 怖かったのかと、確認をする必要もない。\n僕もずうっと――ずっと、ずうっと怖かったから。
587 = "沒有必要去確認她之前究竟有沒有害怕過。因為我也一直——一直都很害怕。" 

# monologue
# JP: （カタン――コトン――\nタタン――タタン――）
627 = "（哐當——哐當——哐當——哐當——）" 

# monologue
# JP: ……ブレーキショックは感じなかった。\nけれど、線路を叩くリズムが変わり始めている。
430 = "……身體沒感覺到剎車帶來的衝擊。但是，列車敲擊線路的節奏開始改變了。" 

# monologue
# JP: \x%l列車;#00ffc040;列車%l;#;は、ゆるやかに減速している。\n終着駅は、もう、すぐなのだ。
56 = "\\x%l列車;#00ffc040;列車%l;#;正在緩緩減速。就快到終點站了。" 

# 【双鉄】
# display as 雙鐵
# JP: 「さよならか」
493 = "「要再見了嗎」" 

# 【路子】
# display as 路子
# JP: 「さよならだねぇ」
492 = "「要再見了呢」" 

# monologue
# JP: 路子が、僕に手を伸ばす。\nあのとき僕を突き放し――僕を生かしてくれた手を。
605 = "路子向我伸出手。那雙在那個時候推了我一把——讓我活了下來的手。" 

# 【双鉄】
# display as 雙鐵
# JP: 「ありがとう、路子。今まで、ずっと」
497 = "「謝謝你，路子。謝謝你至今以來所做的一切」" 

# monologue
# JP: だから、その手を握りしめ。\n今度は僕から――そうっと離す。
574 = "我緊緊握住了她的手。這次是我自己主動輕輕鬆開。" 

# 【路子】
# display as 路子
# JP: 「これからだって、双子だよ？」
481 = "「我們今後也永遠是雙胞胎兄妹」" 

# monologue
# JP: 路子が笑う。\n小さな路子そのままの、いたずらっぽい笑顔を浮かべる。
609 = "路子笑道。她露出了小時候那種壞壞的笑臉。" 

# monologue
# JP: そうだ、路子はこういう顔で笑うんだった――\n思い出したら、泣きたいような気持ちになる。
588 = "沒錯，路子以前笑的時候就會露出這種表情——我一回想起來，就不由得想哭。" 

# 【路子】
# display as 路子
# JP: 「じゃ、さ。いくから。\nまた会うときは、ずうっと先でいいけど」
462 = "「再見了，我該走了。希望下次再見到你是很久很久以後」" 

# monologue
# JP: \x%l列車;#00ffc040;列車%l;#;が、止まる。\n扉が開く。
55 = "\\x%l列車;#00ffc040;列車%l;#;停了下來，門打開了。" 

# monologue
# JP: その向こうへと、路子の姿が消えていく。\n僕は、一歩も動けない。
606 = "路子的身影消失在門的另一側。我則是一步都無法移動。" 

# 【路子】
# display as 路子
# JP: 「声だけでもさ、届けに来てね？\n私、おねえちゃんにもあってみたいし」
496 = "「記得三不五時至少給我傳幾句話哦？我也想見見姐姐呢」" 

# 【双鉄】
# display as 雙鐵
# JP: 「路子！」
504 = "「路子！」" 

# 【路子】
# display as 路子
# JP: 「ばいばい、そーちゃん」
461 = "「再見了，小雙」" 

# monologue
# JP: 扉が閉まる。\n\x%l列車;#00ffc040;列車%l;#;は、再び走りだす――
616 = "門關上了。\\x%l列車;#00ffc040;列車%l;#;再次開始啟動——" 

# monologue
# JP: なら、僕の居場所は、この\x%l客車;#00ffc040;客車%l;#;じゃない。\n\x%l運転台;#00ffc040;運転台%l;#;へ――僕は、目覚めて。向かうのだ。
614 = "那我現在該在的地方就不再是這節\\x%l客車;#00ffc040;客運車廂%l;#;。我應該去\\x%l運転台;#00ffc040;駕駛台%l;#;——我要快點醒來，到那裡去才行。" 
