# 日々姫15_終着駅.txt

[info]

[characters]
550 = "Soutetsu"
599 = "Michiko"

[character_subs]
620 = "Soutetsu"
629 = "???"

[script]
55 = "\\x%l列車;#00ffc040;Đoàn tàu%l;#; dừng lại. Cửa mở ra."
56 = "\\x%l列車;#00ffc040;Đoàn tàu%l;#; đang từ từ giảm tốc. Ga cuối, đã đến rất gần rồi."
418 = "――Nhưng vì Hibiki, đã bao bọc lấy tôi. Trong kén tằm của vô số nụ cười, con bé đã chữa lành cho tôi."
426 = "……Là \\x%l客車;#00ffc040;toa hành khách%l;#;. Màu nâu đỏ. Giữa khung cảnh quen thuộc, nhưng bóng dáng đứng đó lại khác biệt."
430 = "……Không hề cảm thấy chấn động do phanh. Nhưng, nhịp điệu gõ lên đường ray đang bắt đầu thay đổi."
453 = "「Không phải đâu? Sou-chan.」"
455 = "「Không phải là em. Mà là thế giới cơ. Toàn bộ thế giới này, chính là tấm gương phản chiếu Sou-chan đấy.」"
461 = "「Bái bai, Sou-chan.」"
462 = "「Vậy, nhé. Em đi đây. Lần tới gặp lại, hy vọng sẽ là một khoảng thời gian rất dài sau này.」"
468 = "「Ufufu, đẹp thật đấy. \\x%l客車;#00ffc040;Toa hành khách%l;#; này. Lúc nào em cũng thấy sợ nhưng hóa ra nó lại đẹp đến thế này nhỉ.」"
470 = "「Oa!」"
471 = "「À――」"
472 = "「A…… ra là vậy.」"
473 = "「Vâng.」"
477 = "「Làm sao mà anh không biết được. Chúng ta――là anh em sinh đôi mà.」"
479 = "「Anh, đã từng là một đứa trẻ sao.」"
481 = "「Từ nay về sau, chúng ta vẫn là anh em sinh đôi mà?」"
483 = "「Bây giờ, anh đã trưởng thành rồi sao.」"
484 = "「Em đã lớn rồi đấy? Trở thành người lớn rồi. Bởi vì Sou-chan, đã lớn lên mà.」"
486 = "「Vậy nên…… Michiko cũng」"
489 = "「Thứ quyết định hình dáng của thế giới, chính là đôi mắt của anh, thứ phản chiếu lại thế giới.」"
491 = "「Tiếc thật, anh nhận ra ngay nhỉ. Em cứ định làm anh giật mình cơ đấy.」"
492 = "「Phải nói lời tạm biệt rồi nhỉ.」"
493 = "「Phải nói lời tạm biệt sao.」"
496 = "「Dù chỉ là giọng nói, anh cũng nhớ gửi đến cho em nhé? Em cũng muốn gặp chị gái nữa.」"
497 = "「Cảm ơn em, Michiko. Vì tất cả những gì từ trước đến nay.」"
500 = "「Michiko…… em đã lớn rồi sao.」"
503 = "「Michiko.」"
504 = "「Michiko!」"
507 = "「Dạ, em muốn xuống ở ga tiếp theo.」"
527 = "Nhưng bây giờ, đứng trước mặt tôi chắc chắn là một Michiko đã trưởng thành."
540 = "Dù không nói ra, vẫn có thể truyền đạt được. Nhưng Michiko, vẫn dùng lời nói để truyền đạt cho tôi."
554 = "Bởi vì trái tim tôi, đã biết được rằng. Thế giới này, lại tươi đẹp đến thế."
558 = "Chỉ một câu nói đó, tôi đã hiểu. Vì là anh em sinh đôi, nên tôi hiểu. Michiko và tôi, tuy là một nhưng lại khác biệt."
560 = "Âm thanh đã bám riết lấy sâu trong màng nhĩ suốt bao nhiêu năm qua, hôm nay vẫn vang lên với cùng một âm sắc――"
564 = "Chúng tôi―― chính là hình ảnh phản chiếu của nhau trong gương."
565 = "Khi tôi sống mà như đã chết, thì mọi thứ trên thế giới này cũng đã chết. Hibiki đã mở mắt cho tôi, và thế giới của tôi đã có lại sắc màu."
567 = "Tôi đang mơ. Tôi ý thức được điều đó, nhưng cũng không tỉnh dậy."
570 = "Đứa em gái sinh đôi của tôi, đã chết từ lâu lắm rồi. Khi còn chưa kịp lớn lên."
572 = "Tôi, biết điều đó. Hibiki, đã dạy cho tôi điều đó."
574 = "Vì vậy, tôi nắm chặt lấy bàn tay ấy. Lần này, chính tôi――sẽ nhẹ nhàng buông ra."
581 = "Tiếng \\x%l列車;#00ffc040;đoàn tàu%l;#;. Vẫn là âm thanh quen thuộc đó."
586 = "Chính vì vậy, sự thay đổi. Ý nghĩa của nó dường như càng trở nên nổi bật."
587 = "Không cần phải xác nhận xem con bé có sợ hay không. Bởi vì tôi cũng đã luôn――luôn luôn, luôn luôn sợ hãi."
588 = "Đúng rồi, Michiko thường cười với vẻ mặt như thế này―― Nhớ lại điều đó, tôi có cảm giác như muốn khóc."
592 = "Màu nâu đỏ nhạt dần. Ngay cả thế giới này, cũng được tô điểm lại bằng những màu sắc rực rỡ."
605 = "Michiko, vươn tay về phía tôi. Bàn tay đã đẩy tôi ra lúc đó――bàn tay đã cứu sống tôi."
606 = "Về phía bên kia, bóng dáng Michiko dần tan biến. Tôi, không thể nhúc nhích dù chỉ một bước."
609 = "Michiko mỉm cười. Nở một nụ cười tinh nghịch, y hệt như Michiko hồi còn nhỏ."
611 = "Mang theo vết thương của vụ tai nạn đó, trái tim tôi, vẫn luôn là một đứa trẻ――"
614 = "Vậy thì, nơi tôi thuộc về, không phải là \\x%l客車;#00ffc040;toa hành khách%l;#; này. Đến \\x%l運転台;#00ffc040;buồng lái%l;#;――Tôi phải tỉnh dậy. Và đi tới đó."
616 = "Cửa đóng lại. \\x%l列車;#00ffc040;Đoàn tàu%l;#;, lại tiếp tục chạy――"
627 = "（Cạch――cạch―― xình xịch――xình xịch――）"
628 = "（Cọc cạch, cọc cạch, xình xịch, xình xịch――）"

[selections]
