# 共通01_右田双鉄の帰還.txt 
[info]

[characters]
1607 = "清美勝子"
1500 = "ハチロク"
1568 = "帝鉄職員Ａ"
1544 = "右田泰斗"
1540 = "双鉄"
1571 = "帝鉄職員Ｃ"
1497 = "ナビ"

[character_subs]
1672 = "？？？"
1655 = "鐵路人偶"
1548 = "司機"
1573 = "帝鐵職員Ａ"
1574 = "帝鐵職員Ｂ"
1519 = "倖存者"
1575 = "帝鐵職員Ｃ"
1673 = "Ｎａｖｉ"
1663 = "雙鐵"

[script]
# lines: 159 
# 【清美勝子】
# display as ？？？
# JP: 「ついてないわね。こうも見事に直撃されるなんて」
1361 = "「真夠不走運的。竟然趕得這麼分毫不差」" 
# 【ハチロク】
# display as 鐵路人偶
# JP: 「\x%l粘着力;#00ffc040;粘着力%l;#;が著しく低下しています。\n[すなま,1]砂撒きを進言します」
1027 = "「\\x%l粘着力;#00ffc040;黏著力%l;#;大幅下降。建議放沙」" 
# 【清美勝子】
# display as 司機
# JP: 「[ま]撒いた瞬間流されるのがオチでしょうけど。\nま、やらないよりはね――っと」
1317 = "「放下的沙子恐怕轉瞬就會被沖走吧。算了，總比什麼也不做強——吧」" 
# 【ハチロク】
# display as 鐵路人偶
# JP: 「\x%l砂撒き;#00ffc040;砂撒き%l;#;を確認。……\x%l粘着力;#00ffc040;粘着力%l;#;の増加は確認できず。\n脱線の危険があります。速度低減を進言します」
1371 = "「確認開始\\x%l砂撒き;#00ffc040;放沙%l;#;。……\\x%l粘着力;#00ffc040;黏著力%l;#;並未增加。存在脫軌的危險。建議降低速度」" 
# 【清美勝子】
# display as 司機
# JP: 「……やむなしね。\n[しずおか,1]靜岡での\x%l接続;#00ffc040;接続%l;#;は遅らせたくなかったんだけど」
1047 = "「……沒辦法啦。還要在靜岡進行\\x%l接続;#00ffc040;會車%l;#;呢，真不想晚點啊」" 
# 【ハチロク】
# display as 鐵路人偶
# JP: 「すぐに先方の\x%lレイルロオド;#00ffc040;レイルロオド%l;#;へ\x%l共感;#00ffc040;共感%l;#;をつなぎ遅延連絡\n――っ！？　なっ！？　え？　もう一度っ！？」
1375 = "「立即與前方最近的\\x%lレイルロオド;#00ffc040;鐵路人偶%l;#;進行\\x%l共感;#00ffc040;共鳴%l;#;連結告知晚點——！？什…！？哎？請重複！？」" 
# 【清美勝子】
# display as 司機
# JP: 「なにかあったの？　報告を」
1207 = "「出什麼事了？快報告」" 
# 【ハチロク】
# display as 鐵路人偶
# JP: 「続報を――続報を速やかに送りなさい！\n沈黙は許しませんっ！　早く、早く続報をっ！」
1292 = "「後續…請立即告知後續情況！務必回答！立即…立即告知後續情況！」" 
# 【清美勝子】
# display as 司機
# JP: 「冷静になり報告しなさいっ！」
1204 = "「冷靜一下報告情況！」" 
# 【ハチロク】
# display as 鐵路人偶
# JP: 「っ！　――最大限の\x%l制動;#00ffc040;制動%l;#;をください。\n\x%l滑走;#00ffc040;滑走%l;#;せぬよう補助します」
1247 = "「啊！請進行全力\\x%l制動;#00ffc040;減速%l;#;。我來輔助避免\\x%l滑走;#00ffc040;打滑%l;#;」" 
# 【清美勝子】
# display as 司機
# JP: 「\x%l制動;#00ffc040;制動%l;#;了解。この速度から\x%l非常;#00ffc040;非常%l;#;は無理――よね」
1023 = "「\\x%l制動;#00ffc040;減速%l;#;了解。現在這速度\\x%l非常;#00ffc040;緊急%l;#;是沒辦法用了」" 
# 【ハチロク】
# display as 鐵路人偶
# JP: 「……これ以上は\x%l滑走;#00ffc040;滑走%l;#;します。\n限界です。制動力は足りません」
1041 = "「……力度再大就要\\x%l滑走;#00ffc040;打滑%l;#;了。已經到極限了。減速度不足」" 
# 【清美勝子】
# display as 司機
# JP: 「これでも\x%lロック;#00ffc040;ロック%l;#;？　どれだけ\x%l粘着力;#00ffc040;粘着力%l;#;落ちてるのよ」
1427 = "「這都會\\x%lロック;#00ffc040;抱死%l;#;？\\x%l粘着力;#00ffc040;黏著力%l;#;到底低到什麼程度了啊」" 
# 【ハチロク】
# display as 鐵路人偶
# JP: 「これは……もう方法が」
1421 = "「這……已經沒有辦法」" 
# 【清美勝子】
# display as 司機
# JP: 「報告なさい。何の方法？　報告が一秒遅れるだけで、\n危険が何メートル近づくかわかってるでしょうに」
1398 = "「請報告，什麼辦法？你應該清楚，晚一秒報告危險就會接近多少公尺的吧」" 
# 【ハチロク】
# display as 鐵路人偶
# JP: 「状況未確定の事故報告。\x%l発報;#00ffc040;発報%l;#;は[キュウロクヨンニイ,3]9642\x%lレイルロオド;#00ffc040;レイルロオド%l;#;。\n\x%l帝鉄貨物;#00ffc040;帝鉄貨物%l;#;。十五両\x%l編成;#00ffc040;編成%l;#;。全車両喪失の可能性あり」
1335 = "「有狀況尚未確認的事故報告。\\x%l発報;#00ffc040;發報%l;#;的是９６４２\\x%lレイルロオド;#00ffc040;鐵路人偶%l;#;。\\x%l帝鉄貨物;#00ffc040;帝國鐵路貨運%l;#;。十五輛\\x%l編成;#00ffc040;編組%l;#;。可能已全部損失」" 
# 【清美勝子】
# display as 司機
# JP: 「十五両全部！？　って、詳細！」
1219 = "「十五輛全部！？快報告具體情況！」" 
# 【ハチロク】
# display as 鐵路人偶
# JP: 「9642\x%lレイルロオド;#00ffc040;レイルロオド%l;#;は『鉄橋崩落』と――断末魔の\x%l共感;#00ffc040;共感%l;#;で。\n……[ふじがわ,2]冨士川[きょうりょう,1]橋梁が崩落したと」
1457 = "「９６４２\\x%lレイルロオド;#00ffc040;鐵路人偶%l;#;在最後關頭通過\\x%l共感;#00ffc040;共鳴%l;#;發出了“鐵橋坍塌”的消息。……內容是“富士川橋樑坍塌”」" 
# 【清美勝子】
# display as 司機
# JP: 「[ふじがわ,2]冨士川っ！？\nまさかそんなっ！　近すぎるっ！！」
1271 = "「富士川！？竟然是那裡！這太近了！！」" 
# 【ハチロク】
# display as 鐵路人偶
# JP: 「当機に停止の手段無し。\x%l制動;#00ffc040;制動%l;#;力を最大限適正にとっても……七五秒後、止まりきれずに――」
1337 = "「本次列車已無法停車。即便進行極限\\x%l制動;#00ffc040;減速%l;#;也無法剎停，在七十五秒後……」" 
# 【清美勝子】
# display as 司機
# JP: 「お客様乗せてんのよ、無理でも止めるっ！！\n再減速！　そっち主導で！！」
1404 = "「車上還有乘客，無論如何都要停下！！進一步減速，以你為主！！」" 
# 【ハチロク】
# display as 鐵路人偶
# JP: 「再減速了解。\x%l圧;#00ffc040;[あつ,4]ブレーキ力%l;#;、強めます――っ！」
1430 = "「進一步減速了解。加大\\x%l圧;#00ffc040;壓力%l;#;！」" 
# 【清美勝子】
# display as 司機
# JP: 「ああもうっ！　こんなときに横風までっ」
1244 = "「啊啊真是的！這種時候側風還來添亂」" 
# 【ハチロク】
# display as 鐵路人偶
# JP: 「\x%l制動;#00ffc040;制動%l;#;続行。\n――もう少し――圧、もう少しだけ――っ！！！」
1382 = "「繼續\\x%l制動;#00ffc040;減速%l;#;。壓力還差一點，加把勁！！！」" 
# monologue
# JP: （ポ！　ポオォッ！　ポッ！　ポーーーーーーーーッ！）
1668 = "（呼！嗚——！呼！嗚————————！）" 
# 【ハチロク】
# display as 鐵路人偶
# JP: 「……これ以上は\x%l滑走;#00ffc040;滑走%l;#;します。限界です。\n\x%l制動;#00ffc040;制動%l;#;力は足りません」
# 1041 = "「……力度再大就要\\x%l滑走;#00ffc040;打滑%l;#;了。已經到極限了。減速度不足」" 
# 【清美勝子】
# display as 司機
# JP: 「だったら他っ！　停止以外の方策をっ！\n手段は問わない！　目標は転落回避っ！！！」
1438 = "「那就想想別的辦法！剎停以外的方法！什麼辦法都行！能不墜河就行！！！」" 
# 【ハチロク】
# display as 鐵路人偶
# JP: 「停止、以外――。\nでしたら、逆に！」
1217 = "「剎停以外嗎。那就反其道行之！」" 
# 【清美勝子】
# display as 司機
# JP: 「ああ！　そうね、逆に――これしかないわね」
1246 = "「啊！對哦，那就反過來——只有這個辦法了」" 
# 【ハチロク】
# display as 鐵路人偶
# JP: 「お客様、ご着席大丈夫でしょうか」
1166 = "「乘客們不知有沒有好好落座呢」" 
# 【清美勝子】
# display as 司機
# JP: 「\x%l車掌;#00ffc040;車掌%l;#;・[せき]関、\x%l車販;#00ffc040;車販%l;#;・[まゆずみ]黛のコンビでしょ？\nやってるわ。きちんと、彼女たちの仕事を」
1173 = "「今天是關擔當\\x%l車掌;#00ffc040;列車長%l;#;、黛負責\\x%l車販;#00ffc040;車售%l;#;吧？她們一定會做好自己的工作的」" 
# 【ハチロク】
# display as 鐵路人偶
# JP: 「そうですね。\nわたくしたちも、わたくしたちの」
1397 = "「說得也是呢。我們也要，做好我們的…」" 
# 【清美勝子】
# display as 司機
# JP: 「やってやるわよ。一世一代の仕事をね！」
1185 = "「來吧。這輩子就押在這一次了！」" 
# 【清美勝子】
# display as 司機
# JP: 「南無三っ！！！」
1443 = "「阿彌陀佛！！！」" 
# monologue
# JP: ……………………………………………………………………\n……………………………………………………………………
992 = "…………………………………………………………………………………………………………………………………………" 
# 【帝鉄職員Ａ】
# display as 帝鐵職員Ａ
# JP: 「ここだ！　落ちてない！　落ちてないぞっ！」
1262 = "「在這裡！沒有墜河！沒有墜河！」" 
# 【右田泰斗】
# display as 帝鐵職員Ｂ
# JP: 「奇跡だな。止まってくれたというのか」
1266 = "「奇蹟啊。居然停下來了嗎」" 
# 【帝鉄職員Ａ】
# display as 帝鐵職員Ａ
# JP: 「いや、転覆だ！　\x%l脱線転覆;#00ffc040;脱線転覆%l;#;！！\nだが、全滅よりはよほどマシだっ！！」
1160 = "「不，傾覆了！\\x%l脱線転覆;#00ffc040;脫軌傾覆%l;#;！！不過總比全滅好多了！！」" 
# 【右田泰斗】
# display as 帝鐵職員Ｂ
# JP: 「ぅ……む――これは――先頭\x%l客車;#00ffc040;客車%l;#;、特にひどいな――\nおい、探すんだ。生存者を探して救助しろ」
1423 = "「這是……靠前的\\x%l客車;#00ffc040;客運車廂%l;#;，比後面更嚴重啊。喂，快來幫忙尋找倖存者，救助他們」" 
# monologue
# JP: ……………………………………………………………………\n……………………………………………………………………
# 992 = "…………………………………………………………………………………………………………………………………………" 
# monologue
# JP: ……声、誰かの声が聞こえる。\n……感じる……手……誰かが、僕を……ゆすってる。
1012 = "……聲音，好像聽到了誰的聲音。……感覺到……手……有誰，在……搖晃我。" 
# monologue
# JP: なら、僕……生きてる……\n僕だけ……僕の、はんぶんは――
1647 = "這麼說，我……還活著……只有我……我的，另一半——" 
# 【双鉄】
# display as 倖存者
# JP: 「み……ち……」
1403 = "「路……子……」" 
# 【帝鉄職員Ｃ】
# display as 帝鐵職員Ｃ
# JP: 「いました！　生存者！\n呼吸ありますが――重症ですっ」
1309 = "「找到了！有倖存者！還有呼吸，但是傷勢很重」" 
# 【帝鉄職員Ａ】
# display as 帝鐵職員Ａ
# JP: 「子供じゃないか！　おいっ、君！」
1432 = "「還是個孩子！喂，醒醒！」" 
# 【帝鉄職員Ｃ】
# display as 帝鐵職員Ｃ
# JP: 「ダメです！　動かさないで！　頭から出血しています」
1152 = "「不行！別動他！頭上在出血呢」" 
# monologue
# JP: ……出血、僕の、頭……から。\nなら、このまま――けど……………………
1004 = "……出血，我的，頭……上。那索性，就這樣——可是……………………" 
# monologue
# JP: それじゃあ、みちが――\n僕を、突き飛ばしてくれた[いもうと,1]路子が――
1652 = "那樣的話，路子——推開了我的[妹妹,1]路子不就——" 
# 【帝鉄職員Ａ】
# display as 帝鐵職員Ａ
# JP: 「止血しろ！　助けるんだ！　早くっ！」
1189 = "「先止血！準備搶救！抓緊！」" 
# 【帝鉄職員Ｃ】
# display as 帝鐵職員Ｃ
# JP: 「もちろんです！　\nですが――、一刻も早く病院につれていかないとっ」
1440 = "「那是自然！可是，得儘快送他去醫院」" 
# 【帝鉄職員Ａ】
# display as 帝鐵職員Ａ
# JP: 「どう移送する！？　救援車は一番近くて[こうづ,2]国兎津だぞ！\n徒歩で\x%l保線;#00ffc040;保線%l;#;基地まで戻った方がまだ早い！」
1300 = "「怎麼送啊！？最近的救援車輛可在國府津啊！徒步走回\\x%l保線;#00ffc040;巡線%l;#;基地還更快些！」" 
# 【帝鉄職員Ｃ】
# display as 帝鐵職員Ｃ
# JP: 「無理です！　それではとても保たないっ」
1150 = "「不可能的！他根本堅持不了那麼久」" 
# 【帝鉄職員Ａ】
# display as 帝鐵職員Ａ
# JP: 「ならどうしろとっ！！」
1434 = "「那你說怎麼辦！！」" 
# monologue
# JP: ……ダメ、だ。\n聞いてること、意味、わからない。
1000 = "……不行……了。聽到的話……已經……理解不了了。" 
# monologue
# JP: …………なんで、こんなに眠いんだ――\nさっきまで、僕……寝てた、の、に…………
996 = "…………為什麼，這麼睏呢——明明，直到剛才……我都還……在……睡…………" 
# 【右田泰斗】
# display as 帝鐵職員Ｂ
# JP: 「支社に\x%lエアクラ;#00ffc040;エアクラ%l;#;――飛ぶ奴、試作機があるだろう。\nあれを要請しろ」
1208 = "「分公司不是有能飛的\\x%lエアクラ;#00ffc040;空凝機%l;#;測試機嗎。去調那個來」" 
# 【帝鉄職員Ａ】
# display as 帝鐵職員Ａ
# JP: 「あの試作機か！　いや、だが――この風雨だぞっ！？」
1437 = "「那台測試機！慢著，狂風暴雨的——可以嗎！？」" 
# 【右田泰斗】
# display as 帝鐵職員Ｂ
# JP: 「無人で飛ばせ。たとえ落ちても誰も死なん。\n放っておけばこの子は死ぬ。考える余地があるか？」
1155 = "「不要坐人就是了。就算墜機也不會有傷亡。不拼一把的話這孩子可就沒命了。哪還有空瞻前顧後啊？」" 
# 【帝鉄職員Ａ】
# display as 帝鐵職員Ａ
# JP: 「わかった！　この子の命が最優先だと要請しよう。\nおいキミ、頑張れ。試作機が来るまで死ぬんじゃないぞ」
1268 = "「好的！申請調用時我會跟他們說，以救這孩子為首要任務。孩子，加油啊。測試機來之前可別死了」" 
# 【帝鉄職員Ｃ】
# display as 帝鐵職員Ｃ
# JP: 「死なせませんよ！　死なせませんともっ！！」
1151 = "「不會讓你死的！絕不會讓你死的！！」" 
# 【右田泰斗】
# display as 帝鐵職員Ｂ
# JP: 「飛ばせ、飛ばすんだ、飛行型をっ。\nこの子の命が最優先だ、なにを置いても飛ばさせろ！」
1401 = "「起飛，馬上讓飛行型起飛。這孩子的性命是第一位的，無論如何都要馬上起飛！」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「双鉄様。問題なく雨雲を抜けました」
1448 = "「雙鐵少爺。平安穿過雨雲了」" 
# 【双鉄】
# display as 雙鐵
# JP: 「…………」
1033 = "「…………」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「が、雨雲を突っ切れとのご命令は今後お控えください。\nナビは、双鉄様の命を最優先として判断します」
1157 = "「不過，今後請儘量不要下達穿過雨雲這樣的命令。Ｎａｖｉ的一切判斷皆以雙鐵少爺的生命安全為最優先」" 
# 【双鉄】
# display as 雙鐵
# JP: 「…………」
# 1033 = "「…………」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「双鉄様の『急ぎなので、無理をしても』とのご命令と、\n双鉄様の命を最優先することとには、矛盾があります」
1447 = "「雙鐵少爺“趕時間，無論如何也要穿過”這樣的命令，和雙鐵少爺的生命安全之間，是有矛盾的」" 
# 【双鉄】
# display as 雙鐵
# JP: 「…………」
# 1033 = "「…………」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「矛盾の判断には大きな演算能力を必要とし、\nその負荷が双鉄様の安全を脅かすという……双鉄様？」
1260 = "「在矛盾中做出判斷需要大量的計算能力，而這個負荷又會威脅到雙鐵少爺的安全……雙鐵少爺？」" 
# 【双鉄】
# display as 雙鐵
# JP: 「うん。すまない。少し寝ていた」
1252 = "「嗯。不好意思。打了個瞌睡」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「これはこれは。\n起こしてしまいましたか。すみません」
1234 = "「哎呀我沒注意到。把您吵醒了嗎。對不起」" 
# 【双鉄】
# display as 雙鐵
# JP: 「意図的だろう？\n僕は、うなされていたのだろうな」
1184 = "「你其實是故意的吧？我剛才估計是又做噩夢了」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「意図的などと、ご冗談を。ナビは物です。物品です。\n何を意図することもございません」
1236 = "「哪有故意，您說笑了。Ｎａｖｉ只是一件東西，一件物品。並不會故意去做任何事」" 
# 【双鉄】
# display as 雙鐵
# JP: 「うむ、そうか。\nお前がそういうのなら、そうなのだろうな」
1256 = "「嗯，好吧。既然你這麼說，就當是這樣吧」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「はい、左様です。\nナビは単なる[ドライバー,3]操縦機器ですので」
1332 = "「是的，正是如此。Ｎａｖｉ只是單純的駕駛儀而已」" 
# 【双鉄】
# display as 雙鐵
# JP: 「訂正しておけ。お前は――ナビは、\n“単なる”ではなく、最上級のドライバーだ」
1425 = "「這裡得訂正一下。你——Ｎａｖｉ，不只是“單純的”，而是最棒的駕駛儀」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「ご命令を了解しました。\nナビは、双鉄様の基準においては最上級の[ドライバー,3]操縦機器です」
1288 = "「已收到您的命令。Ｎａｖｉ，以雙鐵少爺的標準，是最棒的駕駛儀」" 
# 【双鉄】
# display as 雙鐵
# JP: 「かわいくないな」
1363 = "「真是一點都不可愛啊」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「物品ですので」
1258 = "「因為我只是物品而已」" 
# monologue
# JP: ……物との会話。\nあるいは、ただの独り言。
1009 = "……我對著東西說話。或者說，只是自言自語。" 
# monologue
# JP: だとしても、\n鈍り、曇り、沈みかけていた心が少し、浮き上がる。
1521 = "儘管如此，日漸遲鈍、陰雲籠罩、眼見將沉入深淵的心卻得到了些許喘息。" 
# monologue
# JP: （夢から覚めて……\n現実もまた、夢の続きか）
1671 = "（從夢境中醒來……而現實，卻又如夢境的延續嗎）" 
# monologue
# JP: あの事故のときと同様に、\nナビに、救い上げられている。
1562 = "如同那次事故時一樣，我又一次為Ｎａｖｉ所救。" 
# monologue
# JP: そうして、[おひとよ,2]御一夜――\n眼下に広がるこの町も、僕を間違いなく救ってくれた。
1628 = "而此時，御一夜——下方映入眼簾的城鎮，也同樣拯救過我。" 
# 【双鉄】
# display as 雙鐵
# JP: 「……何年ぶりになるか」
1045 = "「……多少年沒回來了呢」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「六年四ヶ月ぶりです、双鉄様」　
1195 = "「六年四個月了，雙鐵少爺」" 
# monologue
# JP: 上空から見下ろす御一夜の町並みは、\n出て行ったときと、何も変わっていないように見える。
1592 = "我從上空俯瞰御一夜的街道。與當初離開時相比，這裡似乎一點都沒改變。" 
# 【双鉄】
# display as 雙鐵
# JP: 「六年四ヶ月」
1194 = "「六年四個月」" 
# monologue
# JP: だが――その内側は変わりつつある。\n僕の帰還を余儀なくするほど。
1610 = "然而——變化卻在暗處悄然蔓延。以至我別無選擇，唯有回鄉。" 
# 【双鉄】
# display as 雙鐵
# JP: 「何かが変わるには十分な時間――いや。\n変わらずにいるには、長すぎる時間なのかもしれない」
1429 = "「這麼長時間，產生任何變化都不無可能——不，過了這麼久，一成不變才怪吧」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「ご命令を了解しました。\n同期間における御一夜市の変化をご報告します」
1278 = "「已收到您的命令。立即向您報告該期間御一夜市發生的變化」" 
# monologue
# JP: 感傷的にすぎてしまったかもしれない呟きを――\n“意図的”に、ナビは曲解して返す。
1674 = "Ｎａｖｉ“故意”曲解了我脫口而出的感傷言語，並回答道。" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「行政に関しての最大の変化は、市長です。\n現在の市長には[ひない,1]雛衣・ポーレットが就任しています」
1390 = "「行政方面最大的變化，就是市長了。現在市長是由雛衣·波萊特擔任」" 
# 【双鉄】
# display as 雙鐵
# JP: 「[ひない,1]雛衣というと、前の市長の？」
1450 = "「雛衣啊，是前任市長的？」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「はい。ご息女です。\nしかし、行政手腕は遺伝しなかったとの評判です」
1329 = "「是的，是前任市長千金。不過依風評看來，她並沒有遺傳前任市長的執政能力」" 
# 【双鉄】
# display as 雙鐵
# JP: 「世評が無能と断じているのは、前職か？　現職か？」
1391 = "「被說無能的是前任呢，還是現任？」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「後者のようです、双鉄様」
1176 = "「似乎是後者，雙鐵少爺」" 
# 【双鉄】
# display as 雙鐵
# JP: 「なるほど。それゆえ、御一夜は衰退し、\n\x%lエアクラ;#00ffc040;エアクラ%l;#;工場の誘致話が持ち上がったわけか？」
1224 = "「原來如此。所以御一夜才會衰退成這樣，甚至提出讓\\x%lエアクラ;#00ffc040;空凝機%l;#;工廠落戶嗎？」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「その詳細まではわかりかねます」
1196 = "「其中詳細暫時不得而知」" 
# 【双鉄】
# display as 雙鐵
# JP: 「おっと」
1238 = "「唔…」" 
# monologue
# JP: 声の調子は変わらない。
1641 = "語調一如平常。" 
# monologue
# JP: が――少し怒って聞こえるのは、\n僕の気のせいだけなのだろうか。
1514 = "但聽在我耳中，似有一絲慍意，可能只是我多心了吧。" 
# 【双鉄】
# display as 雙鐵
# JP: 「ナビ。お前も\x%lエアクラ;#00ffc040;エアクラ%l;#;の仲間だったな。\n気を悪くしたか？」
1461 = "「Ｎａｖｉ。說起來你也是\\x%lエアクラ;#00ffc040;空凝機%l;#;的一員啊。我的話是不是讓你不開心了？」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「まさか。ナビは物品ですので」
1394 = "「言重了。Ｎａｖｉ只是物品而已」" 
# monologue
# JP: \x%lエアクラ;#00ffc040;エアクラ%l;#;――正式名称をエアロクラフテック機関。\nエアロ＝クラフテック社による“世界を変えた”発明品。
78 = "\\x%lエアクラ;#00ffc040;空凝機%l;#;的正式名稱是空凝機引擎。是空凝科技公司堪稱“改變世界”的發明。" 
# monologue
# JP: 地磁気と太陽光とを利用する超高効率のその発動機は、\n化石燃料エンジンをほぼ、駆逐した。
1533 = "利用地磁與太陽光的超高效率發動機，幾乎將化石燃料引擎完全淘汰。" 
# 【双鉄】
# display as 雙鐵
# JP: 「怒ってないなら良かったさ」
1344 = "「沒生氣就好」" 
# monologue
# JP: 地上を行くもの、水面を行くもの、空を行くもの――
1554 = "地上行駛的，水面航行的，空中飛翔的——" 
# monologue
# JP: \x%lエアクラ;#00ffc040;エアクラ%l;#;機関を使う乗り物全ても、機関同様、\n単に“\x%lエアクラ;#00ffc040;エアクラ%l;#;”と総称される。
1516 = "使用了\\x%lエアクラ;#00ffc040;空凝機%l;#;引擎的全部載具，與引擎同樣被簡化統稱為“\\x%lエアクラ;#00ffc040;空凝機%l;#;”。" 
# 【双鉄】
# display as 雙鐵
# JP: 「お前のように優秀なナビを、\n敵に回したくはないからな」
1308 = "「我可不想與你這麼優秀的導航系統為敵」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「敵も味方も、双鉄様のご命令のままに。\nナビはあくまで物品ですので」
1350 = "「無謂敵我，唯雙鐵少爺馬首是瞻。Ｎａｖｉ只是物品而已」" 
# 【双鉄】
# display as 雙鐵
# JP: 「ふむ」
1239 = "「唔」" 
# monologue
# JP: ナビという物品。\x%lエアクラ;#00ffc040;エアクラ%l;#;・ナビ。\n\x%lエアクラ;#00ffc040;エアクラ%l;#;とともに急発展し、一般にまで普及した擬似知能。
1637 = "被我稱作Ｎａｖｉ的物品，全稱\\x%lエアクラ;#00ffc040;空凝機%l;#;導航系統，是隨著\\x%lエアクラ;#00ffc040;空凝機%l;#;的高速發展而廣為普及的人工智慧。" 
# monologue
# JP: “\x%l共感;#00ffc040;共感%l;#;運用”というその最大の特徴は、\n交通渋滞という概念を過去のものとした。
1589 = "憑藉其“\\x%l共感;#00ffc040;共鳴%l;#;同步”這一最大特徵，使得“交通堵塞”這個概念徹底成了過去。" 
# 【双鉄】
# display as 雙鐵
# JP: 「お前たちは確かに便利な物品だよ。\nナビと\x%lエアクラ;#00ffc040;エアクラ%l;#;なしでは、移動一つさえ大騒動だ」
1181 = "「你們這些物品確實很方便啊。要是沒有導航系統和\\x%lエアクラ;#00ffc040;空凝機%l;#;，光交通就會是個大問題」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「その便利な物品を作る工場を、双鉄様は、\n御一夜に誘致してほしくはないとおっしゃっています」
1352 = "「然而雙鐵少爺卻說，不想讓生產這些方便物品的工廠在御一夜落戶」" 
# monologue
# JP: 事実確認。\nの皮をかぶった、詰問としか聞こえない。
1621 = "確認事實。字面雖是如此，但我聽來，完全就是責問。" 
# monologue
# JP: 世間一般のナビよりも、\nうちのはどうにも人間臭く思えてならない。
1614 = "相較世上的普通導航系統，我的這台簡直處處散發著人類的氣息。" 
# 【双鉄】
# display as 雙鐵
# JP: 「エゴだがな。\nこの光景を目にしてしまえば――」
1422 = "「這只是出於我的私心。看著眼前這幅景色——」" 
# monologue
# JP: 僕の意を酌み、ナビが機体を傾ける。
1623 = "稍加斟酌後，Ｎａｖｉ傾轉了機身。" 
# monologue
# JP: だから視線はすぐに捉える――眼下を流れる光の帯を。\n太陽の煌きを豊かに返す、御一夜の象徴、クマ川を。
1551 = "因此，我的視線立即捕捉到了，眼前流淌著的光帶——那將太陽的光芒反射得五彩繽紛的，正是御一夜的象徵，隈河。" 
# 【双鉄】
# display as 雙鐵
# JP: 「御一夜以外に作って欲しいと思わずにはいられんのだ。\nここは、僕のもうひとつの故郷なのだから」
1359 = "「看到這景色自然會希望不要在御一夜進行生產。這裡可是我的第二故鄉啊」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「承知しています。まもなく、目的地の[みぎたいちしゅぞうもと,5]右田一酒造元です。\n上空を一度通過しますか？」
1170 = "「了解。即將抵達目的地，右田一釀酒廠。要從上空先飛過一次嗎？」" 
# 【双鉄】
# display as 雙鐵
# JP: 「そうだな、着水前に一度上から見ておこう」
1168 = "「也是，在水上降落前先從空中俯瞰一下吧」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「ご命令を了解しました」
1289 = "「已收到您的命令」" 
# monologue
# JP: 機体姿勢を即座に戻し、けれど航路は変更しない。
1601 = "機身迅速回正，然而航線卻未有絲毫變化。" 
# monologue
# JP: どうやら僕の“ご命令”は、\nあらかじめ予測されていたらしい。
1616 = "看來我的“命令”完全不出Ｎａｖｉ的預料。" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「目的地上空です」
1213 = "「到達目的地上空」" 
# 【双鉄】
# display as 雙鐵
# JP: 「言われずともだ」
1426 = "「這裡我自然認得」" 
# monologue
# JP: 見間違えようはずもない。\n古ぼけた瓦屋根、庭にずらりと並んだタンク。
1593 = "我絕不會認錯——那古樸的瓦房頂，還有庭院裡整齊排列的槽罐。" 
# monologue
# JP: 生家という言葉に習うのならば、僕の育家である\n――右田一酒造元の、その姿を。
1634 = "若是類比誕生之家這個詞彙的話，這就是我的養育之家——右田一釀酒廠。" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「高度を下げた方がよろしいでしょうか？」
1452 = "「需要降低高度嗎？」" 
# 【双鉄】
# display as 雙鐵
# JP: 「いや、仕事の邪魔になっては――おや？」
1163 = "「不，影響她們工作就不好了——哦？」" 
# monologue
# JP: はるか眼下に、豆粒のような人影が、\nなのに大きく動いている。
1648 = "遠遠的下方，一個只有豆粒大小的身影，卻在大幅度地舞動著。" 
# monologue
# JP: ぴょこぴょこ飛び跳ね、\nそれからダっ、と、蔵の中へと駆け込んでいく。
1560 = "她歡呼雀躍地來回奔跑，然後閃電般衝進了酒窖。" 
# 【双鉄】
# display as 雙鐵
# JP: 「[ひびき,2]日々姫か。相変わらずの様子だな。\n少しは大人になったかと想像していたのだが」
1326 = "「日日姬啊。還是老樣子呢。虧我還想像了她成熟一點的樣子」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「明確な変化が見られます。\n以前の日々姫様には無い行動です」
1433 = "「還是有明確可見的變化的。以前的日日姬小姐是不會這樣做的」" 
# 【双鉄】
# display as 雙鐵
# JP: 「ああ――なるほど、確かに」
1240 = "「啊——原來如此，的確」" 
# monologue
# JP: 以前のままの日々姫ならば、\n“蔵へ駆け込み報告をする”などと決してしなかったろう。
1632 = "若是從前的日日姬，斷然不會“衝進酒窖去報告”的吧。" 
# monologue
# JP: 良くて、機影をそのまま追ったか……\n虫の居所が悪ければ、知らん顔さえしたかもしれない。
1584 = "心情好的話，她會直接追著Ｎａｖｉ的影子跑……若是不好的話，說不定根本不會理睬。" 
# 【双鉄】
# display as 雙鐵
# JP: 「ならば、実地で確かめるとしよう。\nナビ、最適地点に着水してくれ」
1323 = "「既然這樣，還是親自去確認一下吧。Ｎａｖｉ，找個最合適的地方降落吧」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「ご命令を了解しました。\n着水地点をサーチします」
1282 = "「已收到您的命令。開始搜索降落地點」" 
# monologue
# JP: “試作機”だった\x%lエアクラ;#00ffc040;エアクラ%l;#;は、静かに高度を下げていく。
1597 = "曾是“測試機”的這台\\x%lエアクラ;#00ffc040;空凝機%l;#;，開始安靜地下降。" 
# monologue
# JP: 十数年前の技術の粋は、\nいまだ、わずかな錆さえ見せない。
1535 = "十幾年前的技術結晶，即便時隔多年，仍然寶刀未老。" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「あと120秒で着水します。\n着水後は\x%l駐機;#00ffc040;駐機%l;#;モードに移行してよろしいですか？」
1275 = "「將在１２０秒後降落。降落後是否要切換到\\x%l駐機;#00ffc040;停靠%l;#;模式？」" 
# 【双鉄】
# display as 雙鐵
# JP: 「うむ。頼む」
1254 = "「嗯。麻煩」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「ご命令を了解しました。\n着水後、\x%l駐機;#00ffc040;駐機%l;#;モードに移行します」
1285 = "「已收到您的命令。降落後切換為\\x%l駐機;#00ffc040;停靠%l;#;模式」" 
# monologue
# JP: クマ川の水が近くなる。\n上から青に見えていたのが、深い緑に見えてくる。
1662 = "隨著高度的降低，從上空看來呈現青色的隈河，逐漸變成了深綠色。" 
# monologue
# JP: 着水し、ナビの\x%l翼端;#00ffc040;翼端%l;#;を歩いて渡り岸に下りれば――\n御一夜だ。
1659 = "降落後，只要從Ｎａｖｉ的\\x%l翼端;#00ffc040;翼梢%l;#;走上岸，就算到御一夜了。" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「着水します。\n双鉄様――」
1223 = "「即將降落。雙鐵少爺」" 
# monologue
# JP: 沈黙。\nナビにはありえないほど、長い沈黙。
1606 = "沉默。對Ｎａｖｉ來說，這算是難以想像的漫長沉默。" 
# 【双鉄】
# display as 雙鐵
# JP: 「どうした、ナビ？」
1299 = "「怎麼了，Ｎａｖｉ？」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「『お疲れ様でした』と『いってらっしゃいませ』。\nどちらが適正なご挨拶でしょうか？」
1032 = "「“您辛苦了”和“您慢走”。我應該說哪句合適呢？」" 
# 【双鉄】
# display as 雙鐵
# JP: 「ああ」
1242 = "「啊」" 
# monologue
# JP: 帰宅したときは『お疲れ様』。\n目的地についたときには『いってらっしゃい』。
1550 = "回家時是“您辛苦了”。到達目的地時是“您慢走”。" 
# monologue
# JP: それが、ナビのデフォルトの挨拶だ。
1646 = "這兩句是Ｎａｖｉ預設的問候語。" 
# 【双鉄】
# display as 雙鐵
# JP: 「お前に任せる。\nどちらでもそう大差はないさ」
1445 = "「隨你選吧。其實沒什麼區別」" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「ご命令を了解しました。\nそれでは、双鉄様」
1280 = "「已收到您的命令。請坐穩，雙鐵少爺」" 
# monologue
# JP: そして、着水。\n立ったであろう水音は、川の流れにかき消される。
1677 = "Ｎａｖｉ降落在水面上。降落激起的水聲就如一朵小浪花般，迅速消失在水流中。" 
# 【ナビ】
# display as Ｎａｖｉ
# JP: 「『どうぞ、お気をつけていってらっしゃいませ』」
1029 = "「“您慢走，路上請多加小心”」" 
